/**
 * opencode.ts — OpenCode adapter (npm `opencode-ai` 1.x / `@opencode/cli` 2.x,
 * binary `opencode`).
 *
 * OpenCode is a terminal coding agent whose instructions file is `AGENTS.md`
 * (project, with a `CLAUDE.md` fallback, and `~/.config/opencode/AGENTS.md`;
 * https://opencode.ai/docs/rules/). The rule sets go there through the
 * shared `AGENTS.md` writer (agentsMd.ts).
 *
 * The governance-critical half is a **plugin**, not a hook file: OpenCode
 * loads `.opencode/plugins/*.js` into its own process and runs the plugin's
 * `tool.execute.before` hook (1.x) / `tool execute.before` hook (2.x) before
 * every tool call; throwing refuses the call. That plugin is generated by
 * `@intutic/sync-daemon`'s `openCodeHooks.ts`, the same split Muse and Grok
 * use for their hook writers. This adapter does not write `opencode.json`;
 * the sync daemon's `mcpAutoWrite.ts` edits its `mcp` block only (TD-487) —
 * see the writer's module doc.
 *
 * HLD §3.14 — Harness Onboarding Matrix
 * @module
 */

import { join } from 'node:path'
import { access } from 'node:fs/promises'
import { homedir } from 'node:os'
import { HarnessType } from '@intutic/shared-types'
import type { SyncSopEntry } from '@intutic/shared-types'
import type { IHarnessAdapter } from './types.js'
import { writeOpenCodeHooks } from '@intutic/sync-daemon/harness/openCodeHooks'
import { AGENTS_MD, agentsMdHash, writeAgentsMd } from './agentsMd.js'

/** `$OPENCODE_CONFIG_DIR` or `~/.config/opencode` — the user-level config dir. */
function openCodeConfigDir(): string {
  return process.env.OPENCODE_CONFIG_DIR || join(homedir(), '.config', 'opencode')
}

export const opencodeAdapter: IHarnessAdapter = {
  type: HarnessType.OPENCODE,
  configFileName: AGENTS_MD,

  async detect(workspaceRoot: string): Promise<boolean> {
    // 1. Project-local `.opencode/` directory or `opencode.json{,c}`. Not
    //    AGENTS.md alone — Muse and Grok read the same file.
    for (const marker of ['.opencode', 'opencode.json', 'opencode.jsonc']) {
      try {
        await access(join(workspaceRoot, marker))
        return true
      } catch { /* not here */ }
    }

    // 2. User-level config dir — installed but never run in this workspace.
    try {
      await access(openCodeConfigDir())
      return true
    } catch { /* not here */ }

    // 3. `opencode` (or the 2.x line's `opencode2`) binary on PATH.
    const pathDirs = (process.env.PATH ?? '').split(process.platform === 'win32' ? ';' : ':')
    try {
      const { accessSync } = await import('node:fs')
      for (const dir of pathDirs) {
        for (const bin of ['opencode', 'opencode2']) {
          try { accessSync(join(dir, bin)); return true } catch { /* not here */ }
        }
      }
    } catch { /* ignore */ }
    return false
  },

  /** The plugin gate. `intutic connect` has no workspace id in scope — same
   *  limitation `museAdapter` has — the sync daemon re-runs this with a real
   *  one on the next cycle. */
  async installGate(workspaceRoot: string, proxyUrl: string): Promise<void> {
    await writeOpenCodeHooks(workspaceRoot, proxyUrl, '')
  },

  writeConfig(workspaceRoot: string, sops: SyncSopEntry[], proxyUrl: string): Promise<string | null> {
    return writeAgentsMd(workspaceRoot, sops, proxyUrl)
  },

  readCurrentHash(workspaceRoot: string): Promise<string | null> {
    return agentsMdHash(workspaceRoot)
  },
}
