/**
 * opencode.ts — OpenCode adapter (npm `opencode-ai` 1.x / `@opencode/cli` 2.x,
 * binary `opencode`).
 *
 * OpenCode is a terminal coding agent whose instructions file is `AGENTS.md`
 * (project, with a `CLAUDE.md` fallback, and `~/.config/opencode/AGENTS.md`)
 * — delivered here through the shared markdown builder every other
 * `AGENTS.md`/`CLAUDE.md` harness uses, so it grows no rules format of its
 * own.
 *
 * The governance-critical half is a **plugin**, not a hook file: OpenCode
 * loads `.opencode/plugins/*.js` into its own process and runs the plugin's
 * `tool.execute.before` hook (1.x) / `tool execute.before` hook (2.x) before
 * every tool call; throwing refuses the call. That plugin is generated by
 * `@intutic/sync-daemon`'s `openCodeHooks.ts`, the same split Muse and Grok
 * use for their hook writers. `opencode.json` is not written — see the
 * writer's module doc.
 *
 * HLD §3.14 — Harness Onboarding Matrix
 * @module
 */

import { join, dirname } from 'node:path'
import { access, writeFile, rename, mkdir } from 'node:fs/promises'
import { homedir } from 'node:os'
import { HarnessType } from '@intutic/shared-types'
import type { SyncSopEntry } from '@intutic/shared-types'
import type { IHarnessAdapter } from './types.js'
import { hashFile } from '../lib/hash.js'
import { buildMarkdownContent } from './base.js'
import { writeOpenCodeHooks } from '@intutic/sync-daemon/harness/openCodeHooks'

/** Workspace-relative rules file. OpenCode reads this, falling back to CLAUDE.md. */
const CONFIG_FILE = 'AGENTS.md'

/** `$OPENCODE_CONFIG_DIR` or `~/.config/opencode` — the user-level config dir. */
function openCodeConfigDir(): string {
  return process.env.OPENCODE_CONFIG_DIR || join(homedir(), '.config', 'opencode')
}

export const opencodeAdapter: IHarnessAdapter = {
  type: HarnessType.OPENCODE,
  configFileName: CONFIG_FILE,

  async detect(workspaceRoot: string): Promise<boolean> {
    // 1. Project-local `.opencode/` directory or `opencode.json{,c}`. Not
    //    AGENTS.md alone — Muse and Grok read the same file.
    for (const marker of ['.opencode', 'opencode.json', 'opencode.jsonc']) {
      try {
        await access(join(workspaceRoot, marker))
        return true
      } catch { /* not here */ }
    }

    // 2. User-level config dir — installed but never run in this workspace.
    try {
      await access(openCodeConfigDir())
      return true
    } catch { /* not here */ }

    // 3. `opencode` (or the 2.x line's `opencode2`) binary on PATH.
    const pathDirs = (process.env.PATH ?? '').split(process.platform === 'win32' ? ';' : ':')
    try {
      const { accessSync } = await import('node:fs')
      for (const dir of pathDirs) {
        for (const bin of ['opencode', 'opencode2']) {
          try { accessSync(join(dir, bin)); return true } catch { /* not here */ }
        }
      }
    } catch { /* ignore */ }
    return false
  },

  async writeConfig(workspaceRoot: string, sops: SyncSopEntry[], proxyUrl: string): Promise<string | null> {
    const agentsPath = join(workspaceRoot, CONFIG_FILE)

    // 1. AGENTS.md rules file — same "skip when there is nothing to write"
    //    convention every markdown adapter uses.
    if (sops.length > 0) {
      const content = buildMarkdownContent(sops, proxyUrl)
      await mkdir(dirname(agentsPath), { recursive: true })
      const tmp = agentsPath + '.intutic-tmp'
      await writeFile(tmp, content, 'utf-8')
      await rename(tmp, agentsPath)
    }

    // 2. The plugin gate. `intutic connect` has no workspace id in scope —
    //    same limitation `museAdapter` has — the sync daemon re-runs this
    //    with a real one on the next cycle.
    await writeOpenCodeHooks(workspaceRoot, proxyUrl, '')

    return agentsPath
  },

  async readCurrentHash(workspaceRoot: string): Promise<string | null> {
    try {
      return await hashFile(join(workspaceRoot, CONFIG_FILE))
    } catch {
      return null
    }
  },
}
