/**
 * vscodeSettingsWriter.ts — VS Code settings.json proxy injection.
 *
 * Shared by the Cline and Roo Code adapters. Merges Intutic proxy
 * API base URL keys into:
 *   - macOS: ~/Library/Application Support/Code/User/settings.json
 *   - Linux: ~/.config/Code/User/settings.json
 *   - Workspace: <workspaceRoot>/.vscode/settings.json
 *
 * Also writes ~/.intutic/.env.intutic with exported env vars for
 * shells that source it before launching VS Code.
 *
 * LLD #14 — Phase 3 cross-harness defence
 * HLD §3.14 — Three-Tier Defense Cascade
 *
 * @module
 */

import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import * as os from 'node:os'
import { createLogger } from '@intutic/logger'
import { newIso } from '@intutic/id'

const log = createLogger('sync-vscode-writer')

/** VS Code user settings path by platform. */
function getVscodeUserSettingsPath(): string {
  switch (process.platform) {
    case 'darwin':
      return path.join(os.homedir(), 'Library', 'Application Support', 'Code', 'User', 'settings.json')
    case 'win32':
      return path.join(process.env.APPDATA ?? os.homedir(), 'Code', 'User', 'settings.json')
    default: // linux
      return path.join(os.homedir(), '.config', 'Code', 'User', 'settings.json')
  }
}

/**
 * Settings keys injected for each harness.
 * These are checked during drift detection and restored on tamper.
 */
export const CLINE_PROXY_KEYS = ['cline.apiBase', 'cline.openAiBaseUrl'] as const
export const ROO_CODE_PROXY_KEYS = ['roo-cline.openAiBaseUrl', 'roo-cline.apiBase'] as const

/**
 * Merge Intutic proxy URL into VS Code user + workspace settings.json
 * for the Cline extension.
 */
export async function injectClineProxySettings(
  workspaceRoot: string,
  proxyUrl: string,
): Promise<void> {
  const keys: Record<string, string> = {}
  for (const k of CLINE_PROXY_KEYS) {
    keys[k] = proxyUrl
  }
  await mergeVscodeSettings(getVscodeUserSettingsPath(), keys)
  await mergeVscodeSettings(path.join(workspaceRoot, '.vscode', 'settings.json'), keys)
  await writeEnvSidecar(proxyUrl)
  log.info({ action: 'cline_proxy_injected', proxyUrl }, 'Cline proxy keys injected into VS Code settings')
}

/**
 * Merge Intutic proxy URL into VS Code user + workspace settings.json
 * for the Roo Code extension.
 */
export async function injectRooCodeProxySettings(
  workspaceRoot: string,
  proxyUrl: string,
): Promise<void> {
  const keys: Record<string, string> = {}
  for (const k of ROO_CODE_PROXY_KEYS) {
    keys[k] = proxyUrl
  }
  await mergeVscodeSettings(getVscodeUserSettingsPath(), keys)
  await mergeVscodeSettings(path.join(workspaceRoot, '.vscode', 'settings.json'), keys)
  await writeEnvSidecar(proxyUrl)
  log.info({ action: 'roo_code_proxy_injected', proxyUrl }, 'Roo Code proxy keys injected into VS Code settings')
}

/**
 * Write (or update) ~/.intutic/.env.intutic with proxy env vars.
 * Users/CI pipelines can `source ~/.intutic/.env.intutic` to get proxy routing
 * for any harness that respects OPENAI_BASE_URL / ANTHROPIC_BASE_URL.
 */
export async function writeEnvSidecar(proxyUrl: string): Promise<void> {
  const intuticDir = path.join(os.homedir(), '.intutic')
  await fs.mkdir(intuticDir, { recursive: true })
  const envPath = path.join(intuticDir, '.env.intutic')

  const content = [
    `# Intutic proxy env vars — auto-generated by intutic sync daemon`,
    `# Source this file in your shell rc: source ~/.intutic/.env.intutic`,
    `# Last sync: ${newIso()}`,
    '',
    `export ANTHROPIC_BASE_URL="${proxyUrl}"`,
    `export OPENAI_BASE_URL="${proxyUrl}"`,
    `export OPENAI_API_BASE="${proxyUrl}"`,
    `export CLINE_API_BASE="${proxyUrl}"`,
    `export AIDER_OPENAI_API_BASE="${proxyUrl}"`,
    `export GOOSE_OPENAI_HOST="${proxyUrl}"`,
    `export LLM_BASE_URL="${proxyUrl}"`,
    '',
  ].join('\n')

  const tmp = envPath + '.intutic-tmp'
  await fs.writeFile(tmp, content, 'utf-8')
  await fs.rename(tmp, envPath)
  log.info({ action: 'env_sidecar_written', path: envPath }, '.env.intutic sidecar written')
}

// ─── Internal ────────────────────────────────────────────────────────

async function mergeVscodeSettings(
  settingsPath: string,
  keys: Record<string, string>,
): Promise<void> {
  let existing: Record<string, unknown> = {}
  try {
    const raw = await fs.readFile(settingsPath, 'utf-8')
    // Strip JSON5-style comments before parsing
    const stripped = raw.replace(/\/\/[^\n]*/g, '').replace(/\/\*[\s\S]*?\*\//g, '')
    existing = JSON.parse(stripped)
  } catch {
    // No file or parse error — start fresh
  }

  const merged = { ...existing, ...keys }

  await fs.mkdir(path.dirname(settingsPath), { recursive: true })
  const tmp = settingsPath + '.intutic-tmp'
  await fs.writeFile(tmp, JSON.stringify(merged, null, 2) + '\n', 'utf-8')
  await fs.rename(tmp, settingsPath)
  log.debug({ action: 'vscode_settings_merged', path: settingsPath }, 'VS Code settings merged')
}
