#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
# pricing-repin.sh — the nightly pricing re-pin (.github/workflows/pricing-repin.yml).
#
# Pins LiteLLM's model price list to its last commit before 00:00 UTC today, so
# every repo that carries the generated files regenerates them from the same
# commit; reruns build-offline-pricing-bundle.ts; and, when a rate or a model
# changed, opens a pull request on branch pricing-repin-<date>, runs CI on it
# and merges it once CI passes — unless pricing-repin-review.mjs asks for a
# person, in which case the pull request waits for one.
#
# A pull request opened with the workflow's GITHUB_TOKEN starts no workflows of
# its own, so CI is started here with `gh workflow run ci.yml`, which that token
# may do. Its merge, by the same token, starts none either: nothing deploys
# from it; the next deploy picks the new prices up.
#
# Needs: gh with GH_TOKEN (contents, pull-requests and actions: write),
# GITHUB_REPOSITORY, and `pnpm install` already run.
# ──────────────────────────────────────────────────────────────────────────────
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"
REPO="${GITHUB_REPOSITORY:?set GITHUB_REPOSITORY}"
TMP="${RUNNER_TEMP:-$(mktemp -d)}"
day="$(date -u +%F)"
branch="pricing-repin-$day"
GEN=tools/scripts/build-offline-pricing-bundle.ts
OUT=(packages/proxy/src/pricing/offline_bundle.json packages/shared-types/src/modelCatalog.generated.ts)

if git ls-remote --exit-code --heads origin "$branch" >/dev/null 2>&1; then
  echo "Branch $branch exists: today's re-pin already ran."
  exit 0
fi

sha="$(gh api "repos/BerriAI/litellm/commits?sha=main&until=${day}T00:00:00Z&per_page=1" --jq '.[0].sha')"
[[ "$sha" =~ ^[0-9a-f]{40}$ ]] || { echo "::error::could not resolve LiteLLM's last commit before ${day}T00:00Z"; exit 1; }
current="$(sed -n "s/^const LITELLM_PRICES_SHA = '\([0-9a-f]*\)'.*/\1/p" "$GEN")"
[[ "$current" =~ ^[0-9a-f]{40}$ ]] || { echo "::error::no LITELLM_PRICES_SHA pin found in $GEN"; exit 1; }
# Only forward: a pin set by hand to a newer commit than tonight's cut-off stays.
status="$(gh api "repos/BerriAI/litellm/compare/$current...$sha" --jq .status)"
if [ "$status" != "ahead" ]; then
  echo "Pinned to ${current:0:8}; LiteLLM's commit before ${day}T00:00Z (${sha:0:8}) is not newer ($status)."
  exit 0
fi
sed -i.bak "s/^const LITELLM_PRICES_SHA = '[0-9a-f]*' \/\/ .*/const LITELLM_PRICES_SHA = '$sha' \/\/ $day/" "$GEN" && rm -f "$GEN.bak"
grep -q "^const LITELLM_PRICES_SHA = '$sha'" "$GEN" || { echo "::error::could not rewrite the pin in $GEN"; exit 1; }

pnpm --filter @intutic/cli exec tsx "$ROOT/$GEN"

set +e
node tools/scripts/pricing-repin-review.mjs > "$TMP/review.md"
review=$?
set -e
case $review in
  2)
    echo "LiteLLM $sha changed no rate or model we carry; nothing to do."
    git checkout -- "$GEN" "${OUT[@]}"
    exit 0 ;;
  0|3) ;;
  *) cat "$TMP/review.md"; exit 1 ;;
esac

git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
git checkout -q -b "$branch"
git add "$GEN" "${OUT[@]}"
{
  echo "Pricing bundle re-pinned to the current upstream ($day)"
  echo
  echo "LITELLM_PRICES_SHA ${sha:0:8}, LiteLLM's last commit before ${day}T00:00Z;"
  echo "offline_bundle.json and modelCatalog.generated.ts regenerated by the nightly"
  echo "pricing re-pin."
  echo
  cat "$TMP/review.md"
} > "$TMP/message.txt"
git commit -q -F "$TMP/message.txt"
git push -q origin "$branch"

{
  echo "Opened by the nightly pricing re-pin (\`.github/workflows/pricing-repin.yml\`): LiteLLM pinned to [\`${sha:0:8}\`](https://github.com/BerriAI/litellm/commit/$sha), its last commit before ${day}T00:00Z."
  echo
  cat "$TMP/review.md"
  echo
  if [ "$review" -eq 0 ]; then
    echo "It merges itself once CI passes."
  else
    echo "It waits for a person: check the rates above against the providers' price pages, then merge or close it."
  fi
} > "$TMP/body.md"
pr="$(gh pr create --repo "$REPO" --base main --head "$branch" --title "Pricing bundle re-pinned to the current upstream ($day)" --body-file "$TMP/body.md")"
echo "Opened $pr"
gh workflow run ci.yml --repo "$REPO" --ref "$branch"

[ "$review" -eq 0 ] || { echo "Left for a person: $pr"; exit 0; }

head="$(git rev-parse HEAD)"
run=""
for _ in $(seq 1 30); do
  run="$(gh run list --repo "$REPO" --workflow ci.yml --branch "$branch" --json databaseId,headSha \
    --jq "map(select(.headSha == \"$head\"))[0].databaseId // empty")"
  [ -n "$run" ] && break
  sleep 20
done
[ -n "$run" ] || { echo "::error::CI never started on $branch"; exit 1; }

if gh run watch "$run" --repo "$REPO" --exit-status --interval 60 > /dev/null; then
  gh pr merge "$pr" --repo "$REPO" --merge
  echo "Merged $pr"
else
  gh pr comment "$pr" --repo "$REPO" --body "CI failed on this re-pin, so it was not merged: $(gh run view "$run" --repo "$REPO" --json url --jq .url)"
  echo "::error::CI failed on $pr"
  exit 1
fi
