/**
 * antigravityCliHooks.ts — Google Antigravity governance hook injection.
 *
 * Antigravity (the 2.0 desktop app, the IDE and Antigravity CLI, which
 * replaced Gemini CLI for individual users in 2026) runs command hooks from
 * `<workspace>/.agents/hooks.json` and `~/.gemini/config/hooks.json`
 * (https://antigravity.google/docs/hooks/). This module:
 *
 * 1. Writes the gate script to `.intutic/hooks/antigravity-cli-check.js`.
 * 2. Merges an `intutic-governance` entry into `~/.gemini/config/hooks.json`,
 *    keeping every other hook in the file. A file that is not a plain JSON
 *    object is left alone and reported.
 *
 * # The hook contract, from the documentation
 *
 * The file's top-level keys are hook names; each maps event names to
 * handlers. `PreToolUse` takes `{matcher, hooks: [{type, command, timeout?}]}`
 * entries, where a matcher of `"*"` applies to every tool. The command gets
 * `{toolCall: {name, args}, conversationId, workspacePaths, ...}` on stdin,
 * camelCase, with Antigravity's own tool names (`run_command` with
 * `CommandLine`, `write_to_file` and `replace_file_content` with
 * `TargetFile`). It refuses a call by printing
 * `{"decision":"deny","reason":"..."}` on stdout — the same shape as Grok
 * Build's, so the gate uses the `stdout-decision-deny` contract.
 *
 * On an allowed call the gate prints `{}`: a JSON object, which every hook
 * must print, with no decision in it. `allow` would auto-approve the call
 * past the permission prompts the user configured, and `ask` would prompt
 * for every call the user lets run unprompted, so the gate states no
 * decision and Antigravity's own permission settings decide. The
 * documentation marks `decision` as required and does not say how a result
 * without one is read; that was not verified against a running Antigravity.
 *
 * HLD §3.14 — Three-Tier Defense Cascade (Tier 1 Native Gating)
 * @module
 */

import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import * as os from 'node:os'
import { createLogger } from '@intutic/logger'
import { keepOriginal } from '../disconnect/originals.js'
import { newIso } from '@intutic/id'
import { emitJsGate, emitJsFailClosedPrelude } from './gateBody.js'
import { readJsonObjectForMerge } from './jsonMergeTarget.js'

const log = createLogger('sync-antigravity-cli-hooks')

/** The key Intutic owns in Antigravity's hooks file. */
export const ANTIGRAVITY_HOOK_NAME = 'intutic-governance'

/** The gate script's file name in `.intutic/hooks/`. */
export const ANTIGRAVITY_CLI_GATE = 'antigravity-cli-check.js'

/** `~/.gemini/config/hooks.json`, resolved at call time so a moved HOME is honoured. */
export function antigravityHooksPath(): string {
  return path.join(os.homedir(), '.gemini', 'config', 'hooks.json')
}

/** The `intutic-governance` entry for Antigravity's hooks file. */
export function buildAntigravityHookEntry(hookScriptPath: string): Record<string, unknown> {
  return {
    enabled: true,
    PreToolUse: [
      {
        // Every tool: the gate decides from the arguments, so a tool name
        // nobody anticipated is still evaluated.
        matcher: '*',
        hooks: [{ type: 'command', command: `node ${JSON.stringify(hookScriptPath)}` }],
      },
    ],
  }
}

function buildHookScript(proxyUrl: string, workspaceRoot: string, workspaceId: string): string {
  const hookEventsLog = path.join(workspaceRoot, '.intutic', 'events', 'hook-events.jsonl')
  return `#!/usr/bin/env node
/**
 * Intutic Antigravity governance gate.
 * Auto-generated by intutic sync-daemon. DO NOT EDIT.
 * Proxy: ${proxyUrl}
 * Generated: ${newIso()}
 */
${emitJsFailClosedPrelude({ harness: 'antigravity', contract: 'stdout-decision-deny' })}
const fs = require('fs');
const crypto = require('crypto');
const https = require('https');

// Runtime credentials
const _runtimeEnvPath = require('path').join(require('os').homedir(), '.intutic', 'env', 'runtime.env');
let _intuticHost = 'https://api.intutic.ai', _intuticKey = '', _intuticWsId = ${JSON.stringify(workspaceId)};
try {
  fs.readFileSync(_runtimeEnvPath, 'utf-8').split('\\n').forEach(line => {
    const eq = line.indexOf('='); if (eq < 0) return;
    const k = line.slice(0, eq).trim(), v = line.slice(eq + 1).trim();
    if (k === 'INTUTIC_HOST' && v) _intuticHost = v;
    if (k === 'INTUTIC_API_KEY' && v) _intuticKey = v;
    if (k === 'INTUTIC_WORKSPACE_ID' && v) _intuticWsId = v;
  });
} catch {}

${emitJsGate({ harness: 'antigravity', contract: 'stdout-decision-deny' })}

let _intuticSessionId = '';
function logEvent(verdict, toolName, reason) {
  try {
    const ts = new Date().toISOString();
    const incidentId = crypto.createHash('sha1').update(ts + toolName + _intuticWsId).digest('hex').slice(0, 16);
    const entry = JSON.stringify({
      event: verdict,
      toolName, reason: reason || '',
      workspaceId: _intuticWsId,
      harnessType: 'antigravity',
      timestamp: ts,
      incidentId,
      ...(_intuticSessionId ? { sessionId: _intuticSessionId } : {}),
    }) + '\\n';
    fs.appendFileSync(${JSON.stringify(hookEventsLog)}, entry, { flag: 'a' });
    if (_intuticKey) {
      try {
        const body = JSON.stringify({ events: [JSON.parse(entry)] });
        const urlObj = new URL('/api/v1/hook-events', _intuticHost);
        const mod = urlObj.protocol === 'https:' ? https : require('http');
        const req = mod.request({ hostname: urlObj.hostname, port: urlObj.port || 443, path: urlObj.pathname, method: 'POST', headers: { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body), 'Authorization': 'Bearer ' + _intuticKey } });
        req.on('error', () => { /* fire-and-forget */ });
        req.write(body); req.end();
      } catch { /* never crash the hook */ }
    }
  } catch { /* never crash the hook */ }
}

let raw = '';
process.stdin.on('data', (c) => { raw += c; });
process.stdin.on('end', () => {
  try {
    const ctx = JSON.parse(raw);
    _intuticSessionId = ctx.conversationId || ctx.session_id || '';
    // Antigravity sends {toolCall: {name, args}}; the Claude-Code-shaped
    // fields are read too, so the shared gate test matrix drives this gate
    // with the payload it sends every other one.
    intuticGuardEnvelope(ctx, ['toolCall', 'tool_name', 'tool_input'], logEvent);
    const call = (ctx.toolCall && typeof ctx.toolCall === 'object') ? ctx.toolCall : {};
    const toolName = call.name || ctx.tool_name || 'tool';
    const input = call.args || ctx.tool_input || {};

    const targetPath = input.TargetFile || input.AbsolutePath || input.path || input.file_path ||
      input.filePath || input.target || '';
    const command = input.CommandLine || input.command || input.cmd || '';

    intuticGate(toolName, targetPath, command, logEvent, _intuticWsId, input);

    // Allow: a result with no decision in it. \`allow\` would auto-approve
    // the call past the user's own permission prompts.
    logEvent('tool_allowed', toolName, '');
    process.stdout.write('{}\\n');
    process.exit(0);
  } catch (err) {
    // Fail CLOSED — the stdout-decision-deny contract, even on a crash inside
    // this handler (the module-level prelude above covers crashes outside it).
    const errMsg = String(err);
    process.stderr.write('[Intutic Governance] Hook error (fail-closed): ' + errMsg + '\\n');
    logEvent('tool_blocked', 'unknown', errMsg);
    process.stdout.write(JSON.stringify({ decision: 'deny', reason: '[Intutic Governance] Hook error (fail-closed): ' + errMsg }) + '\\n');
    process.exit(0);
  }
});
`
}

/**
 * Write the Antigravity gate script and merge its registration into
 * `~/.gemini/config/hooks.json`.
 *
 * @param workspaceRoot - Absolute workspace root path.
 * @param proxyUrl      - Intutic proxy URL written into the script header.
 * @param workspaceId   - Workspace ID embedded in every hook event payload.
 */
export async function writeAntigravityCliHooks(
  workspaceRoot: string,
  proxyUrl: string,
  workspaceId = '',
): Promise<void> {
  const hookScriptDir = path.join(workspaceRoot, '.intutic', 'hooks')
  const hooksFile = antigravityHooksPath()

  await keepOriginal(hooksFile, workspaceRoot)
  await Promise.all([
    fs.mkdir(hookScriptDir, { recursive: true }),
    fs.mkdir(path.join(workspaceRoot, '.intutic', 'events'), { recursive: true }),
    fs.mkdir(path.dirname(hooksFile), { recursive: true }),
  ])

  const hookScriptPath = path.join(hookScriptDir, ANTIGRAVITY_CLI_GATE)
  const tmpScript = hookScriptPath + '.intutic-tmp'
  await fs.writeFile(tmpScript, buildHookScript(proxyUrl, workspaceRoot, workspaceId), 'utf-8')
  await fs.rename(tmpScript, hookScriptPath)
  await fs.chmod(hookScriptPath, 0o755)
  log.info({ action: 'antigravity_cli_hook_script_written', path: hookScriptPath }, 'Antigravity hook script written')

  const existing = await readJsonObjectForMerge(hooksFile)
  if (existing === null) return

  // Only Intutic's own key is replaced; every hook the user registered stays.
  const merged = { ...existing, [ANTIGRAVITY_HOOK_NAME]: buildAntigravityHookEntry(hookScriptPath) }
  const tmp = hooksFile + '.intutic-tmp'
  await fs.writeFile(tmp, JSON.stringify(merged, null, 2) + '\n', 'utf-8')
  await fs.rename(tmp, hooksFile)
  log.info({ action: 'antigravity_cli_hooks_written', path: hooksFile }, 'Merged Intutic PreToolUse hook into ~/.gemini/config/hooks.json')
}
