/**
 * antigravityHooks.ts — Gemini CLI (Antigravity) governance hook injection.
 *
 * Antigravity (Google DeepMind's Gemini CLI) supports a tool-level governance
 * hook via the `ANTIGRAVITY_PRE_TOOL_HOOK` environment variable and an optional
 * hook configuration file at `~/.gemini/settings.json`. This module:
 *
 * 1. Writes a pre-tool-check.sh script to `.intutic/hooks/antigravity-check.sh`
 *    (same pattern as Goose / OpenHands bash hooks).
 * 2. Merges the hook path into `~/.gemini/settings.json` under the
 *    `hooks.preTool` key.
 * 3. Optionally writes an `ANTIGRAVITY_PROXY_URL` env snippet to
 *    `.intutic/env/antigravity.env` for IDE/shell integration.
 *
 * Why bash and not Node.js?
 *   The Gemini CLI (antigravity) is a standalone binary; when it invokes
 *   a pre-tool hook it sets the current directory to the workspace root.
 *   A bash script is the most portable solution for the widest range of
 *   user configurations (no Node.js version dependency, no CJS/ESM split).
 *
 * Hook events:
 *   Every block/allow is appended to `.intutic/events/hook-events.jsonl`
 *   and drained to the control plane via FSEvents-driven drain.
 *
 * LLD #14 — Phase 3 cross-harness defence (Gap 3)
 * HLD §3.14 — Three-Tier Defense Cascade (Tier 1 Native Gating)
 * HLD §3.x  — Gemini CLI / Antigravity harness
 *
 * @module
 */

import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import * as os from 'node:os'
import { createLogger } from '@intutic/logger'
import { newIso } from '@intutic/id'
import { emitShellGate, SHELL_EXTRACT, SHELL_FAIL_CLOSED } from './gateBody.js'

const log = createLogger('sync-antigravity-hooks')

/** Default path to the Gemini CLI global settings file. */
const GEMINI_SETTINGS = path.join(os.homedir(), '.gemini', 'settings.json')

/** Governance-sensitive paths that the hook gate protects. */
// ─── Bash hook script template ────────────────────────────────────────────────

function buildAntigravityCheckScript(
  proxyUrl: string,
  workspaceRoot: string,
  workspaceId: string,
): string {
  const hookEventsLog = path.join(workspaceRoot, '.intutic', 'events', 'hook-events.jsonl')
  return `#!/usr/bin/env bash
# Intutic Antigravity (Gemini CLI) PreToolUse governance gate.
# Auto-generated by intutic sync-daemon. DO NOT EDIT.
# Proxy: ${proxyUrl}
# Generated: ${newIso()}
# Workspace: ${workspaceId}
set -euo pipefail
${SHELL_FAIL_CLOSED}
INPUT="$(cat)"
${SHELL_EXTRACT}

HOOK_EVENTS_LOG=${JSON.stringify(hookEventsLog)}

# ── Runtime credentials (sourced from ~/.intutic/env/runtime.env) ────────────────────────
# These are defaults, and they are also the only thing standing between
# \`set -u\` and a fatal unbound-variable error: log_event reads all three, so on
# a machine with no runtime.env to source, an unset name kills the gate before
# it can exit 2. Spelling matters — INTUTIC_, never INTUITIC_.
RUNTIME_ENV="$HOME/.intutic/env/runtime.env"
INTUTIC_HOST="https://api.intutic.ai"
INTUTIC_API_KEY=""
INTUTIC_WORKSPACE_ID=${JSON.stringify(workspaceId)}
[ -f "$RUNTIME_ENV" ] && source "$RUNTIME_ENV" 2>/dev/null || true

log_event() {
  local verdict="\$1" tool="\$2" reason="\$3"
  # \`tool\` and \`reason\` carry agent-controlled text — the tool name, and the
  # target path quoted into the block reason — and both are spliced into the
  # JSON string below. Escape first: one unescaped quote yields a line
  # JSON.parse rejects, and drainHookEvents drops malformed lines then wipes the
  # log on a successful drain, so the record of a block is destroyed rather than
  # delayed. A crafted path could otherwise close the string and forge fields.
  tool="\${tool//\\\\/\\\\\\\\}";     tool="\${tool//\\"/\\\\\\"}"
  reason="\${reason//\\\\/\\\\\\\\}"; reason="\${reason//\\"/\\\\\\"}"
  # Every C0 control character, not just newline and carriage return. JSON
  # forbids all of U+0000-U+001F unescaped, so a plain TAB in a filename — no
  # adversary required — was still enough to produce a line JSON.parse rejects.
  # (NUL cannot appear in a bash variable, so the range starts at \\x01.)
  tool="\${tool//[\$'\\x01'-\$'\\x1f']/ }"; reason="\${reason//[\$'\\x01'-\$'\\x1f']/ }"
  # The workspace id is spliced into the same JSON string. It comes from
  # runtime.env on disk rather than from the agent, so it is lower risk — but a
  # value with a quote in it breaks every audit line the same way, and "lower
  # risk" is not "cannot happen" for a file the operator edits by hand.
  local ws="\${INTUTIC_WORKSPACE_ID}"
  ws="\${ws//\\\\/\\\\\\\\}"; ws="\${ws//\\"/\\\\\\"}"; ws="\${ws//[\$'\\x01'-\$'\\x1f']/ }"
  local ts; ts="\$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  local incident_id; incident_id="\$(printf '%s' "\${ts}\${tool}\${INTUTIC_WORKSPACE_ID}" | sha1sum 2>/dev/null | cut -c1-16 || echo \"\$(date +%s)\")"
  local entry="{\\"event\\":\\"\${verdict}\\",\\"toolName\\":\\"\${tool}\\",\\"reason\\":\\"\${reason}\\",\\"workspaceId\\":\\"\${ws}\\",\\"harnessType\\":\\"antigravity\\",\\"timestamp\\":\\"\${ts}\\",\\"incidentId\\":\\"\${incident_id}\\"}"
  printf '%s\\n' "\$entry" >> "\$HOOK_EVENTS_LOG" 2>/dev/null || true
  if [ -n "\$INTUTIC_API_KEY" ]; then
    curl -s -o /dev/null --max-time 3 -X POST \\
      -H "Content-Type: application/json" \\
      -H "Authorization: Bearer \$INTUTIC_API_KEY" \\
      -d "{\\"events\\":[\$entry]}" \\
      "\${INTUTIC_HOST}/api/v1/hook-events" & disown 2>/dev/null || true
  fi
}

${emitShellGate({ harness: "antigravity" })}
log_event "tool_allowed" "$TOOL_NAME" ""
exit 0
`
}

// ─── Main export ──────────────────────────────────────────────────────────────

/**
 * Write the Antigravity (Gemini CLI) governance hook script and merge
 * hook configuration into `~/.gemini/settings.json`.
 *
 * Safe to call repeatedly — uses atomic rename (`.intutic-tmp` → final path)
 * so partial writes never leave a corrupt script in place.
 *
 * @param workspaceRoot - Absolute workspace root path.
 * @param proxyUrl      - Intutic proxy URL written into the hook script header.
 * @param workspaceId   - Workspace ID embedded in every hook event payload.
 */
export async function writeAntigravityHooks(
  workspaceRoot: string,
  proxyUrl: string,
  workspaceId = '',
): Promise<void> {
  // ── 1. Ensure directories ──────────────────────────────────────────────────

  const hookScriptDir = path.join(workspaceRoot, '.intutic', 'hooks')
  const hookEventsDir = path.join(workspaceRoot, '.intutic', 'events')
  const envDir = path.join(workspaceRoot, '.intutic', 'env')

  await Promise.all([
    fs.mkdir(hookScriptDir, { recursive: true }),
    fs.mkdir(hookEventsDir, { recursive: true }),
    fs.mkdir(envDir, { recursive: true }),
    fs.mkdir(path.join(os.homedir(), '.gemini'), { recursive: true }),
  ])

  // ── 2. Write hook script ───────────────────────────────────────────────────

  const hookScriptPath = path.join(hookScriptDir, 'antigravity-check.sh')
  const tmpScript = hookScriptPath + '.intutic-tmp'
  await fs.writeFile(tmpScript, buildAntigravityCheckScript(proxyUrl, workspaceRoot, workspaceId), 'utf-8')
  await fs.rename(tmpScript, hookScriptPath)
  await fs.chmod(hookScriptPath, 0o755)

  log.info({ action: 'antigravity_hook_script_written', path: hookScriptPath }, 'Antigravity hook script written')

  // ── 3. Merge into ~/.gemini/settings.json ─────────────────────────────────

  let existingSettings: Record<string, unknown> = {}
  try {
    const raw = await fs.readFile(GEMINI_SETTINGS, 'utf-8')
    existingSettings = JSON.parse(raw)
  } catch {
    // File doesn't exist yet — start fresh
  }

  const mergedSettings = {
    ...existingSettings,
    hooks: {
      ...(existingSettings.hooks as Record<string, unknown>),
      // Register the pre-tool hook command
      preTool: hookScriptPath,
    },
  }

  const tmpSettings = GEMINI_SETTINGS + '.intutic-tmp'
  await fs.writeFile(tmpSettings, JSON.stringify(mergedSettings, null, 2) + '\n', 'utf-8')
  await fs.rename(tmpSettings, GEMINI_SETTINGS)

  log.info(
    { action: 'antigravity_settings_written', path: GEMINI_SETTINGS },
    'Merged Intutic hook into ~/.gemini/settings.json',
  )

  // ── 4. Write env snippet (optional — for shell profiles / IDE env) ─────────

  const envSnippet = [
    `# Intutic Antigravity governance hook — auto-generated ${newIso()}`,
    `# Source this file in ~/.bashrc or ~/.zshrc to apply governance to Gemini CLI.`,
    `export ANTIGRAVITY_PRE_TOOL_HOOK=${JSON.stringify(hookScriptPath)}`,
    proxyUrl ? `export ANTIGRAVITY_PROXY_URL=${JSON.stringify(proxyUrl)}` : '',
  ].filter(Boolean).join('\n') + '\n'

  const envFilePath = path.join(envDir, 'antigravity.env')
  const tmpEnv = envFilePath + '.intutic-tmp'
  await fs.writeFile(tmpEnv, envSnippet, 'utf-8')
  await fs.rename(tmpEnv, envFilePath)

  log.info(
    { action: 'antigravity_env_written', path: envFilePath },
    'Antigravity env snippet written',
  )
}
