/**
 * antigravityHooks.ts — Gemini CLI (Antigravity) governance hook injection.
 *
 * Gemini CLI runs command hooks registered under `hooks.BeforeTool` in
 * `~/.gemini/settings.json`. Each entry carries a `matcher` regex over tool
 * names and a list of `{type: "command", command}` hooks; the command receives
 * `{tool_name, tool_input, ...}` on stdin and blocks the call with exit code 2
 * (stderr is the reason). This module:
 *
 * 1. Writes the gate script to `.intutic/hooks/antigravity-check.sh`
 *    (same pattern as Goose / OpenHands bash hooks).
 * 2. Merges a catch-all `BeforeTool` entry for it into
 *    `~/.gemini/settings.json`, keeping every other setting and hook. A
 *    settings file that is not a plain JSON object is left alone.
 *
 * Earlier versions registered the script under `hooks.preTool` and wrote an
 * `ANTIGRAVITY_PRE_TOOL_HOOK` env snippet. Neither is a Gemini CLI setting, so
 * that gate never ran; the stale `preTool` key is removed on the next write.
 *
 * Why bash and not Node.js?
 *   The Gemini CLI (antigravity) is a standalone binary; when it invokes
 *   a pre-tool hook it sets the current directory to the workspace root.
 *   A bash script is the most portable solution for the widest range of
 *   user configurations (no Node.js version dependency, no CJS/ESM split).
 *
 * Hook events:
 *   Every block/allow is appended to `.intutic/events/hook-events.jsonl`
 *   and drained to the control plane via FSEvents-driven drain.
 *
 * LLD #14 — Phase 3 cross-harness defence (Gap 3)
 * HLD §3.14 — Three-Tier Defense Cascade (Tier 1 Native Gating)
 * HLD §3.x  — Gemini CLI / Antigravity harness
 *
 * @module
 */

import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import * as os from 'node:os'
import { createLogger } from '@intutic/logger'
import { keepOriginal } from '../disconnect/originals.js'
import { newIso } from '@intutic/id'
import { emitShellGate, HOOK_TIMEOUT_SECONDS, SHELL_EXTRACT, SHELL_FAIL_CLOSED } from './gateBody.js'
import { readJsonObjectForMerge } from './jsonMergeTarget.js'

const log = createLogger('sync-antigravity-hooks')


/** Governance-sensitive paths that the hook gate protects. */
// ─── Bash hook script template ────────────────────────────────────────────────

function buildAntigravityCheckScript(
  proxyUrl: string,
  workspaceRoot: string,
  workspaceId: string,
): string {
  const hookEventsLog = path.join(workspaceRoot, '.intutic', 'events', 'hook-events.jsonl')
  return `#!/usr/bin/env bash
# Intutic Antigravity (Gemini CLI) PreToolUse governance gate.
# Auto-generated by intutic sync-daemon. DO NOT EDIT.
# Proxy: ${proxyUrl}
# Generated: ${newIso()}
# Workspace: ${workspaceId}
set -euo pipefail
${SHELL_FAIL_CLOSED}
INPUT="$(cat)"
${SHELL_EXTRACT}

HOOK_EVENTS_LOG=${JSON.stringify(hookEventsLog)}

# ── Runtime credentials (sourced from ~/.intutic/env/runtime.env) ────────────────────────
# These are defaults, and they are also the only thing standing between
# \`set -u\` and a fatal unbound-variable error: log_event reads all three, so on
# a machine with no runtime.env to source, an unset name kills the gate before
# it can exit 2. Spelling matters — INTUTIC_, never INTUITIC_.
RUNTIME_ENV="$HOME/.intutic/env/runtime.env"
INTUTIC_HOST="https://api.intutic.ai"
INTUTIC_API_KEY=""
INTUTIC_WORKSPACE_ID=${JSON.stringify(workspaceId)}
[ -f "$RUNTIME_ENV" ] && source "$RUNTIME_ENV" 2>/dev/null || true

log_event() {
  local verdict="\$1" tool="\$2" reason="\$3"
  # \`tool\` and \`reason\` carry agent-controlled text — the tool name, and the
  # target path quoted into the block reason — and both are spliced into the
  # JSON string below. Escape first: one unescaped quote yields a line
  # JSON.parse rejects, and drainHookEvents drops malformed lines then wipes the
  # log on a successful drain, so the record of a block is destroyed rather than
  # delayed. A crafted path could otherwise close the string and forge fields.
  tool="\${tool//\\\\/\\\\\\\\}";     tool="\${tool//\\"/\\\\\\"}"
  reason="\${reason//\\\\/\\\\\\\\}"; reason="\${reason//\\"/\\\\\\"}"
  # Every C0 control character, not just newline and carriage return. JSON
  # forbids all of U+0000-U+001F unescaped, so a plain TAB in a filename — no
  # adversary required — was still enough to produce a line JSON.parse rejects.
  # (NUL cannot appear in a bash variable, so the range starts at \\x01.)
  tool="\${tool//[\$'\\x01'-\$'\\x1f']/ }"; reason="\${reason//[\$'\\x01'-\$'\\x1f']/ }"
  # The workspace id is spliced into the same JSON string. It comes from
  # runtime.env on disk rather than from the agent, so it is lower risk — but a
  # value with a quote in it breaks every audit line the same way, and "lower
  # risk" is not "cannot happen" for a file the operator edits by hand.
  local ws="\${INTUTIC_WORKSPACE_ID}"
  ws="\${ws//\\\\/\\\\\\\\}"; ws="\${ws//\\"/\\\\\\"}"; ws="\${ws//[\$'\\x01'-\$'\\x1f']/ }"
  local ts; ts="\$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  local incident_id; incident_id="\$(printf '%s' "\${ts}\${tool}\${INTUTIC_WORKSPACE_ID}" | sha1sum 2>/dev/null | cut -c1-16 || echo \"\$(date +%s)\")"
  # The event's id: random, made once here, and resent with the line it is
  # written into, so the control plane processes the event once.
  local event_id; event_id="\$(od -An -N16 -tx1 /dev/urandom 2>/dev/null | tr -d ' \\n' || true)"
  [ -n "\$event_id" ] || event_id="\$(date +%s)\$\$\${RANDOM}\${RANDOM}\${RANDOM}"
  local entry="{\\"event\\":\\"\${verdict}\\",\\"toolName\\":\\"\${tool}\\",\\"reason\\":\\"\${reason}\\",\\"workspaceId\\":\\"\${ws}\\",\\"harnessType\\":\\"antigravity\\",\\"timestamp\\":\\"\${ts}\\",\\"incidentId\\":\\"\${incident_id}\\",\\"eventId\\":\\"\${event_id}\\"}"
  printf '%s\\n' "\$entry" >> "\$HOOK_EVENTS_LOG" 2>/dev/null || true
  if [ -n "\$INTUTIC_API_KEY" ]; then
    curl -s -o /dev/null --max-time 3 -X POST \\
      -H "Content-Type: application/json" \\
      -H "Authorization: Bearer \$INTUTIC_API_KEY" \\
      -d "{\\"events\\":[\$entry]}" \\
      "\${INTUTIC_HOST}/api/v1/hook-events" & disown 2>/dev/null || true
  fi
}

${emitShellGate({ harness: "antigravity" })}
log_event "tool_allowed" "$TOOL_NAME" ""
exit 0
`
}

/**
 * The `BeforeTool` entry that registers the gate: a catch-all matcher, since
 * the gate decides from the arguments and a tool name nobody anticipated is
 * still evaluated. Shared with the MDM manifest, so the two cannot drift.
 * Gemini CLI's \`timeout\` is in milliseconds (default 60 000), and it runs a
 * call whose hook times out; the gate refuses at its own deadline inside it.
 */
export function buildGeminiBeforeToolEntry(hookScriptPath: string): Record<string, unknown> {
  return {
    matcher: '.*',
    hooks: [{
      name: 'intutic-governance',
      type: 'command',
      command: geminiGateCommand(hookScriptPath),
      timeout: HOOK_TIMEOUT_SECONDS * 1000,
    }],
  }
}

function geminiGateCommand(hookScriptPath: string): string {
  return `bash ${JSON.stringify(hookScriptPath)}`
}

// ─── Main export ──────────────────────────────────────────────────────────────

/**
 * Write the Antigravity (Gemini CLI) governance hook script and merge
 * hook configuration into `~/.gemini/settings.json`.
 *
 * Safe to call repeatedly — uses atomic rename (`.intutic-tmp` → final path)
 * so partial writes never leave a corrupt script in place.
 *
 * @param workspaceRoot - Absolute workspace root path.
 * @param proxyUrl      - Intutic proxy URL written into the hook script header.
 * @param workspaceId   - Workspace ID embedded in every hook event payload.
 */
export async function writeAntigravityHooks(
  workspaceRoot: string,
  proxyUrl: string,
  workspaceId = '',
): Promise<void> {
  // ── 1. Ensure directories ──────────────────────────────────────────────────

  const hookScriptDir = path.join(workspaceRoot, '.intutic', 'hooks')
  const hookEventsDir = path.join(workspaceRoot, '.intutic', 'events')
  // homedir() read at call time so tests that move HOME are honoured.
  const geminiSettings = path.join(os.homedir(), '.gemini', 'settings.json')

  await keepOriginal(geminiSettings, workspaceRoot)
  await Promise.all([
    fs.mkdir(hookScriptDir, { recursive: true }),
    fs.mkdir(hookEventsDir, { recursive: true }),
    fs.mkdir(path.dirname(geminiSettings), { recursive: true }),
  ])

  // ── 2. Write hook script ───────────────────────────────────────────────────

  const hookScriptPath = path.join(hookScriptDir, 'antigravity-check.sh')
  const tmpScript = hookScriptPath + '.intutic-tmp'
  await fs.writeFile(tmpScript, buildAntigravityCheckScript(proxyUrl, workspaceRoot, workspaceId), 'utf-8')
  await fs.rename(tmpScript, hookScriptPath)
  await fs.chmod(hookScriptPath, 0o755)

  log.info({ action: 'antigravity_hook_script_written', path: hookScriptPath }, 'Antigravity hook script written')

  // ── 3. Merge into ~/.gemini/settings.json ─────────────────────────────────

  const existingSettings = await readJsonObjectForMerge(geminiSettings)
  if (existingSettings === null) return

  const existingHooks = (typeof existingSettings.hooks === 'object' && existingSettings.hooks !== null
    ? existingSettings.hooks
    : {}) as Record<string, unknown>
  // `preTool` is where earlier versions registered the gate; it is not a
  // Gemini CLI hook event, so it is dropped rather than carried forward.
  const keptHooks: Record<string, unknown> = { ...existingHooks }
  delete keptHooks.preTool
  const existingBeforeTool = Array.isArray(keptHooks.BeforeTool) ? (keptHooks.BeforeTool as unknown[]) : []

  // De-duplicated by command, so repeated syncs replace this entry rather than
  // stacking copies, and every hook the user registered is kept.
  const intuticCmd = geminiGateCommand(hookScriptPath)
  const filtered = existingBeforeTool.filter((entry: unknown) => {
    if (typeof entry !== 'object' || entry === null) return true
    const inner = ((entry as Record<string, unknown>).hooks as unknown[]) ?? []
    return !(
      inner.length > 0 &&
      inner.every((h: unknown) => typeof h === 'object' && h !== null && (h as Record<string, unknown>).command === intuticCmd)
    )
  })

  const mergedSettings = {
    ...existingSettings,
    hooks: {
      ...keptHooks,
      BeforeTool: [...filtered, buildGeminiBeforeToolEntry(hookScriptPath)],
    },
  }

  const tmpSettings = geminiSettings + '.intutic-tmp'
  await fs.writeFile(tmpSettings, JSON.stringify(mergedSettings, null, 2) + '\n', 'utf-8')
  await fs.rename(tmpSettings, geminiSettings)

  log.info(
    { action: 'antigravity_settings_written', path: geminiSettings },
    'Merged Intutic BeforeTool hook into ~/.gemini/settings.json',
  )
}
