/**
 * claudeDesktopHooks.ts — Claude Desktop PreToolUse hook generator.
 *
 * Claude Desktop shares the same hook format as Claude Code (PreToolUse,
 * exit 2 on stdin JSON) but reads its config from an OS-specific location:
 *   macOS : ~/Library/Application Support/Claude/claude_desktop_config.json
 *   Linux : ~/.config/Claude/claude_desktop_config.json
 *
 * Hook events are written via dual-path logEvent:
 *   Path B (reliable)  — synchronous append to .intutic/events/claude-desktop-hook-events.jsonl
 *   Path A (telemetry) — fire-and-forget https.request to the control plane
 *
 * LLD #14 — Phase 3 cross-harness defence (Gap 3, WS-B)
 * HLD §3.14 — Three-Tier Defense Cascade (Tier 1 Native Gating)
 *
 * @module
 */

import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import * as os from 'node:os'
import { createLogger } from '@intutic/logger'
import { newIso } from '@intutic/id'

const log = createLogger('sync-claude-desktop-hooks')

/** Governance-sensitive paths that the hook gate protects (mirrors claudeCodeHooks). */
const PROTECTED_PATHS = [
  path.join(os.homedir(), '.claude', 'settings.json'),
  path.join(os.homedir(), '.claude', 'settings.local.json'),
  '.claude/settings.json',
  '.claude/settings.local.json',
  '.intutic/hooks',
  '.intutic/integrity.json',
  '.intutic/context_integrity.json',
]

/** Resolve the OS-specific claude_desktop_config.json path. */
function resolveClaudeDesktopConfigPath(): string {
  switch (process.platform) {
    case 'darwin':
      return path.join(os.homedir(), 'Library', 'Application Support', 'Claude', 'claude_desktop_config.json')
    case 'linux':
      return path.join(os.homedir(), '.config', 'Claude', 'claude_desktop_config.json')
    default:
      // Fallback to macOS path — Windows is out of scope for now
      return path.join(os.homedir(), 'Library', 'Application Support', 'Claude', 'claude_desktop_config.json')
  }
}

// ─── Node.js hook script template ─────────────────────────────────────────────

function buildClaudeDesktopCheckScript(
  proxyUrl: string,
  workspaceRoot: string,
  workspaceId: string,
): string {
  const hookEventsLog = path.join(workspaceRoot, '.intutic', 'events', 'claude-desktop-hook-events.jsonl')
  const runtimeEnvPath = path.join(os.homedir(), '.intutic', 'env', 'runtime.env')

  return `/**
 * Intutic Claude Desktop PreToolUse execution gate.
 * Auto-generated by intutic sync-daemon. DO NOT EDIT.
 *
 * Dual-path logEvent:
 *   Path B — synchronous file append to hook-events.jsonl
 *   Path A — fire-and-forget https.request to the control plane
 *
 * Proxy: ${proxyUrl}
 * Generated: ${newIso()}
 * Workspace: ${workspaceId}
 */
'use strict';
const path = require('path');
const os = require('os');
const fs = require('fs');
const https = require('https');
const crypto = require('crypto');
const url = require('url');

// ── Runtime env loader (Path A credentials) ──────────────────────────────────
const RUNTIME_ENV_PATH = ${JSON.stringify(runtimeEnvPath)};

function loadRuntimeEnv() {
  const env = {
    INTUTIC_HOST: 'https://api.intutic.ai',
    INTUTIC_API_KEY: '',
    INTUTIC_WORKSPACE_ID: ${JSON.stringify(workspaceId)},
  };
  try {
    const raw = fs.readFileSync(RUNTIME_ENV_PATH, 'utf-8');
    for (const line of raw.split('\\n')) {
      const stripped = line.trim();
      if (!stripped || stripped.startsWith('#') || !stripped.includes('=')) continue;
      const eq = stripped.indexOf('=');
      const k = stripped.slice(0, eq).trim();
      const v = stripped.slice(eq + 1).trim();
      env[k] = v;
    }
  } catch { /* file may not exist yet */ }
  return env;
}

// ── Governance-sensitive paths ────────────────────────────────────────────────
const PROTECTED_PATHS = ${JSON.stringify(PROTECTED_PATHS)};

// ── Dual-path logEvent ────────────────────────────────────────────────────────
const HOOK_EVENTS_LOG = ${JSON.stringify(hookEventsLog)};

function logEvent(env, verdict, toolName, reason) {
  const ts = new Date().toISOString();
  const incidentId = crypto.createHash('sha1')
    .update(ts + toolName + env.INTUTIC_WORKSPACE_ID)
    .digest('hex').slice(0, 16);

  const entry = {
    event: verdict === 'blocked' ? 'tool_blocked' : 'tool_allowed',
    toolName,
    reason: reason || '',
    workspaceId: env.INTUTIC_WORKSPACE_ID,
    harnessType: 'claude-desktop',
    timestamp: ts,
    incidentId,
  };

  // Path B — reliable file append
  try {
    const dir = path.dirname(HOOK_EVENTS_LOG);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.appendFileSync(HOOK_EVENTS_LOG, JSON.stringify(entry) + '\\n', { flag: 'a' });
  } catch { /* never crash the hook */ }

  // Path A — fire-and-forget https.request
  if (env.INTUTIC_API_KEY) {
    try {
      const body = Buffer.from(JSON.stringify({ events: [entry] }));
      const parsedUrl = url.parse(env.INTUTIC_HOST + '/api/v1/hook-events');
      const req = https.request({
        hostname: parsedUrl.hostname,
        port: parsedUrl.port || 443,
        path: parsedUrl.path,
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Content-Length': body.length,
          'Authorization': 'Bearer ' + env.INTUTIC_API_KEY,
        },
      });
      req.on('error', () => {}); // fire-and-forget
      req.write(body);
      req.end();
    } catch { /* never crash the hook */ }
  }
}

// ── Main ──────────────────────────────────────────────────────────────────────
const runtimeEnv = loadRuntimeEnv();
let inputData = '';
process.stdin.on('data', (chunk) => { inputData += chunk; });
process.stdin.on('end', () => {
  try {
    const ctx = JSON.parse(inputData);
    const toolName = (ctx.tool_name || ctx.toolName || '').toLowerCase();
    const toolInput = ctx.tool_input || ctx.toolInput || {};
    const toolInputStr = JSON.stringify(toolInput);

    // 1. Protected-path guard
    if (['edit', 'write', 'multiedit'].includes(toolName)) {
      const targetPath = toolInput.path || toolInput.file_path ||
        toolInput.new_path || toolInput.target || '';
      for (const p of PROTECTED_PATHS) {
        if (targetPath.includes(p) || String(targetPath).startsWith(p)) {
          const reason = 'Attempt to modify governance-protected path: "' + targetPath + '". ' +
            'To change governance policy, update your SOP via the Intutic control plane.';
          console.error('[Intutic Guardrail] BLOCKED: ' + reason);
          logEvent(runtimeEnv, 'blocked', toolName, reason);
          process.exit(2);
        }
      }
    }

    // 2. Bash/shell command bypass guard
    if (toolName === 'bash') {
      const cmd = toolInput.command || toolInput.cmd || '';
      const BYPASS_PATTERNS = [
        'chflags nouchg',
        'chattr -i',
        'rm -rf .intutic',
        'CLAUDE_DESKTOP_HOOKS=',
      ];
      for (const pattern of BYPASS_PATTERNS) {
        if (cmd.includes(pattern)) {
          const reason = 'Shell command matches governance bypass pattern: "' + pattern + '"';
          console.error('[Intutic Guardrail] BLOCKED: ' + reason);
          logEvent(runtimeEnv, 'blocked', toolName, reason);
          process.exit(2);
        }
      }
    }

    logEvent(runtimeEnv, 'allowed', toolName, '');
    process.exit(0);
  } catch (err) {
    console.error('[Intutic Guardrail] Hook error (blocking for safety):', err);
    logEvent(runtimeEnv, 'blocked', 'unknown', String(err));
    process.exit(2);
  }
});
`.trim()
}

// ─── Main export ──────────────────────────────────────────────────────────────

/**
 * Write the Claude Desktop governance hook script and merge hook configuration
 * into the OS-specific claude_desktop_config.json.
 *
 * Safe to call repeatedly — uses atomic rename (`.intutic-tmp` → final path).
 * Does NOT touch the `mcpServers` section of the config.
 *
 * @param workspaceRoot - Absolute workspace root path.
 * @param proxyUrl      - Intutic proxy URL written into the hook script header.
 * @param workspaceId   - Workspace ID embedded in every hook event payload.
 */
export async function writeClaudeDesktopHooks(
  workspaceRoot: string,
  proxyUrl: string,
  workspaceId = '',
): Promise<void> {
  // ── 1. Ensure directories ──────────────────────────────────────────────────

  const hookScriptDir = path.join(workspaceRoot, '.intutic', 'hooks')
  const hookEventsDir = path.join(workspaceRoot, '.intutic', 'events')
  const desktopConfigPath = resolveClaudeDesktopConfigPath()
  const desktopConfigDir = path.dirname(desktopConfigPath)

  await Promise.all([
    fs.mkdir(hookScriptDir, { recursive: true }),
    fs.mkdir(hookEventsDir, { recursive: true }),
    fs.mkdir(desktopConfigDir, { recursive: true }),
  ])

  // ── 2. Write hook script (atomic) ─────────────────────────────────────────

  const hookScriptPath = path.join(hookScriptDir, 'claude-desktop-check.js')
  const tmpScript = hookScriptPath + '.intutic-tmp'
  await fs.writeFile(tmpScript, buildClaudeDesktopCheckScript(proxyUrl, workspaceRoot, workspaceId), 'utf-8')
  await fs.rename(tmpScript, hookScriptPath)

  log.info({ action: 'claude_desktop_hook_script_written', path: hookScriptPath }, 'Claude Desktop hook script written')

  // ── 3. Merge into claude_desktop_config.json (safe merge, preserve mcpServers) ──

  let existingConfig: Record<string, unknown> = {}
  try {
    const raw = await fs.readFile(desktopConfigPath, 'utf-8')
    existingConfig = JSON.parse(raw)
  } catch {
    // File doesn't exist yet — start fresh
  }

  const existingHooks = (existingConfig.hooks as Record<string, unknown>) ?? {}
  const existingPreToolUse = (existingHooks.PreToolUse as unknown[]) ?? []

  // De-duplicate: remove any existing Intutic entry for Bash then re-add
  const HOOK_MATCHERS = ['Bash', 'Edit', 'Write', 'MultiEdit']
  const intuticCmd = `node ${hookScriptPath}`
  const filteredPTU = existingPreToolUse.filter((entry: unknown) => {
    if (typeof entry !== 'object' || entry === null) return true
    const e = entry as Record<string, unknown>
    // Remove entries where all inner hooks use the intutic command
    const innerHooks = (e.hooks as unknown[]) ?? []
    return !innerHooks.every(
      (h: unknown) => typeof h === 'object' && h !== null && (h as Record<string, unknown>).command === intuticCmd,
    )
  })

  const newPreToolUseEntries = HOOK_MATCHERS.map((matcher) => ({
    matcher,
    hooks: [{ type: 'command', command: intuticCmd }],
  }))

  const mergedConfig = {
    ...existingConfig,
    hooks: {
      ...existingHooks,
      PreToolUse: [...filteredPTU, ...newPreToolUseEntries],
    },
  }

  const tmpConfig = desktopConfigPath + '.intutic-tmp'
  await fs.writeFile(tmpConfig, JSON.stringify(mergedConfig, null, 2) + '\n', 'utf-8')
  await fs.rename(tmpConfig, desktopConfigPath)

  log.info(
    { action: 'claude_desktop_config_written', path: desktopConfigPath },
    'Merged Intutic hooks into claude_desktop_config.json',
  )
}
