/**
 * claudeDesktopHooks.ts — Claude Desktop PreToolUse hook generator.
 *
 * Claude Desktop shares the same hook format as Claude Code (PreToolUse,
 * exit 2 on stdin JSON) but reads its config from an OS-specific location:
 *   macOS : ~/Library/Application Support/Claude/claude_desktop_config.json
 *   Linux : ~/.config/Claude/claude_desktop_config.json
 *
 * Hook events are written via dual-path logEvent:
 *   Path B (reliable)  — synchronous append to .intutic/events/claude-desktop-hook-events.jsonl
 *   Path A (telemetry) — fire-and-forget https.request to the control plane
 *
 * LLD #14 — Phase 3 cross-harness defence (Gap 3, WS-B)
 * HLD §3.14 — Three-Tier Defense Cascade (Tier 1 Native Gating)
 *
 * @module
 */

import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import * as os from 'node:os'
import { createLogger } from '@intutic/logger'
import { newIso } from '@intutic/id'
import { emitJsGate, emitJsFailClosedPrelude } from './gateBody.js'

const log = createLogger('sync-claude-desktop-hooks')

/** Governance-sensitive paths that the hook gate protects (mirrors claudeCodeHooks). */

/** Resolve the OS-specific claude_desktop_config.json path. */
function resolveClaudeDesktopConfigPath(): string {
  switch (process.platform) {
    case 'darwin':
      return path.join(os.homedir(), 'Library', 'Application Support', 'Claude', 'claude_desktop_config.json')
    case 'linux':
      return path.join(os.homedir(), '.config', 'Claude', 'claude_desktop_config.json')
    default:
      // Fallback to macOS path — Windows is out of scope for now
      return path.join(os.homedir(), 'Library', 'Application Support', 'Claude', 'claude_desktop_config.json')
  }
}

// ─── Node.js hook script template ─────────────────────────────────────────────

function buildClaudeDesktopCheckScript(
  proxyUrl: string,
  workspaceRoot: string,
  workspaceId: string,
): string {
  const hookEventsLog = path.join(workspaceRoot, '.intutic', 'events', 'claude-desktop-hook-events.jsonl')
  const runtimeEnvPath = path.join(os.homedir(), '.intutic', 'env', 'runtime.env')

  return `/**
 * Intutic Claude Desktop PreToolUse execution gate.
 * Auto-generated by intutic sync-daemon. DO NOT EDIT.
 *
 * Dual-path logEvent:
 *   Path B — synchronous file append to hook-events.jsonl
 *   Path A — fire-and-forget https.request to the control plane
 *
 * Proxy: ${proxyUrl}
 * Generated: ${newIso()}
 * Workspace: ${workspaceId}
 */
'use strict';
${emitJsFailClosedPrelude({ harness: 'claude-desktop', contract: 'exit2' })}
const path = require('path');
const os = require('os');
const fs = require('fs');
const https = require('https');
const crypto = require('crypto');
const url = require('url');

// ── Runtime env loader (Path A credentials) ──────────────────────────────────
const RUNTIME_ENV_PATH = ${JSON.stringify(runtimeEnvPath)};

function loadRuntimeEnv() {
  const env = {
    INTUTIC_HOST: 'https://api.intutic.ai',
    INTUTIC_API_KEY: '',
    INTUTIC_WORKSPACE_ID: ${JSON.stringify(workspaceId)},
  };
  try {
    const raw = fs.readFileSync(RUNTIME_ENV_PATH, 'utf-8');
    for (const line of raw.split('\\n')) {
      const stripped = line.trim();
      if (!stripped || stripped.startsWith('#') || !stripped.includes('=')) continue;
      const eq = stripped.indexOf('=');
      const k = stripped.slice(0, eq).trim();
      const v = stripped.slice(eq + 1).trim();
      env[k] = v;
    }
  } catch { /* file may not exist yet */ }
  return env;
}

// ── Governance-sensitive paths ────────────────────────────────────────────────
${emitJsGate({ harness: "claude-desktop", contract: 'exit2' })}

// ── Dual-path logEvent ────────────────────────────────────────────────────────
const HOOK_EVENTS_LOG = ${JSON.stringify(hookEventsLog)};

let _intuticSessionId = '';
function logEvent(env, verdict, toolName, reason) {
  const ts = new Date().toISOString();
  const incidentId = crypto.createHash('sha1')
    .update(ts + toolName + env.INTUTIC_WORKSPACE_ID)
    .digest('hex').slice(0, 16);

  const entry = {
    // Passed through, not collapsed to two values: the advisory tier emits
      // 'tool_flagged', and a ternary here silently recorded it as an allow.
      event: verdict,
    toolName,
    reason: reason || '',
    workspaceId: env.INTUTIC_WORKSPACE_ID,
    harnessType: 'claude-desktop',
    timestamp: ts,
    incidentId,
    ...(_intuticSessionId ? { sessionId: _intuticSessionId } : {}),
  };

  // Path B — reliable file append
  try {
    const dir = path.dirname(HOOK_EVENTS_LOG);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.appendFileSync(HOOK_EVENTS_LOG, JSON.stringify(entry) + '\\n', { flag: 'a' });
  } catch { /* never crash the hook */ }

  // Path A — fire-and-forget https.request
  if (env.INTUTIC_API_KEY) {
    try {
      const body = Buffer.from(JSON.stringify({ events: [entry] }));
      const parsedUrl = url.parse(env.INTUTIC_HOST + '/api/v1/hook-events');
      const req = https.request({
        hostname: parsedUrl.hostname,
        port: parsedUrl.port || 443,
        path: parsedUrl.path,
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Content-Length': body.length,
          'Authorization': 'Bearer ' + env.INTUTIC_API_KEY,
        },
      });
      req.on('error', () => {}); // fire-and-forget
      req.write(body);
      req.end();
    } catch { /* never crash the hook */ }
  }
}

// ── Main ──────────────────────────────────────────────────────────────────────
const runtimeEnv = loadRuntimeEnv();
let inputData = '';
process.stdin.on('data', (chunk) => { inputData += chunk; });
process.stdin.on('end', () => {
  try {
    const ctx = JSON.parse(inputData);
    _intuticSessionId = ctx.session_id || ctx.sessionId || ctx.conversation_id || ctx.conversationId || ctx.task_id || ctx.taskId || '';
    // An envelope carrying none of the tool fields extracts to empty strings,
    // which match no rule — an allow. Refused instead; see the guard itself.
    intuticGuardEnvelope(ctx, ['tool_name', 'toolName', 'tool_input', 'toolInput'],
      (v, t, r) => logEvent(runtimeEnv, v, t, r));
    const toolName = (ctx.tool_name || ctx.toolName || '').toLowerCase()
    // Case preserved for the gate. A BLOCK: SOP compiles to a tool-name
    // pattern the operator wrote as they see it (Bash, Write) and this
    // harness lowercases the tool for its own matching. Handing the gate the
    // lowercased form means every SOP tool rule silently matches nothing here
    // while appearing active everywhere else.
    const rawToolName = ctx.tool_name || ctx.toolName || '';
    const toolInput = ctx.tool_input || ctx.toolInput || {};
    const toolInputStr = JSON.stringify(toolInput);

    // Both guards used to be gated on the tool name — paths only for
    // edit/write/multiedit, commands only for a tool literally called "bash".
    // A harness that names its shell tool anything else (run_command, terminal,
    // execute) walked past both. The shared gate keys on the *arguments*, so a
    // tool name nobody anticipated is no longer a bypass.
    const targetPath = toolInput.path || toolInput.file_path || toolInput.filePath ||
      toolInput.new_path || toolInput.target || toolInput.notebook_path || '';
    const command = toolInput.command || toolInput.cmd || toolInput.script || '';
    intuticGate(rawToolName, targetPath, command, (v, t, r) => logEvent(runtimeEnv, v, t, r), runtimeEnv.INTUTIC_WORKSPACE_ID, toolInput);

    logEvent(runtimeEnv, 'tool_allowed', toolName, '');
    process.exit(0);
  } catch (err) {
    console.error('[Intutic Guardrail] Hook error (blocking for safety):', err);
    logEvent(runtimeEnv, 'tool_blocked', 'unknown', String(err));
    process.exit(2);
  }
});
`.trim()
}

// ─── Main export ──────────────────────────────────────────────────────────────

/**
 * Write the Claude Desktop governance hook script and merge hook configuration
 * into the OS-specific claude_desktop_config.json.
 *
 * Safe to call repeatedly — uses atomic rename (`.intutic-tmp` → final path).
 * Does NOT touch the `mcpServers` section of the config.
 *
 * @param workspaceRoot - Absolute workspace root path.
 * @param proxyUrl      - Intutic proxy URL written into the hook script header.
 * @param workspaceId   - Workspace ID embedded in every hook event payload.
 */
export async function writeClaudeDesktopHooks(
  workspaceRoot: string,
  proxyUrl: string,
  workspaceId = '',
): Promise<void> {
  // ── 1. Ensure directories ──────────────────────────────────────────────────

  const hookScriptDir = path.join(workspaceRoot, '.intutic', 'hooks')
  const hookEventsDir = path.join(workspaceRoot, '.intutic', 'events')
  const desktopConfigPath = resolveClaudeDesktopConfigPath()
  const desktopConfigDir = path.dirname(desktopConfigPath)

  await Promise.all([
    fs.mkdir(hookScriptDir, { recursive: true }),
    fs.mkdir(hookEventsDir, { recursive: true }),
    fs.mkdir(desktopConfigDir, { recursive: true }),
  ])

  // ── 2. Write hook script (atomic) ─────────────────────────────────────────

  const hookScriptPath = path.join(hookScriptDir, 'claude-desktop-check.js')
  const tmpScript = hookScriptPath + '.intutic-tmp'
  await fs.writeFile(tmpScript, buildClaudeDesktopCheckScript(proxyUrl, workspaceRoot, workspaceId), 'utf-8')
  await fs.rename(tmpScript, hookScriptPath)

  log.info({ action: 'claude_desktop_hook_script_written', path: hookScriptPath }, 'Claude Desktop hook script written')

  // ── 3. Merge into claude_desktop_config.json (safe merge, preserve mcpServers) ──

  let existingConfig: Record<string, unknown> = {}
  try {
    const raw = await fs.readFile(desktopConfigPath, 'utf-8')
    existingConfig = JSON.parse(raw)
  } catch {
    // File doesn't exist yet — start fresh
  }

  const existingHooks = (existingConfig.hooks as Record<string, unknown>) ?? {}
  const existingPreToolUse = (existingHooks.PreToolUse as unknown[]) ?? []

  // De-duplicate: remove any existing Intutic entry for Bash then re-add
  // M3: 'mcp__.*' routes Claude Desktop's mcp__<server>__<tool> calls into
  // this same gate script — see the identical note in claudeCodeHooks.ts,
  // which shares this harness's PreToolUse contract exactly.
  const HOOK_MATCHERS = ['Bash', 'Edit', 'Write', 'MultiEdit', 'mcp__.*']
  const intuticCmd = `node ${hookScriptPath}`
  const filteredPTU = existingPreToolUse.filter((entry: unknown) => {
    if (typeof entry !== 'object' || entry === null) return true
    const e = entry as Record<string, unknown>
    // Remove entries where all inner hooks use the intutic command
    const innerHooks = (e.hooks as unknown[]) ?? []
    return !innerHooks.every(
      (h: unknown) => typeof h === 'object' && h !== null && (h as Record<string, unknown>).command === intuticCmd,
    )
  })

  const newPreToolUseEntries = HOOK_MATCHERS.map((matcher) => ({
    matcher,
    hooks: [{ type: 'command', command: intuticCmd }],
  }))

  const mergedConfig = {
    ...existingConfig,
    hooks: {
      ...existingHooks,
      PreToolUse: [...filteredPTU, ...newPreToolUseEntries],
    },
  }

  const tmpConfig = desktopConfigPath + '.intutic-tmp'
  await fs.writeFile(tmpConfig, JSON.stringify(mergedConfig, null, 2) + '\n', 'utf-8')
  await fs.rename(tmpConfig, desktopConfigPath)

  log.info(
    { action: 'claude_desktop_config_written', path: desktopConfigPath },
    'Merged Intutic hooks into claude_desktop_config.json',
  )
}
