/**
 * clineHooks.ts — Cline PreToolUse governance hook injection.
 *
 * Writes .cline/hooks/hooks.json and the Intutic pre-tool-check
 * script into the workspace. Cline's hook system accepts JSON on stdin
 * and blocks execution when the script returns {"cancel": true}.
 *
 * NOTE: Hooks are placed in .cline/hooks/ (NOT .clinerules/hooks/) to avoid
 * ENOTDIR conflict — .clinerules is written as a flat file by the CLI adapter.
 *
 * LLD #14 — Phase 3 cross-harness defence
 * HLD §3.14 — Three-Tier Defense Cascade
 *
 * @module
 */

import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import { createLogger } from '@intutic/logger'
import { newIso } from '@intutic/id'

const log = createLogger('sync-cline-hooks')

/** Tools Cline can invoke that require governance interception. */
const GOVERNED_TOOLS = [
  'execute_command',
  'write_to_file',
  'str_replace_based_edit_tool',
  'replace_in_file',
  'create_file',
  'delete_file',
  'rename_file',
  'read_file',  // watch for exfiltration patterns
]

/**
 * Governance-sensitive paths that must never be agent-modified.
 * Mirrors the protected path list in claudeCodeHooks.ts.
 */
const PROTECTED_PATH_FRAGMENTS = [
  '.cline/hooks',
  '.intutic/hooks',
  '.intutic/integrity.json',
  '.claude/settings.json',
  '.cursor/hooks.json',
  '.codeium/windsurf/hooks.json',
  '.agents/plugins/intutic-governance',
  '.openhands/hooks.json',
]

/**
 * Write the Intutic governance hook into .cline/hooks/.
 *
 * @param workspaceRoot - Absolute workspace root path.
 * @param proxyUrl - Intutic proxy URL for inclusion in block messages.
 */
export async function writeClineHooks(
  workspaceRoot: string,
  proxyUrl: string,
  workspaceId = '',
): Promise<void> {
  const hooksDir = path.join(workspaceRoot, '.cline', 'hooks')
  const hooksJsonPath = path.join(hooksDir, 'hooks.json')
  const checkScriptPath = path.join(hooksDir, 'intutic-check.js')

  await fs.mkdir(hooksDir, { recursive: true })

  // ── hooks.json ──────────────────────────────────────────────────────
  // Cline reads this file and runs matched hook scripts before tool execution.
  // The matcher regex is matched against the tool name.
  const hooksConfig = {
    _comment: 'Intutic governance hooks — auto-generated. DO NOT EDIT.',
    _lastSync: newIso(),
    hooks: GOVERNED_TOOLS.map((tool) => ({
      type: 'PreToolUse',
      matcher: `^${tool}$`,
      command: `node ${checkScriptPath}`,
    })),
  }

  const tmpJson = hooksJsonPath + '.intutic-tmp'
  await fs.writeFile(tmpJson, JSON.stringify(hooksConfig, null, 2) + '\n', 'utf-8')
  await fs.rename(tmpJson, hooksJsonPath)

  // ── pre-tool-check script ────────────────────────────────────────────
  // Cline passes tool_name + tool_input as JSON on stdin.
  // Return {"cancel": false} to allow, {"cancel": true, "errorMessage": "..."} to block.
  const checkScript = `#!/usr/bin/env node
/**
 * Intutic Cline PreToolUse governance gate.
 * Auto-generated by intutic sync-daemon. DO NOT EDIT.
 * Proxy: ${proxyUrl}
 * Generated: ${newIso()}
 */
const path = require('path');
const os = require('os');
const fs = require('fs');
const crypto = require('crypto');
const https = require('https');

// Runtime credentials
const _runtimeEnvPath = path.join(os.homedir(), '.intutic', 'env', 'runtime.env');
let _intuticHost = 'https://api.intutic.ai', _intuticKey = '', _intuticWsId = ${JSON.stringify(workspaceId)};
try {
  fs.readFileSync(_runtimeEnvPath, 'utf-8').split('\\n').forEach(line => {
    const eq = line.indexOf('='); if (eq < 0) return;
    const k = line.slice(0, eq).trim(), v = line.slice(eq + 1).trim();
    if (k === 'INTUTIC_HOST' && v) _intuticHost = v;
    if (k === 'INTUTIC_API_KEY' && v) _intuticKey = v;
    if (k === 'INTUTIC_WORKSPACE_ID' && v) _intuticWsId = v;
  });
} catch {}

const HOOK_EVENTS_LOG = path.join(os.homedir(), '.intutic', 'events', 'cline-hook-events.jsonl');

function logEvent(verdict, toolName, reason) {
  try {
    const ts = new Date().toISOString();
    const incidentId = crypto.createHash('sha1').update(ts + toolName + _intuticWsId).digest('hex').slice(0, 16);
    const entry = JSON.stringify({ event: verdict === 'blocked' ? 'tool_blocked' : 'tool_allowed', toolName, reason: reason || '', workspaceId: _intuticWsId, harnessType: 'cline', timestamp: ts, incidentId }) + '\\n';
    try { fs.appendFileSync(HOOK_EVENTS_LOG, entry, { flag: 'a' }); } catch {}
    if (_intuticKey) {
      try {
        const body = JSON.stringify({ events: [JSON.parse(entry)] });
        const urlObj = new URL('/api/v1/hook-events', _intuticHost);
        const mod = urlObj.protocol === 'https:' ? https : require('http');
        const req = mod.request({ hostname: urlObj.hostname, port: urlObj.port || 443, path: urlObj.pathname, method: 'POST', headers: { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body), 'Authorization': 'Bearer ' + _intuticKey } });
        req.on('error', () => {});
        req.write(body); req.end();
      } catch {}
    }
  } catch {}
}

const PROTECTED_PATHS = ${JSON.stringify(PROTECTED_PATH_FRAGMENTS)};

let raw = '';
process.stdin.on('data', (c) => { raw += c; });
process.stdin.on('end', () => {
  try {
    const ctx = JSON.parse(raw);
    const tool = (ctx.tool_name || '').toLowerCase();
    const input = ctx.tool_input || {};
    const inputStr = JSON.stringify(input);

    // Protected-path guard: block any write/edit/delete targeting governance files
    const targetPath = input.path || input.file_path || input.target || input.source || '';
    if (['write_to_file','str_replace_based_edit_tool','replace_in_file','create_file','delete_file','rename_file'].includes(tool)) {
      for (const p of PROTECTED_PATHS) {
        if (String(targetPath).includes(p)) {
          logEvent('blocked', tool, 'Blocked: attempt to modify governance-protected path "' + targetPath + '"');
          process.stdout.write(JSON.stringify({
            cancel: true,
            errorMessage: '[Intutic Governance] Blocked: attempt to modify governance-protected path "' + targetPath + '". Update policy via the Intutic control plane.',
          }));
          process.exit(0);
        }
      }
    }

    // Allow all other tool calls
    logEvent('allowed', tool || 'unknown', '');
    process.stdout.write(JSON.stringify({ cancel: false }));
    process.exit(0);
  } catch (err) {
    // Fail CLOSED — hook parse error blocks the tool call
    logEvent('blocked', 'unknown', String(err));
    process.stdout.write(JSON.stringify({
      cancel: true,
      errorMessage: '[Intutic Governance] Hook error (fail-closed): ' + String(err),
    }));
    process.exit(0);
  }
});
`

  const tmpScript = checkScriptPath + '.intutic-tmp'
  await fs.writeFile(tmpScript, checkScript, 'utf-8')
  await fs.rename(tmpScript, checkScriptPath)
  await fs.chmod(checkScriptPath, 0o755)

  log.info(
    { action: 'cline_hooks_written', hooksDir, toolCount: GOVERNED_TOOLS.length },
    'Cline governance hooks written',
  )
}
