/**
 * codexHooks.ts — Codex CLI PreToolUse hook injection.
 *
 * Codex CLI executes PreToolUse hooks registered in `hooks.json`:
 *   - User-level:    ~/.codex/hooks.json
 *   - Project-level: <workspaceRoot>/.codex/hooks.json
 *
 * Each PreToolUse entry carries a `matcher` regex over tool names; the hook
 * command receives JSON on stdin — {tool_name, tool_use_id, tool_input}, with
 * a shell command at tool_input.command — and refuses with **exit code 2**
 * (stderr becomes the reason shown to the agent). That is the same stdin shape
 * and exit-2 contract the shared JS gate already speaks, so the gate body is a
 * drop-in; this writer's whole job is emitting the gate file and registering
 * it in both hooks.json files without destroying anything the user put there.
 *
 * (Codex also accepts a stdout `{"hookSpecificOutput":{"permissionDecision":
 * "deny"}}` object; exit 2 is used here because it is the contract every other
 * exit-2 harness shares and the one `generatedGateBehaviour.test.ts` drives.)
 *
 * Historically codex was governed by `.env.intutic` proxy routing only — an
 * egress control, not a tool gate. This closes that gap.
 *
 * @module
 */

import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import * as os from 'node:os'
import { createLogger } from '@intutic/logger'
import { newIso } from '@intutic/id'
import { emitJsGate, emitJsFailClosedPrelude } from './gateBody.js'

const log = createLogger('sync-codex-hooks')

/**
 * The pre-tool gate script — receives Codex's PreToolUse JSON on stdin,
 * exits 0 to allow or 2 to block.
 */
function buildHookScript(proxyUrl: string, workspaceRoot: string, workspaceId: string): string {
  const hookEventsLog = path.join(workspaceRoot, '.intutic', 'events', 'hook-events.jsonl')
  return `#!/usr/bin/env node
/**
 * Intutic Codex CLI governance gate.
 * Auto-generated by intutic sync-daemon. DO NOT EDIT.
 * Proxy: ${proxyUrl}
 * Generated: ${newIso()}
 */
${emitJsFailClosedPrelude({ harness: 'codex', contract: 'exit2' })}
const path = require('path');
const os = require('os');
const fs = require('fs');
const crypto = require('crypto');
const https = require('https');

// Runtime credentials
const _runtimeEnvPath = path.join(os.homedir(), '.intutic', 'env', 'runtime.env');
let _intuticHost = 'https://api.intutic.ai', _intuticKey = '', _intuticWsId = ${JSON.stringify(workspaceId)};
try {
  fs.readFileSync(_runtimeEnvPath, 'utf-8').split('\\n').forEach(line => {
    const eq = line.indexOf('='); if (eq < 0) return;
    const k = line.slice(0, eq).trim(), v = line.slice(eq + 1).trim();
    if (k === 'INTUTIC_HOST' && v) _intuticHost = v;
    if (k === 'INTUTIC_API_KEY' && v) _intuticKey = v;
    if (k === 'INTUTIC_WORKSPACE_ID' && v) _intuticWsId = v;
  });
} catch {}

${emitJsGate({ harness: 'codex', contract: 'exit2' })}

let _intuticSessionId = '';
function logEvent(verdict, toolName, reason) {
  try {
    const ts = new Date().toISOString();
    const incidentId = crypto.createHash('sha1').update(ts + toolName + _intuticWsId).digest('hex').slice(0, 16);
    const entry = JSON.stringify({
      // Passed through, not collapsed to two values: the advisory tier emits
      // 'tool_flagged', and a ternary here silently recorded it as an allow.
      event: verdict,
      toolName, reason: reason || '',
      workspaceId: _intuticWsId,
      harnessType: 'codex',
      timestamp: ts,
      incidentId,
      ...(_intuticSessionId ? { sessionId: _intuticSessionId } : {}),
    }) + '\\n';
    fs.appendFileSync(${JSON.stringify(hookEventsLog)}, entry, { flag: 'a' });
    if (_intuticKey) {
      try {
        const body = JSON.stringify({ events: [JSON.parse(entry)] });
        const urlObj = new URL('/api/v1/hook-events', _intuticHost);
        const mod = urlObj.protocol === 'https:' ? https : require('http');
        const req = mod.request({ hostname: urlObj.hostname, port: urlObj.port || 443, path: urlObj.pathname, method: 'POST', headers: { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body), 'Authorization': 'Bearer ' + _intuticKey } });
        req.on('error', () => { /* fire-and-forget */ });
        req.write(body); req.end();
      } catch { /* never crash the hook */ }
    }
  } catch { /* never crash the hook */ }
}

let raw = '';
process.stdin.on('data', (c) => { raw += c; });
process.stdin.on('end', () => {
  try {
    const ctx = JSON.parse(raw);
    _intuticSessionId = ctx.session_id || ctx.sessionId || '';
    // Verified during the v5 audit: this writer did NOT have the envelope
    // guard its registry note implied it inherited — a payload with neither a
    // tool name nor a tool_input defaulted to toolName 'tool' with empty
    // fields, matched no rule, and was allowed. Refused now, uniformly.
    intuticGuardEnvelope(ctx, ['tool_name', 'toolName', 'tool_input', 'toolInput'], logEvent);
    const input = ctx.tool_input || ctx.toolInput || {};
    const toolName = ctx.tool_name || ctx.toolName || 'tool';

    // Every spelling any harness uses, matching the bash extractor. A field
    // name this list misses is a path guard that silently does not run — and
    // the caller controls which spelling it sends.
    const targetPath = input.path || input.file_path || input.filePath || input.file ||
      input.target || input.notebook_path || '';
    const command = input.command || input.cmd || input.script || '';

    intuticGate(toolName, targetPath, command, logEvent, _intuticWsId, input);

    // Allow
    logEvent('tool_allowed', toolName, '');
    process.exit(0);
  } catch (err) {
    // Fail CLOSED
    const errMsg = String(err);
    process.stderr.write('[Intutic Governance] Hook error (fail-closed): ' + errMsg + '\\n');
    logEvent('tool_blocked', 'unknown', errMsg);
    process.exit(2);
  }
});
`
}

/**
 * Merge the Intutic PreToolUse entry into a Codex hooks.json, preserving
 * everything the user registered themselves.
 *
 * De-duplication is by command (any entry whose hooks all invoke this gate
 * script is ours and is replaced), the same convention claudeDesktopHooks
 * uses — so repeated syncs are idempotent and never stack duplicate entries.
 */
async function mergeCodexHooksJson(configPath: string, hookScriptPath: string): Promise<void> {
  let existing: Record<string, unknown> = {}
  try {
    existing = JSON.parse(await fs.readFile(configPath, 'utf-8'))
  } catch {
    // File doesn't exist or is malformed — start fresh
  }

  const existingHooks = (existing.hooks as Record<string, unknown>) ?? {}
  const existingPreToolUse = Array.isArray(existingHooks.PreToolUse)
    ? (existingHooks.PreToolUse as unknown[])
    : []

  const intuticCmd = `node "${hookScriptPath}"`
  const filtered = existingPreToolUse.filter((entry: unknown) => {
    if (typeof entry !== 'object' || entry === null) return true
    const inner = ((entry as Record<string, unknown>).hooks as unknown[]) ?? []
    return !(
      inner.length > 0 &&
      inner.every(
        (h: unknown) =>
          typeof h === 'object' && h !== null && (h as Record<string, unknown>).command === intuticCmd,
      )
    )
  })

  // Provenance lives in `description` and NOWHERE else: Codex parses
  // hooks.json with a strict schema ("expected `description` or `hooks`") and
  // REJECTS the entire file over an unknown top-level key. The first version
  // of this writer stamped `_intutic_comment`/`_intutic_last_sync` here, and a
  // live smoke against codex-cli 0.147.0 showed the gate silently never
  // loading — "warning: failed to parse hooks config … unknown field
  // `_intutic_comment`" — while every emitted-script test stayed green. Only
  // fields the consumer's schema names may appear at this level, and the two
  // legacy keys are actively deleted so a file the old writer touched heals
  // on the next sync instead of staying rejected forever.
  delete (existing as Record<string, unknown>)['_intutic_comment']
  delete (existing as Record<string, unknown>)['_intutic_last_sync']
  const merged = {
    ...existing,
    description:
      'Intutic governance PreToolUse hook (auto-managed; your own hooks are preserved). ' +
      `Last sync: ${newIso()}`,
    hooks: {
      ...existingHooks,
      PreToolUse: [
        ...filtered,
        {
          // One catch-all matcher rather than a tool list: the gate itself
          // decides from the arguments, so a tool name nobody anticipated is
          // still evaluated rather than silently unmatched.
          matcher: '.*',
          hooks: [{ type: 'command', command: intuticCmd }],
        },
      ],
    },
  }

  const tmp = configPath + '.intutic-tmp'
  await fs.writeFile(tmp, JSON.stringify(merged, null, 2) + '\n', 'utf-8')
  await fs.rename(tmp, configPath)
}

/**
 * Write the Codex gate script and register it at user and project level.
 *
 * Safe to call repeatedly — uses atomic rename (`.intutic-tmp` → final path)
 * and command-keyed de-duplication in both hooks.json files.
 *
 * @param workspaceRoot - Absolute workspace root path.
 * @param proxyUrl      - Intutic proxy URL written into the gate header.
 * @param workspaceId   - Workspace ID embedded in every hook event payload.
 */
export async function writeCodexHooks(
  workspaceRoot: string,
  proxyUrl: string,
  workspaceId = '',
): Promise<void> {
  const hookScriptDir = path.join(workspaceRoot, '.intutic', 'hooks')
  await fs.mkdir(hookScriptDir, { recursive: true })
  await fs.mkdir(path.join(workspaceRoot, '.intutic', 'events'), { recursive: true })

  // Named after its writer — see the note in claudeCodeHooks.ts about two
  // writers overwriting one `pre-tool-check.js`.
  const hookScriptPath = path.join(hookScriptDir, 'codex-check.js')
  const tmpScript = hookScriptPath + '.intutic-tmp'
  await fs.writeFile(tmpScript, buildHookScript(proxyUrl, workspaceRoot, workspaceId), 'utf-8')
  await fs.rename(tmpScript, hookScriptPath)
  await fs.chmod(hookScriptPath, 0o755)

  // 1. Project-level: <root>/.codex/hooks.json
  const projectCodexDir = path.join(workspaceRoot, '.codex')
  await fs.mkdir(projectCodexDir, { recursive: true })
  await mergeCodexHooksJson(path.join(projectCodexDir, 'hooks.json'), hookScriptPath)
  log.info({ action: 'codex_hooks_written', level: 'project', path: projectCodexDir }, 'Codex project-level hooks written')

  // 2. User-level: ~/.codex/hooks.json
  const userCodexDir = path.join(os.homedir(), '.codex')
  await fs.mkdir(userCodexDir, { recursive: true })
  await mergeCodexHooksJson(path.join(userCodexDir, 'hooks.json'), hookScriptPath)
  log.info({ action: 'codex_hooks_written', level: 'user', path: userCodexDir }, 'Codex user-level hooks written')
}
