/**
 * continueHooks.ts — Continue CLI PreToolUse gate.
 *
 * Proxy routing for Continue (the `apiBase` of each OpenAI/Anthropic model in
 * `~/.continue/config.yaml`) is written by the CLI's Continue adapter
 * (tools/cli/src/harness/continue.ts). This module writes only the gate.
 *
 * **PreToolUse gate** (Continue **CLI `cn` only** — the IDE extension has
 *    no hook system): the CLI executes PreToolUse hooks registered in
 *    `~/.continue/settings.json` (user) and `<repo>/.continue/settings.json`
 *    (project), with a Claude-Code-compatible stdin contract —
 *    {tool_name, tool_input, tool_use_id} — refused via exit code 2 (or a
 *    stdout `{"permissionDecision":"deny"}`; exit 2 is used here, the contract
 *    every other exit-2 harness shares).
 *
 *    **LIVE-VERIFIED LIMITS (cn 1.5.47, 2026-08-10), do not oversell this
 *    gate:**
 *    - **Headless `-p`/`--print` mode does not execute PreToolUse hooks at
 *      all.** Verified against a real install with a bare marker hook: the
 *      terminal tool ran, the marker never fired, with the hook registered in
 *      every path the bundle's own search list names. The hooks engine (and
 *      this exact search list, including `.claude/settings.json`) is present
 *      in the shipped bundle — headless mode simply bypasses it. Interactive
 *      TUI sessions are the mode this registration targets; a headless `cn
 *      -p` run is governed by the proxy layer only.
 *    - **cn's hook engine fails OPEN on hook errors by its own design** —
 *      the bundled dispatcher catches a failed hook event and returns
 *      `{blocked: false}`. Our gate's own crash posture (fail-closed exit 2)
 *      cannot override the harness swallowing the failure; that is cn's
 *      contract, recorded here so the security matrix can say it honestly.
 *
 *    **Overlap, stated so nobody "fixes" it:** the Continue CLI ALSO reads
 *    `.claude/settings.json`, so on a machine where claude-code is governed,
 *    `cn` may already run the claude-code gate by accident. This writer makes
 *    that deliberate by registering in Continue's own settings files — the
 *    dedicated registration is still correct because a user who runs continue
 *    but not claude-code has no `.claude/settings.json` and would otherwise
 *    get no gate at all. Double registration is harmless: both gates evaluate
 *    the same rules, and an allow/allow or block/block pair is idempotent.
 *
 * The settings files are merged, never replaced: a file that is not a plain
 * JSON object is left alone and reported (see jsonMergeTarget.ts).
 *
 * LLD #14 — Phase 3 cross-harness defence (Gap 3, WS-B)
 * HLD §3.14 — Three-Tier Defense Cascade (Tier 1 Native Gating)
 *
 * @module
 */

import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import * as os from 'node:os'
import { createLogger } from '@intutic/logger'
import { newIso } from '@intutic/id'
import { emitJsGate, emitJsFailClosedPrelude } from './gateBody.js'
import { readJsonObjectForMerge } from './jsonMergeTarget.js'

const log = createLogger('sync-continue-hooks')

// ─── PreToolUse gate (Continue CLI `cn`) ──────────────────────────────────────

/**
 * The pre-tool gate script — receives the Continue CLI's Claude-Code-compatible
 * PreToolUse JSON on stdin, exits 0 to allow or 2 to block.
 */
function buildHookScript(proxyUrl: string, workspaceRoot: string, workspaceId: string): string {
  const hookEventsLog = path.join(workspaceRoot, '.intutic', 'events', 'hook-events.jsonl')
  return `#!/usr/bin/env node
/**
 * Intutic Continue CLI governance gate.
 * Auto-generated by intutic sync-daemon. DO NOT EDIT.
 *
 * Applies to the Continue CLI (cn) only — the IDE extension has no hook
 * system. Note the CLI also reads .claude/settings.json, so a machine governed
 * for claude-code may run that gate too; both evaluate the same rules.
 *
 * Proxy: ${proxyUrl}
 * Generated: ${newIso()}
 */
${emitJsFailClosedPrelude({ harness: 'continue', contract: 'exit2' })}
const path = require('path');
const os = require('os');
const fs = require('fs');
const crypto = require('crypto');
const https = require('https');

// Runtime credentials
const _runtimeEnvPath = path.join(os.homedir(), '.intutic', 'env', 'runtime.env');
let _intuticHost = 'https://api.intutic.ai', _intuticKey = '', _intuticWsId = ${JSON.stringify(workspaceId)};
try {
  fs.readFileSync(_runtimeEnvPath, 'utf-8').split('\\n').forEach(line => {
    const eq = line.indexOf('='); if (eq < 0) return;
    const k = line.slice(0, eq).trim(), v = line.slice(eq + 1).trim();
    if (k === 'INTUTIC_HOST' && v) _intuticHost = v;
    if (k === 'INTUTIC_API_KEY' && v) _intuticKey = v;
    if (k === 'INTUTIC_WORKSPACE_ID' && v) _intuticWsId = v;
  });
} catch {}

${emitJsGate({ harness: 'continue', contract: 'exit2' })}

let _intuticSessionId = '';
function logEvent(verdict, toolName, reason) {
  try {
    const ts = new Date().toISOString();
    const incidentId = crypto.createHash('sha1').update(ts + toolName + _intuticWsId).digest('hex').slice(0, 16);
    const entry = JSON.stringify({
      // Passed through, not collapsed to two values: the advisory tier emits
      // 'tool_flagged', and a ternary here silently recorded it as an allow.
      event: verdict,
      toolName, reason: reason || '',
      workspaceId: _intuticWsId,
      harnessType: 'continue',
      timestamp: ts,
      incidentId,
      ...(_intuticSessionId ? { sessionId: _intuticSessionId } : {}),
    }) + '\\n';
    fs.appendFileSync(${JSON.stringify(hookEventsLog)}, entry, { flag: 'a' });
    if (_intuticKey) {
      try {
        const body = JSON.stringify({ events: [JSON.parse(entry)] });
        const urlObj = new URL('/api/v1/hook-events', _intuticHost);
        const mod = urlObj.protocol === 'https:' ? https : require('http');
        const req = mod.request({ hostname: urlObj.hostname, port: urlObj.port || 443, path: urlObj.pathname, method: 'POST', headers: { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body), 'Authorization': 'Bearer ' + _intuticKey } });
        req.on('error', () => { /* fire-and-forget */ });
        req.write(body); req.end();
      } catch { /* never crash the hook */ }
    }
  } catch { /* never crash the hook */ }
}

let raw = '';
process.stdin.on('data', (c) => { raw += c; });
process.stdin.on('end', () => {
  try {
    const ctx = JSON.parse(raw);
    _intuticSessionId = ctx.session_id || ctx.sessionId || '';
    // Verified during the v5 audit: this writer did NOT have the envelope
    // guard its Claude-Code-compatible contract implied it inherited — a
    // payload with neither a tool name nor a tool_input defaulted to toolName
    // 'tool' with empty fields, matched no rule, and was allowed. Refused now.
    intuticGuardEnvelope(ctx, ['tool_name', 'toolName', 'tool_input', 'toolInput'], logEvent);
    const input = ctx.tool_input || ctx.toolInput || {};
    const toolName = ctx.tool_name || ctx.toolName || 'tool';

    // Every spelling any harness uses, matching the bash extractor. A field
    // name this list misses is a path guard that silently does not run — and
    // the caller controls which spelling it sends.
    const targetPath = input.path || input.file_path || input.filePath || input.file ||
      input.target || input.notebook_path || '';
    const command = input.command || input.cmd || input.script || '';

    intuticGate(toolName, targetPath, command, logEvent, _intuticWsId, input);

    // Allow
    logEvent('tool_allowed', toolName, '');
    process.exit(0);
  } catch (err) {
    // Fail CLOSED
    const errMsg = String(err);
    process.stderr.write('[Intutic Governance] Hook error (fail-closed): ' + errMsg + '\\n');
    logEvent('tool_blocked', 'unknown', errMsg);
    process.exit(2);
  }
});
`
}

/**
 * Merge the Intutic PreToolUse entry into a Continue settings.json, preserving
 * everything the user registered themselves.
 *
 * De-duplication is by command (any entry whose hooks all invoke this gate
 * script is ours and is replaced) — the claudeDesktopHooks convention — so
 * repeated syncs never stack duplicate entries.
 */
async function mergeContinueSettings(settingsPath: string, hookScriptPath: string): Promise<void> {
  const existing = await readJsonObjectForMerge(settingsPath)
  if (existing === null) return

  const existingHooks = (existing.hooks as Record<string, unknown>) ?? {}
  const existingPreToolUse = Array.isArray(existingHooks.PreToolUse)
    ? (existingHooks.PreToolUse as unknown[])
    : []

  const intuticCmd = `node "${hookScriptPath}"`
  const filtered = existingPreToolUse.filter((entry: unknown) => {
    if (typeof entry !== 'object' || entry === null) return true
    const inner = ((entry as Record<string, unknown>).hooks as unknown[]) ?? []
    return !(
      inner.length > 0 &&
      inner.every(
        (h: unknown) =>
          typeof h === 'object' && h !== null && (h as Record<string, unknown>).command === intuticCmd,
      )
    )
  })

  const merged = {
    ...existing,
    _intutic_comment: 'Intutic governance PreToolUse hook (Continue CLI) — auto-managed entries only; your own hooks are preserved.',
    _intutic_last_sync: newIso(),
    hooks: {
      ...existingHooks,
      PreToolUse: [
        ...filtered,
        {
          // One catch-all matcher rather than a tool list: the gate itself
          // decides from the arguments, so a tool name nobody anticipated is
          // still evaluated rather than silently unmatched.
          matcher: '.*',
          hooks: [{ type: 'command', command: intuticCmd }],
        },
      ],
    },
  }

  const tmp = settingsPath + '.intutic-tmp'
  await fs.writeFile(tmp, JSON.stringify(merged, null, 2) + '\n', 'utf-8')
  await fs.rename(tmp, settingsPath)
}

// ─── Main export ──────────────────────────────────────────────────────────────

/**
 * Write the Continue CLI gate script `.intutic/hooks/continue-check.js` and
 * register it in `~/.continue/settings.json` and
 * `<root>/.continue/settings.json` (see the module header for the
 * `.claude/settings.json` overlap).
 *
 * Safe to call repeatedly — uses atomic rename (`.intutic-tmp` → final path)
 * and command-keyed de-duplication in both settings files.
 *
 * @param workspaceRoot - Absolute workspace root path.
 * @param proxyUrl      - Intutic proxy URL written into the gate header.
 * @param workspaceId   - Workspace ID embedded in every hook event payload.
 */
export async function writeContinueHooks(
  workspaceRoot: string,
  proxyUrl: string,
  workspaceId = '',
): Promise<void> {
  const hookScriptDir = path.join(workspaceRoot, '.intutic', 'hooks')
  await fs.mkdir(hookScriptDir, { recursive: true })
  await fs.mkdir(path.join(workspaceRoot, '.intutic', 'events'), { recursive: true })

  // Named after its writer — see the note in claudeCodeHooks.ts about two
  // writers overwriting one `pre-tool-check.js`.
  const hookScriptPath = path.join(hookScriptDir, 'continue-check.js')
  const tmpScript = hookScriptPath + '.intutic-tmp'
  await fs.writeFile(tmpScript, buildHookScript(proxyUrl, workspaceRoot, workspaceId), 'utf-8')
  await fs.rename(tmpScript, hookScriptPath)
  await fs.chmod(hookScriptPath, 0o755)

  // Project-level: <root>/.continue/settings.json
  const projectContinueDir = path.join(workspaceRoot, '.continue')
  await fs.mkdir(projectContinueDir, { recursive: true })
  await mergeContinueSettings(path.join(projectContinueDir, 'settings.json'), hookScriptPath)

  // User-level: ~/.continue/settings.json. homedir() read at call time so
  // tests that move HOME before invoking are honoured — see the gooseHooks
  // note in generatedShellIntegrity.test.ts.
  const userContinueDir = path.join(os.homedir(), '.continue')
  await fs.mkdir(userContinueDir, { recursive: true })
  await mergeContinueSettings(path.join(userContinueDir, 'settings.json'), hookScriptPath)

  log.info(
    { action: 'continue_gate_written', path: hookScriptPath },
    'Continue CLI PreToolUse gate written and registered (project + user settings.json)',
  )
}
