/**
 * continueHooks.ts — Continue governance: proxy routing + CLI PreToolUse gate.
 *
 * Two mechanisms, for two different Continue surfaces:
 *
 * 1. **Proxy routing** (both surfaces): each model's `apiBase` field in
 *    `~/.continue/config.json` is set to `proxyUrl`, so LLM egress traverses
 *    the Intutic proxy.
 *
 * 2. **PreToolUse gate** (Continue **CLI `cn` only** — the IDE extension has
 *    no hook system): the CLI executes PreToolUse hooks registered in
 *    `~/.continue/settings.json` (user) and `<repo>/.continue/settings.json`
 *    (project), with a Claude-Code-compatible stdin contract —
 *    {tool_name, tool_input, tool_use_id} — refused via exit code 2 (or a
 *    stdout `{"permissionDecision":"deny"}`; exit 2 is used here, the contract
 *    every other exit-2 harness shares).
 *
 *    **LIVE-VERIFIED LIMITS (cn 1.5.47, 2026-08-10), do not oversell this
 *    gate:**
 *    - **Headless `-p`/`--print` mode does not execute PreToolUse hooks at
 *      all.** Verified against a real install with a bare marker hook: the
 *      terminal tool ran, the marker never fired, with the hook registered in
 *      every path the bundle's own search list names. The hooks engine (and
 *      this exact search list, including `.claude/settings.json`) is present
 *      in the shipped bundle — headless mode simply bypasses it. Interactive
 *      TUI sessions are the mode this registration targets; a headless `cn
 *      -p` run is governed by the proxy layer only.
 *    - **cn's hook engine fails OPEN on hook errors by its own design** —
 *      the bundled dispatcher catches a failed hook event and returns
 *      `{blocked: false}`. Our gate's own crash posture (fail-closed exit 2)
 *      cannot override the harness swallowing the failure; that is cn's
 *      contract, recorded here so the security matrix can say it honestly.
 *
 *    **Overlap, stated so nobody "fixes" it:** the Continue CLI ALSO reads
 *    `.claude/settings.json`, so on a machine where claude-code is governed,
 *    `cn` may already run the claude-code gate by accident. This writer makes
 *    that deliberate by registering in Continue's own settings files — the
 *    dedicated registration is still correct because a user who runs continue
 *    but not claude-code has no `.claude/settings.json` and would otherwise
 *    get no gate at all. Double registration is harmless: both gates evaluate
 *    the same rules, and an allow/allow or block/block pair is idempotent.
 *
 * JSONC handling: ~/.continue/config.json allows `// comments`. We strip
 * single-line comments with a regex before parsing, then write back as
 * standard JSON with a managed-file header comment.
 *
 * LLD #14 — Phase 3 cross-harness defence (Gap 3, WS-B)
 * HLD §3.14 — Three-Tier Defense Cascade (Tier 1 Native Gating)
 *
 * @module
 */

import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import * as os from 'node:os'
import { createLogger } from '@intutic/logger'
import { newIso } from '@intutic/id'
import { emitJsGate, emitJsFailClosedPrelude } from './gateBody.js'

const log = createLogger('sync-continue-hooks')

/** Default path to the Continue.dev global config file. */
const CONTINUE_CONFIG_PATH = path.join(os.homedir(), '.continue', 'config.json')

/** Governance notice injected into customInstructions. */
const GOVERNANCE_NOTICE = [
  'This workspace is governed by Intutic SOP policies.',
  'All LLM API requests are routed through the Intutic governance proxy.',
  'Do not remove or override the apiBase field in this configuration.',
].join(' ')

// ─── JSONC comment stripper ───────────────────────────────────────────────────

/**
 * Strip single-line `// ...` comments from a JSONC string so it can be
 * parsed by JSON.parse. Block comments (`/* ... *\/`) are not stripped
 * because they are uncommon in Continue config files.
 */
function stripJsoncComments(raw: string): string {
  // Remove // comments that are not inside strings.
  // Simple approach: replace // up to end-of-line (acceptable for Continue config).
  return raw.replace(/\/\/[^\n]*/g, '')
}

// ─── PreToolUse gate (Continue CLI `cn`) ──────────────────────────────────────

/**
 * The pre-tool gate script — receives the Continue CLI's Claude-Code-compatible
 * PreToolUse JSON on stdin, exits 0 to allow or 2 to block.
 */
function buildHookScript(proxyUrl: string, workspaceRoot: string, workspaceId: string): string {
  const hookEventsLog = path.join(workspaceRoot, '.intutic', 'events', 'hook-events.jsonl')
  return `#!/usr/bin/env node
/**
 * Intutic Continue CLI governance gate.
 * Auto-generated by intutic sync-daemon. DO NOT EDIT.
 *
 * Applies to the Continue CLI (cn) only — the IDE extension has no hook
 * system. Note the CLI also reads .claude/settings.json, so a machine governed
 * for claude-code may run that gate too; both evaluate the same rules.
 *
 * Proxy: ${proxyUrl}
 * Generated: ${newIso()}
 */
${emitJsFailClosedPrelude({ harness: 'continue', contract: 'exit2' })}
const path = require('path');
const os = require('os');
const fs = require('fs');
const crypto = require('crypto');
const https = require('https');

// Runtime credentials
const _runtimeEnvPath = path.join(os.homedir(), '.intutic', 'env', 'runtime.env');
let _intuticHost = 'https://api.intutic.ai', _intuticKey = '', _intuticWsId = ${JSON.stringify(workspaceId)};
try {
  fs.readFileSync(_runtimeEnvPath, 'utf-8').split('\\n').forEach(line => {
    const eq = line.indexOf('='); if (eq < 0) return;
    const k = line.slice(0, eq).trim(), v = line.slice(eq + 1).trim();
    if (k === 'INTUTIC_HOST' && v) _intuticHost = v;
    if (k === 'INTUTIC_API_KEY' && v) _intuticKey = v;
    if (k === 'INTUTIC_WORKSPACE_ID' && v) _intuticWsId = v;
  });
} catch {}

${emitJsGate({ harness: 'continue', contract: 'exit2' })}

let _intuticSessionId = '';
function logEvent(verdict, toolName, reason) {
  try {
    const ts = new Date().toISOString();
    const incidentId = crypto.createHash('sha1').update(ts + toolName + _intuticWsId).digest('hex').slice(0, 16);
    const entry = JSON.stringify({
      // Passed through, not collapsed to two values: the advisory tier emits
      // 'tool_flagged', and a ternary here silently recorded it as an allow.
      event: verdict,
      toolName, reason: reason || '',
      workspaceId: _intuticWsId,
      harnessType: 'continue',
      timestamp: ts,
      incidentId,
      ...(_intuticSessionId ? { sessionId: _intuticSessionId } : {}),
    }) + '\\n';
    fs.appendFileSync(${JSON.stringify(hookEventsLog)}, entry, { flag: 'a' });
    if (_intuticKey) {
      try {
        const body = JSON.stringify({ events: [JSON.parse(entry)] });
        const urlObj = new URL('/api/v1/hook-events', _intuticHost);
        const mod = urlObj.protocol === 'https:' ? https : require('http');
        const req = mod.request({ hostname: urlObj.hostname, port: urlObj.port || 443, path: urlObj.pathname, method: 'POST', headers: { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body), 'Authorization': 'Bearer ' + _intuticKey } });
        req.on('error', () => { /* fire-and-forget */ });
        req.write(body); req.end();
      } catch { /* never crash the hook */ }
    }
  } catch { /* never crash the hook */ }
}

let raw = '';
process.stdin.on('data', (c) => { raw += c; });
process.stdin.on('end', () => {
  try {
    const ctx = JSON.parse(raw);
    _intuticSessionId = ctx.session_id || ctx.sessionId || '';
    // Verified during the v5 audit: this writer did NOT have the envelope
    // guard its Claude-Code-compatible contract implied it inherited — a
    // payload with neither a tool name nor a tool_input defaulted to toolName
    // 'tool' with empty fields, matched no rule, and was allowed. Refused now.
    intuticGuardEnvelope(ctx, ['tool_name', 'toolName', 'tool_input', 'toolInput'], logEvent);
    const input = ctx.tool_input || ctx.toolInput || {};
    const toolName = ctx.tool_name || ctx.toolName || 'tool';

    // Every spelling any harness uses, matching the bash extractor. A field
    // name this list misses is a path guard that silently does not run — and
    // the caller controls which spelling it sends.
    const targetPath = input.path || input.file_path || input.filePath || input.file ||
      input.target || input.notebook_path || '';
    const command = input.command || input.cmd || input.script || '';

    intuticGate(toolName, targetPath, command, logEvent, _intuticWsId, input);

    // Allow
    logEvent('tool_allowed', toolName, '');
    process.exit(0);
  } catch (err) {
    // Fail CLOSED
    const errMsg = String(err);
    process.stderr.write('[Intutic Governance] Hook error (fail-closed): ' + errMsg + '\\n');
    logEvent('tool_blocked', 'unknown', errMsg);
    process.exit(2);
  }
});
`
}

/**
 * Merge the Intutic PreToolUse entry into a Continue settings.json, preserving
 * everything the user registered themselves.
 *
 * De-duplication is by command (any entry whose hooks all invoke this gate
 * script is ours and is replaced) — the claudeDesktopHooks convention — so
 * repeated syncs never stack duplicate entries.
 */
async function mergeContinueSettings(settingsPath: string, hookScriptPath: string): Promise<void> {
  let existing: Record<string, unknown> = {}
  try {
    existing = JSON.parse(stripJsoncComments(await fs.readFile(settingsPath, 'utf-8')))
  } catch {
    // File doesn't exist or is malformed — start fresh
  }

  const existingHooks = (existing.hooks as Record<string, unknown>) ?? {}
  const existingPreToolUse = Array.isArray(existingHooks.PreToolUse)
    ? (existingHooks.PreToolUse as unknown[])
    : []

  const intuticCmd = `node "${hookScriptPath}"`
  const filtered = existingPreToolUse.filter((entry: unknown) => {
    if (typeof entry !== 'object' || entry === null) return true
    const inner = ((entry as Record<string, unknown>).hooks as unknown[]) ?? []
    return !(
      inner.length > 0 &&
      inner.every(
        (h: unknown) =>
          typeof h === 'object' && h !== null && (h as Record<string, unknown>).command === intuticCmd,
      )
    )
  })

  const merged = {
    ...existing,
    _intutic_comment: 'Intutic governance PreToolUse hook (Continue CLI) — auto-managed entries only; your own hooks are preserved.',
    _intutic_last_sync: newIso(),
    hooks: {
      ...existingHooks,
      PreToolUse: [
        ...filtered,
        {
          // One catch-all matcher rather than a tool list: the gate itself
          // decides from the arguments, so a tool name nobody anticipated is
          // still evaluated rather than silently unmatched.
          matcher: '.*',
          hooks: [{ type: 'command', command: intuticCmd }],
        },
      ],
    },
  }

  const tmp = settingsPath + '.intutic-tmp'
  await fs.writeFile(tmp, JSON.stringify(merged, null, 2) + '\n', 'utf-8')
  await fs.rename(tmp, settingsPath)
}

// ─── Main export ──────────────────────────────────────────────────────────────

/**
 * Configure Continue: proxy routing for both surfaces, and the CLI's
 * PreToolUse gate.
 *
 *  1. Reads `~/.continue/config.json` (JSONC — strips // comments before parsing).
 *  2. Sets `apiBase = proxyUrl` on each model that doesn't already use it.
 *  3. Adds a `customInstructions` governance notice.
 *  4. Writes the merged result back atomically.
 *  5. Writes `.intutic/env/continue.env` with the proxy URL.
 *  6. Writes the gate script `.intutic/hooks/continue-check.js` and registers
 *     it in `~/.continue/settings.json` and `<root>/.continue/settings.json`
 *     (Continue CLI PreToolUse — see the module header for the
 *     `.claude/settings.json` overlap).
 *
 * Safe to call repeatedly — uses atomic rename (`.intutic-tmp` → final path).
 *
 * @param workspaceRoot - Absolute workspace root path.
 * @param proxyUrl      - Intutic proxy URL to set as model apiBase.
 * @param workspaceId   - Workspace ID stored in the env snippet.
 */
export async function writeContinueHooks(
  workspaceRoot: string,
  proxyUrl: string,
  workspaceId = '',
): Promise<void> {
  // ── 1. Ensure directories ──────────────────────────────────────────────────

  const continueDir = path.join(os.homedir(), '.continue')
  const envDir = path.join(workspaceRoot, '.intutic', 'env')

  await Promise.all([
    fs.mkdir(continueDir, { recursive: true }),
    fs.mkdir(envDir, { recursive: true }),
  ])

  // ── 2. Read and parse ~/.continue/config.json ─────────────────────────────

  let configObj: Record<string, unknown> = {}
  try {
    const raw = await fs.readFile(CONTINUE_CONFIG_PATH, 'utf-8')
    const stripped = stripJsoncComments(raw)
    configObj = JSON.parse(stripped)
  } catch {
    // File doesn't exist or is malformed — start with empty config
    log.warn({ action: 'continue_config_read_failed', path: CONTINUE_CONFIG_PATH }, 'Could not read ~/.continue/config.json — creating fresh')
  }

  // ── 3. Update model apiBase fields ────────────────────────────────────────

  const models = Array.isArray(configObj.models) ? configObj.models : []
  let modifiedCount = 0

  const updatedModels = models.map((model: unknown) => {
    if (typeof model !== 'object' || model === null) return model
    const m = model as Record<string, unknown>
    if (m.apiBase === proxyUrl) return m // Already set — no-op
    modifiedCount++
    return { ...m, apiBase: proxyUrl }
  })

  // ── 4. Build merged config ────────────────────────────────────────────────

  const mergedConfig: Record<string, unknown> = {
    ...configObj,
    // Re-attach updated models array (or keep original if empty)
    ...(models.length > 0 ? { models: updatedModels } : {}),
    // Add/overwrite customInstructions with governance notice
    customInstructions: GOVERNANCE_NOTICE,
    // Metadata fields
    _intutic_managed: true,
    _intutic_last_sync: newIso(),
    _intutic_workspace_id: workspaceId,
  }

  // ── 5. Write back atomically ──────────────────────────────────────────────

  // Prepend a managed-file warning as a comment (will be lost on next read —
  // that's acceptable; we re-add it on each sync).
  const managedHeader = `// AUTO-MANAGED by Intutic sync-daemon. Last sync: ${newIso()}\n// Do not edit apiBase fields — they are governance proxy routes.\n`
  const serialized = managedHeader + JSON.stringify(mergedConfig, null, 2) + '\n'

  const tmpConfig = CONTINUE_CONFIG_PATH + '.intutic-tmp'
  await fs.writeFile(tmpConfig, serialized, 'utf-8')
  await fs.rename(tmpConfig, CONTINUE_CONFIG_PATH)

  log.info(
    { action: 'continue_config_written', path: CONTINUE_CONFIG_PATH, modifiedModels: modifiedCount },
    'Continue.dev config patched with Intutic proxy apiBase',
  )

  // ── 6. Write .intutic/env/continue.env ────────────────────────────────────

  const envContent = [
    `# Intutic Continue.dev governance env — auto-generated ${newIso()}`,
    `# This file is managed by the Intutic sync-daemon. DO NOT EDIT.`,
    `CONTINUE_PROXY_URL=${proxyUrl}`,
    workspaceId ? `INTUTIC_WORKSPACE_ID=${workspaceId}` : '',
    `# All Continue.dev model requests are routed through CONTINUE_PROXY_URL.`,
  ].filter((l) => l !== '').join('\n') + '\n'

  const envFilePath = path.join(envDir, 'continue.env')
  const tmpEnv = envFilePath + '.intutic-tmp'
  await fs.writeFile(tmpEnv, envContent, 'utf-8')
  await fs.rename(tmpEnv, envFilePath)

  log.info(
    { action: 'continue_env_written', path: envFilePath },
    'Continue.dev env snippet written',
  )

  // ── 7. PreToolUse gate for the Continue CLI (cn) ──────────────────────────

  const hookScriptDir = path.join(workspaceRoot, '.intutic', 'hooks')
  await fs.mkdir(hookScriptDir, { recursive: true })
  await fs.mkdir(path.join(workspaceRoot, '.intutic', 'events'), { recursive: true })

  // Named after its writer — see the note in claudeCodeHooks.ts about two
  // writers overwriting one `pre-tool-check.js`.
  const hookScriptPath = path.join(hookScriptDir, 'continue-check.js')
  const tmpScript = hookScriptPath + '.intutic-tmp'
  await fs.writeFile(tmpScript, buildHookScript(proxyUrl, workspaceRoot, workspaceId), 'utf-8')
  await fs.rename(tmpScript, hookScriptPath)
  await fs.chmod(hookScriptPath, 0o755)

  // Project-level: <root>/.continue/settings.json
  const projectContinueDir = path.join(workspaceRoot, '.continue')
  await fs.mkdir(projectContinueDir, { recursive: true })
  await mergeContinueSettings(path.join(projectContinueDir, 'settings.json'), hookScriptPath)

  // User-level: ~/.continue/settings.json. homedir() read at call time (not the
  // module-scope constant above) so tests that move HOME before invoking are
  // honoured — see the gooseHooks note in generatedShellIntegrity.test.ts.
  const userContinueDir = path.join(os.homedir(), '.continue')
  await fs.mkdir(userContinueDir, { recursive: true })
  await mergeContinueSettings(path.join(userContinueDir, 'settings.json'), hookScriptPath)

  log.info(
    { action: 'continue_gate_written', path: hookScriptPath },
    'Continue CLI PreToolUse gate written and registered (project + user settings.json)',
  )
}
