/**
 * cursorHooks.ts — Cursor beforeShellExecution/beforeMCPExecution hook injection.
 *
 * Writes hooks.json at THREE levels per enterprise-readiness requirement:
 *   1. Project-level:  <workspaceRoot>/.cursor/hooks.json
 *   2. User-level:     ~/.cursor/hooks.json
 *   3. System-level:   /etc/cursor/hooks.json (Linux) — written only by system administrators
 *
 * All three levels use failClosed: true so that if the governance script
 * fails or is missing the tool call is blocked, not allowed.
 *
 * LLD #14 — Phase 3 cross-harness defence
 * HLD §3.14 — Three-Tier Defense Cascade
 *
 * @module
 */

import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import * as os from 'node:os'
import { createLogger } from '@intutic/logger'
import { newIso } from '@intutic/id'

const log = createLogger('sync-cursor-hooks')

/** Hook events Cursor fires before execution. */
const HOOK_EVENTS = [
  'beforeShellExecution',
  'beforeMCPExecution',
  'beforeFileEdit',
] as const

/**
 * Build a Cursor hooks.json config object.
 *
 * @param hookScriptPath - Absolute path to the pre-tool-check script.
 */
function buildHooksConfig(hookScriptPath: string) {
  return {
    _comment: 'Intutic governance hooks — auto-generated. DO NOT EDIT.',
    _lastSync: newIso(),
    failClosed: true,
    hooks: Object.fromEntries(
      HOOK_EVENTS.map((event) => [
        event,
        {
          command: `node "${hookScriptPath}"`,
          failClosed: true,
        },
      ]),
    ),
  }
}

/**
 * Governance-sensitive paths — mirrors the list in claudeCodeHooks.ts.
 * Any write/edit targeting these paths is blocked.
 */
const PROTECTED_PATHS = [
  '.cursor/hooks.json',
  '.claude/settings.json',
  '.cline/hooks',
  '.intutic/hooks',
  '.intutic/integrity.json',
  '.codeium/windsurf/hooks.json',
  '.agents/plugins/intutic-governance',
  '.openhands/hooks.json',
]

/**
 * The pre-tool-check.js script content — receives JSON context from Cursor
 * on stdin, exits 0 to allow or exits 2 to block.
 */
function buildHookScript(proxyUrl: string, workspaceRoot: string, workspaceId: string): string {
  const hookEventsLog = path.join(workspaceRoot, '.intutic', 'events', 'hook-events.jsonl')
  return `#!/usr/bin/env node
/**
 * Intutic Cursor governance gate.
 * Auto-generated by intutic sync-daemon. DO NOT EDIT.
 * Proxy: ${proxyUrl}
 * Generated: ${newIso()}
 */
const path = require('path');
const os = require('os');
const fs = require('fs');
const crypto = require('crypto');
const https = require('https');

// Runtime credentials
const _runtimeEnvPath = path.join(os.homedir(), '.intutic', 'env', 'runtime.env');
let _intuticHost = 'https://api.intutic.ai', _intuticKey = '', _intuticWsId = ${JSON.stringify(workspaceId)};
try {
  fs.readFileSync(_runtimeEnvPath, 'utf-8').split('\\n').forEach(line => {
    const eq = line.indexOf('='); if (eq < 0) return;
    const k = line.slice(0, eq).trim(), v = line.slice(eq + 1).trim();
    if (k === 'INTUTIC_HOST' && v) _intuticHost = v;
    if (k === 'INTUTIC_API_KEY' && v) _intuticKey = v;
    if (k === 'INTUTIC_WORKSPACE_ID' && v) _intuticWsId = v;
  });
} catch {}

const PROTECTED_PATHS = ${JSON.stringify(PROTECTED_PATHS)};

function logEvent(verdict, toolName, reason) {
  try {
    const ts = new Date().toISOString();
    const incidentId = crypto.createHash('sha1').update(ts + toolName + _intuticWsId).digest('hex').slice(0, 16);
    const entry = JSON.stringify({
      event: verdict === 'blocked' ? 'tool_blocked' : 'tool_allowed',
      toolName, reason: reason || '',
      workspaceId: _intuticWsId,
      harnessType: 'cursor',
      timestamp: ts,
      incidentId,
    }) + '\\n';
    fs.appendFileSync(${JSON.stringify(hookEventsLog)}, entry, { flag: 'a' });
    if (_intuticKey) {
      try {
        const body = JSON.stringify({ events: [JSON.parse(entry)] });
        const urlObj = new URL('/api/v1/hook-events', _intuticHost);
        const mod = urlObj.protocol === 'https:' ? https : require('http');
        const req = mod.request({ hostname: urlObj.hostname, port: urlObj.port || 443, path: urlObj.pathname, method: 'POST', headers: { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body), 'Authorization': 'Bearer ' + _intuticKey } });
        req.on('error', () => { /* fire-and-forget */ });
        req.write(body); req.end();
      } catch { /* never crash the hook */ }
    }
  } catch { /* never crash the hook */ }
}

let raw = '';
process.stdin.on('data', (c) => { raw += c; });
process.stdin.on('end', () => {
  try {
    const ctx = JSON.parse(raw);
    const event = (ctx.event || '').toLowerCase();
    const input = ctx.input || ctx.tool_input || ctx;

    // For file edits: check target path
    const targetPath = input.path || input.file || input.target || '';
    if (event === 'beforefileedit' || (input.path && input.path.length > 0)) {
      for (const p of PROTECTED_PATHS) {
        if (String(targetPath).includes(p)) {
          const reason = 'Attempt to modify governance-protected path "' + targetPath + '"';
          process.stderr.write('[Intutic Governance] BLOCKED: ' + reason + '\\n');
          logEvent('blocked', 'edit', reason);
          process.exit(2);
        }
      }
    }

    // Shell execution: scan command for dangerous patterns
    const command = input.command || input.cmd || '';
    const dangerPatterns = [
      /chmod\\s+[0-9]*7[0-9]*\\s+.*hooks/,  // chmod on hook files
      /chattr\\s+-i\\s+/,                    // remove immutable flag
      /chflags\\s+nouchg/,                   // macOS remove uchg
    ];
    for (const pat of dangerPatterns) {
      if (pat.test(command)) {
        const reason = 'Command matches governance bypass pattern: "' + command + '"';
        process.stderr.write('[Intutic Governance] BLOCKED: ' + reason + '\\n');
        logEvent('blocked', 'bash', reason);
        process.exit(2);
      }
    }

    // Allow
    logEvent('allowed', event || 'tool', '');
    process.exit(0);
  } catch (err) {
    // Fail CLOSED
    const errMsg = String(err);
    process.stderr.write('[Intutic Governance] Hook error (fail-closed): ' + errMsg + '\\n');
    logEvent('blocked', 'unknown', errMsg);
    process.exit(2);
  }
});
`
}

/**
 * Write Cursor hooks at user-level and project-level.
 * System-level (/etc/cursor) is handled by the corporate policy installer.
 *
 * @param workspaceRoot    - Absolute workspace root.
 * @param proxyUrl         - Intutic proxy URL.
 * @param workspaceId      - Workspace ID embedded in hook event payloads.
 * @param writeSystemLevel - If true, also attempt /etc/cursor (requires root).
 */
export async function writeCursorHooks(
  workspaceRoot: string,
  proxyUrl: string,
  workspaceId = '',
  writeSystemLevel = false,
): Promise<void> {
  const hookScriptDir = path.join(workspaceRoot, '.intutic', 'hooks')
  await fs.mkdir(hookScriptDir, { recursive: true })

  // Ensure hook events log directory exists
  await fs.mkdir(path.join(workspaceRoot, '.intutic', 'events'), { recursive: true })

  const hookScriptPath = path.join(hookScriptDir, 'pre-tool-check.js')

  // Write the hook script
  const tmpScript = hookScriptPath + '.cursor-tmp'
  await fs.writeFile(tmpScript, buildHookScript(proxyUrl, workspaceRoot, workspaceId), 'utf-8')
  await fs.rename(tmpScript, hookScriptPath)
  await fs.chmod(hookScriptPath, 0o755)

  const config = buildHooksConfig(hookScriptPath)

  // 1. Project-level: .cursor/hooks.json
  const projectCursorDir = path.join(workspaceRoot, '.cursor')
  await fs.mkdir(projectCursorDir, { recursive: true })
  await atomicWriteJson(path.join(projectCursorDir, 'hooks.json'), config)
  log.info({ action: 'cursor_hooks_written', level: 'project', path: projectCursorDir }, 'Cursor project-level hooks written')

  // 2. User-level: ~/.cursor/hooks.json
  const userCursorDir = path.join(os.homedir(), '.cursor')
  await fs.mkdir(userCursorDir, { recursive: true })
  await atomicWriteJson(path.join(userCursorDir, 'hooks.json'), config)
  log.info({ action: 'cursor_hooks_written', level: 'user', path: userCursorDir }, 'Cursor user-level hooks written')

  // 3. System-level: /etc/cursor/hooks.json (system administrator installation only)
  if (writeSystemLevel) {
    const systemCursorDir = '/etc/cursor'
    try {
      await fs.mkdir(systemCursorDir, { recursive: true })
      await atomicWriteJson(path.join(systemCursorDir, 'hooks.json'), config)
      log.info({ action: 'cursor_hooks_written', level: 'system', path: systemCursorDir }, 'Cursor system-level hooks written')
    } catch (err) {
      log.error({ action: 'cursor_system_hooks_failed', err }, 'System-level Cursor hooks require root — skipping')
    }
  }
}

async function atomicWriteJson(filePath: string, data: unknown): Promise<void> {
  const tmp = filePath + '.intutic-tmp'
  await fs.writeFile(tmp, JSON.stringify(data, null, 2) + '\n', 'utf-8')
  await fs.rename(tmp, filePath)
}
