/**
 * githubCopilotHooks.ts — GitHub Copilot (VS Code agent mode) PreToolUse hooks.
 *
 * ⚠️ **PREVIEW MECHANISM.** VS Code agent hooks are a Preview feature: Copilot
 * reads hook definitions from `.github/hooks/*.json` in the workspace (and
 * from `~/.copilot/hooks` at user level), fires PreToolUse before each tool
 * call with stdin JSON {session_id, cwd, hook_event_name, tool_name,
 * tool_input, tool_use_id}, and refuses on **exit code 2** or a stdout
 * `{"permissionDecision":"deny"}` (deny wins across hooks). The format may
 * change between releases; everything below is written to fail SAFE if it
 * does.
 *
 * CONTRACT LAST RE-VERIFIED 2026-08-10 against the live docs
 * (code.visualstudio.com/docs/agent-customization/hooks and
 * /docs/agents/reference/hooks-reference): envelope fields, exit-2 blocking,
 * both file locations, the `chat.hookFilesLocations` setting (whose defaults
 * also read `.claude/settings.json`-format hooks), and the explicit Preview
 * marking ("configuration format and behavior might change") all confirmed
 * as described above. What is NOT verified: an end-to-end block inside a
 * live Copilot-subscribed VS Code agent session — that requires an
 * interactive editor with a Copilot entitlement and cannot run headlessly;
 * until someone performs it, this gate's live status is "contract-verified,
 * session-unverified" and the security matrix says so.
 *
 * Fail-safe analysis, stated rather than assumed: the shared JS gate
 * (`intuticGate`) extracts the target path and command from `tool_input` by
 * known field names, and an input whose fields it does not recognise extracts
 * to EMPTY strings — which match no rule, i.e. the gate degrades to ALLOW.
 * That is fine for a stable harness and wrong for a Preview one, so this
 * writer's stdin handler refuses (exit 2) any payload that carries neither
 * `tool_name` nor `tool_input`: if Copilot renames the envelope, the gate
 * fails closed and loudly instead of silently approving everything. A JSON
 * parse failure fails closed the same way.
 *
 * Historically github-copilot had an instructions file only
 * (`.github/copilot-instructions.md`) — advisory text, not enforcement. This
 * closes that gap for agent mode.
 *
 * @module
 */

import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import * as os from 'node:os'
import { createLogger } from '@intutic/logger'
import { newIso } from '@intutic/id'
import { emitJsGate, emitJsFailClosedPrelude } from './gateBody.js'

const log = createLogger('sync-github-copilot-hooks')

/**
 * The pre-tool gate script — receives Copilot's PreToolUse JSON on stdin,
 * exits 0 to allow or 2 to block.
 */
function buildHookScript(proxyUrl: string, workspaceRoot: string, workspaceId: string): string {
  const hookEventsLog = path.join(workspaceRoot, '.intutic', 'events', 'hook-events.jsonl')
  return `#!/usr/bin/env node
/**
 * Intutic GitHub Copilot (agent mode) governance gate.
 * Auto-generated by intutic sync-daemon. DO NOT EDIT.
 *
 * PREVIEW: VS Code agent hooks are a Preview feature and the stdin shape may
 * change. This gate refuses (exit 2) any payload it does not recognise —
 * fail closed, never silently allow.
 *
 * Proxy: ${proxyUrl}
 * Generated: ${newIso()}
 */
${emitJsFailClosedPrelude({ harness: 'github-copilot', contract: 'exit2' })}
const path = require('path');
const os = require('os');
const fs = require('fs');
const crypto = require('crypto');
const https = require('https');

// Runtime credentials
const _runtimeEnvPath = path.join(os.homedir(), '.intutic', 'env', 'runtime.env');
let _intuticHost = 'https://api.intutic.ai', _intuticKey = '', _intuticWsId = ${JSON.stringify(workspaceId)};
try {
  fs.readFileSync(_runtimeEnvPath, 'utf-8').split('\\n').forEach(line => {
    const eq = line.indexOf('='); if (eq < 0) return;
    const k = line.slice(0, eq).trim(), v = line.slice(eq + 1).trim();
    if (k === 'INTUTIC_HOST' && v) _intuticHost = v;
    if (k === 'INTUTIC_API_KEY' && v) _intuticKey = v;
    if (k === 'INTUTIC_WORKSPACE_ID' && v) _intuticWsId = v;
  });
} catch {}

${emitJsGate({ harness: 'github-copilot', contract: 'exit2' })}

let _intuticSessionId = '';
function logEvent(verdict, toolName, reason) {
  try {
    const ts = new Date().toISOString();
    const incidentId = crypto.createHash('sha1').update(ts + toolName + _intuticWsId).digest('hex').slice(0, 16);
    const entry = JSON.stringify({
      // Passed through, not collapsed to two values: the advisory tier emits
      // 'tool_flagged', and a ternary here silently recorded it as an allow.
      event: verdict,
      toolName, reason: reason || '',
      workspaceId: _intuticWsId,
      harnessType: 'github-copilot',
      timestamp: ts,
      incidentId,
      ...(_intuticSessionId ? { sessionId: _intuticSessionId } : {}),
    }) + '\\n';
    fs.appendFileSync(${JSON.stringify(hookEventsLog)}, entry, { flag: 'a' });
    if (_intuticKey) {
      try {
        const body = JSON.stringify({ events: [JSON.parse(entry)] });
        const urlObj = new URL('/api/v1/hook-events', _intuticHost);
        const mod = urlObj.protocol === 'https:' ? https : require('http');
        const req = mod.request({ hostname: urlObj.hostname, port: urlObj.port || 443, path: urlObj.pathname, method: 'POST', headers: { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body), 'Authorization': 'Bearer ' + _intuticKey } });
        req.on('error', () => { /* fire-and-forget */ });
        req.write(body); req.end();
      } catch { /* never crash the hook */ }
    }
  } catch { /* never crash the hook */ }
}

let raw = '';
process.stdin.on('data', (c) => { raw += c; });
process.stdin.on('end', () => {
  try {
    const ctx = JSON.parse(raw);
    _intuticSessionId = ctx.session_id || ctx.sessionId || '';

    // The Preview guard — the precedent the whole family now follows. The
    // shared gate extracts by known field names, and an envelope it does not
    // recognise extracts to empty strings — which match no rule and would
    // ALLOW. On a Preview harness whose format may shift, that is a silent
    // hole. The hand-rolled check that lived here became the shared
    // intuticGuardEnvelope in gateBody.ts (v5), so every JS writer refuses the
    // same envelopes with the same event; if Copilot renames the fields,
    // re-run intutic sync after upgrading.
    intuticGuardEnvelope(ctx, ['tool_name', 'toolName', 'tool_input', 'toolInput'], logEvent);

    const input = ctx.tool_input || ctx.toolInput || {};
    const toolName = ctx.tool_name || ctx.toolName || 'tool';

    // Every spelling any harness uses, matching the bash extractor. A field
    // name this list misses is a path guard that silently does not run — and
    // the caller controls which spelling it sends.
    const targetPath = input.path || input.file_path || input.filePath || input.file ||
      input.target || input.notebook_path || '';
    const command = input.command || input.cmd || input.script || '';

    intuticGate(toolName, targetPath, command, logEvent, _intuticWsId, input);

    // Allow
    logEvent('tool_allowed', toolName, '');
    process.exit(0);
  } catch (err) {
    // Fail CLOSED
    const errMsg = String(err);
    process.stderr.write('[Intutic Governance] Hook error (fail-closed): ' + errMsg + '\\n');
    logEvent('tool_blocked', 'unknown', errMsg);
    process.exit(2);
  }
});
`
}

/** The hook definition Copilot loads. One file wholly owned by Intutic — the
 *  `.github/hooks/` directory is per-file, so no merge is needed and user hook
 *  files are never touched. */
function buildHookConfig(hookScriptPath: string) {
  return {
    _comment:
      'Intutic governance hook — auto-generated. DO NOT EDIT. ' +
      'PREVIEW: VS Code agent hooks are a Preview feature; the gate fails closed if the format changes.',
    _lastSync: newIso(),
    hooks: {
      PreToolUse: [
        {
          // Catch-all: the gate decides from the arguments, so a tool name
          // nobody anticipated is still evaluated.
          matcher: '.*',
          hooks: [{ type: 'command', command: `node "${hookScriptPath}"` }],
        },
      ],
    },
  }
}

/**
 * Write the Copilot gate script and its hook definition at workspace and user
 * level.
 *
 * Safe to call repeatedly — uses atomic rename (`.intutic-tmp` → final path);
 * both hook definition files are wholly Intutic-owned, so rewriting them is
 * idempotent by construction.
 *
 * @param workspaceRoot - Absolute workspace root path.
 * @param proxyUrl      - Intutic proxy URL written into the gate header.
 * @param workspaceId   - Workspace ID embedded in every hook event payload.
 */
export async function writeGithubCopilotHooks(
  workspaceRoot: string,
  proxyUrl: string,
  workspaceId = '',
): Promise<void> {
  const hookScriptDir = path.join(workspaceRoot, '.intutic', 'hooks')
  await fs.mkdir(hookScriptDir, { recursive: true })
  await fs.mkdir(path.join(workspaceRoot, '.intutic', 'events'), { recursive: true })

  const hookScriptPath = path.join(hookScriptDir, 'github-copilot-check.js')
  const tmpScript = hookScriptPath + '.intutic-tmp'
  await fs.writeFile(tmpScript, buildHookScript(proxyUrl, workspaceRoot, workspaceId), 'utf-8')
  await fs.rename(tmpScript, hookScriptPath)
  await fs.chmod(hookScriptPath, 0o755)

  const config = buildHookConfig(hookScriptPath)

  // 1. Workspace-level: .github/hooks/intutic-governance.json
  const projectHooksDir = path.join(workspaceRoot, '.github', 'hooks')
  await fs.mkdir(projectHooksDir, { recursive: true })
  await atomicWriteJson(path.join(projectHooksDir, 'intutic-governance.json'), config)
  log.info(
    { action: 'github_copilot_hooks_written', level: 'workspace', path: projectHooksDir },
    'GitHub Copilot workspace-level hook written (Preview mechanism)',
  )

  // 2. User-level: ~/.copilot/hooks/intutic-governance.json
  const userHooksDir = path.join(os.homedir(), '.copilot', 'hooks')
  await fs.mkdir(userHooksDir, { recursive: true })
  await atomicWriteJson(path.join(userHooksDir, 'intutic-governance.json'), config)
  log.info(
    { action: 'github_copilot_hooks_written', level: 'user', path: userHooksDir },
    'GitHub Copilot user-level hook written (Preview mechanism)',
  )
}

async function atomicWriteJson(filePath: string, data: unknown): Promise<void> {
  const tmp = filePath + '.intutic-tmp'
  await fs.writeFile(tmp, JSON.stringify(data, null, 2) + '\n', 'utf-8')
  await fs.rename(tmp, filePath)
}
