/**
 * gooseHooks.ts — Goose PreToolUse governance plugin injection.
 *
 * Writes the Intutic governance plugin to the Goose plugin directory:
 *   ~/.agents/plugins/intutic-governance/hooks/hooks.json
 *   ~/.agents/plugins/intutic-governance/scripts/intutic-check.sh
 *
 * Also merges the Intutic proxy URL into ~/.config/goose/config.yaml.
 * After writing, calls gooseHardener to apply chmod 444 + immutable flags.
 *
 * LLD #14 — Phase 3 cross-harness defence
 * HLD §3.14 — Three-Tier Defense Cascade
 *
 * @module
 */

import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import * as os from 'node:os'
import { createLogger } from '@intutic/logger'
import { newIso } from '@intutic/id'
import { hardenGoosePlugin, unharden } from './gooseHardener.js'

const log = createLogger('sync-goose-hooks')

const PLUGIN_DIR = path.join(os.homedir(), '.agents', 'plugins', 'intutic-governance')
const GOOSE_CONFIG = path.join(os.homedir(), '.config', 'goose', 'config.yaml')

const PROTECTED_PATHS = [
  '.agents/plugins/intutic-governance',
  '.intutic/hooks',
  '.intutic/integrity.json',
  '.claude/settings.json',
  '.cursor/hooks.json',
  '.cline/hooks',
  '.openhands/hooks.json',
]

/**
 * Write Goose governance plugin and harden it.
 *
 * @param proxyUrl    - Intutic proxy URL written into the plugin script.
 * @param workspaceRoot - Absolute workspace root (for hook events log path).
 * @param workspaceId - Workspace ID embedded in hook event payloads.
 */
export async function writeGooseHooks(proxyUrl: string, workspaceRoot = os.homedir(), workspaceId = ''): Promise<void> {
  const hooksDir = path.join(PLUGIN_DIR, 'hooks')
  const scriptsDir = path.join(PLUGIN_DIR, 'scripts')
  await fs.mkdir(hooksDir, { recursive: true })
  await fs.mkdir(scriptsDir, { recursive: true })

  // ── hooks.json ──────────────────────────────────────────────────────
  const hooksConfig = {
    _comment: 'Intutic governance plugin — auto-generated. DO NOT EDIT.',
    _lastSync: newIso(),
    name: 'intutic-governance',
    version: '1.0.0',
    hooks: {
      PreToolUse: {
        command: path.join(scriptsDir, 'intutic-check.sh'),
        failClosed: true,
      },
      PostToolUse: {
        command: path.join(scriptsDir, 'intutic-check.sh --event post'),
        failClosed: false,
      },
    },
  }

  const hooksJsonPath = path.join(hooksDir, 'hooks.json')

  // Unharden before writing (in case we're refreshing an existing install)
  await unharden(hooksJsonPath)

  const tmpHooks = hooksJsonPath + '.intutic-tmp'
  await fs.writeFile(tmpHooks, JSON.stringify(hooksConfig, null, 2) + '\n', 'utf-8')
  await fs.rename(tmpHooks, hooksJsonPath)

  // ── intutic-check.sh ─────────────────────────────────────────────────
  const checkScriptPath = path.join(scriptsDir, 'intutic-check.sh')
  await unharden(checkScriptPath)

  const hookEventsLog = path.join(workspaceRoot, '.intutic', 'events', 'hook-events.jsonl')
  // Ensure events dir exists
  await fs.mkdir(path.join(workspaceRoot, '.intutic', 'events'), { recursive: true })

  const checkScript = `#!/usr/bin/env bash
# Intutic Goose PreToolUse governance gate.
# Auto-generated by intutic sync-daemon. DO NOT EDIT.
# Proxy: ${proxyUrl}
# Generated: ${newIso()}
set -euo pipefail

EVENT="\${1:-pre}"
INPUT="\$(cat)"
TOOL="$(echo "$INPUT" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('tool_name',''))" 2>/dev/null || true)"
TARGET="$(echo "$INPUT" | python3 -c "import sys,json; d=json.load(sys.stdin); i=d.get('tool_input',{}); print(i.get('path',i.get('file_path','')))" 2>/dev/null || true)"

HOOK_EVENTS_LOG=${JSON.stringify(hookEventsLog)}

# ── Runtime credentials (sourced from ~/.intutic/env/runtime.env) ────────────────────────
RUNTIME_ENV="$HOME/.intutic/env/runtime.env"
INTUITIC_HOST="https://api.intutic.ai"
INTUITIC_API_KEY=""
INTUITIC_WORKSPACE_ID=${JSON.stringify(workspaceId)}
[ -f "$RUNTIME_ENV" ] && source "$RUNTIME_ENV" 2>/dev/null || true

log_event() {
  local verdict="\$1" tool="\$2" reason="\$3"
  local ts; ts="\$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  local incident_id; incident_id="\$(printf '%s' "\${ts}\${tool}\${INTUTIC_WORKSPACE_ID}" | sha1sum 2>/dev/null | cut -c1-16 || echo \"\$(date +%s)\")"
  local entry="{\"event\":\"\${verdict}\",\"toolName\":\"\${tool}\",\"reason\":\"\${reason}\",\"workspaceId\":\"\${INTUTIC_WORKSPACE_ID}\",\"harnessType\":\"goose\",\"timestamp\":\"\${ts}\",\"incidentId\":\"\${incident_id}\"}"
  # Path B: reliable file append
  printf '%s\\n' "\$entry" >> "\$HOOK_EVENTS_LOG" 2>/dev/null || true
  # Path A: fire-and-forget HTTP (non-blocking, near-real-time)
  if [ -n "\$INTUTIC_API_KEY" ]; then
    curl -s -o /dev/null --max-time 3 -X POST \\
      -H "Content-Type: application/json" \\
      -H "Authorization: Bearer \$INTUTIC_API_KEY" \\
      -d "{\"events\":[\$entry]}" \\
      "\${INTUTIC_HOST}/api/v1/hook-events" & disown 2>/dev/null || true
  fi
}

PROTECTED_PATHS=(
  ".agents/plugins/intutic-governance"
  ".intutic/hooks"
  ".intutic/integrity.json"
  ".claude/settings.json"
  ".cursor/hooks.json"
  ".cline/hooks"
  ".openhands/hooks.json"
)

for p in "\${PROTECTED_PATHS[@]}"; do
  if echo "$TARGET" | grep -qF "$p"; then
    REASON="Attempt to modify governance-protected path \\"$TARGET\\""
    echo "[Intutic Governance] BLOCKED: $REASON" >&2
    log_event "tool_blocked" "\$TOOL" "\$REASON"
    exit 2
  fi
done

log_event "tool_allowed" "\$TOOL" ""
exit 0
`

  const tmpScript = checkScriptPath + '.intutic-tmp'
  await fs.writeFile(tmpScript, checkScript, 'utf-8')
  await fs.rename(tmpScript, checkScriptPath)
  await fs.chmod(checkScriptPath, 0o755)

  // Apply immutable flags after writing
  await hardenGoosePlugin(PLUGIN_DIR)

  log.info(
    { action: 'goose_plugin_written', pluginDir: PLUGIN_DIR },
    'Goose governance plugin written and hardened',
  )

  // ── Merge proxy URL into goose config.yaml ───────────────────────────
  await mergeGooseConfig(proxyUrl)
}

/**
 * Merge provider host URL into ~/.config/goose/config.yaml.
 */
async function mergeGooseConfig(proxyUrl: string): Promise<void> {
  let existing = ''
  try {
    existing = await fs.readFile(GOOSE_CONFIG, 'utf-8')
  } catch {
    existing = ''
  }

  // Inject or update provider.host
  // Goose config.yaml format: provider.host or OPENAI_HOST env var
  if (existing.includes('provider:')) {
    if (existing.includes('  host:')) {
      existing = existing.replace(/^\s*host:\s*.*/m, `  host: "${proxyUrl}"`)
    } else {
      existing = existing.replace(/^provider:/m, `provider:\n  host: "${proxyUrl}"`)
    }
  } else {
    existing += `\nprovider:\n  host: "${proxyUrl}"\n`
  }

  const tmpConfig = GOOSE_CONFIG + '.intutic-tmp'
  await fs.mkdir(path.dirname(GOOSE_CONFIG), { recursive: true })
  await fs.writeFile(tmpConfig, existing, 'utf-8')
  await fs.rename(tmpConfig, GOOSE_CONFIG)

  log.info({ action: 'goose_config_written', path: GOOSE_CONFIG }, 'Goose config.yaml updated with proxy host')
}
