/**
 * gooseHooksWriter.ts — Goose pre_tool_use native hook writer.
 *
 * Writes two artefacts:
 *   1. `~/.intutic/hooks/goose-pre-tool-use.sh` — bash gate script that
 *      sources runtime credentials, POSTs to the Intutic hook-gate endpoint,
 *      and exits 2 (block) or 0 (allow).
 *   2. `~/.config/goose/config.yaml` — adds `hooks.pre_tool_use` key if it
 *      is not already present (string operations only; no yaml dep needed).
 *
 * Fail-open semantics: if curl errors the script exits 0 so Goose continues.
 * On block, a JSONL event line is also appended to
 * `~/.intutic/events/hook-events.jsonl` for local audit.
 *
 * LLD #14 — Phase 4 WS-4C native hook script writers
 * HLD §3.14 — Three-Tier Defense Cascade (Tier 1 Native Gating)
 *
 * @module
 */

import * as node_fs from 'node:fs/promises'
import * as node_path from 'node:path'
import * as node_os from 'node:os'
import { createLogger } from '@intutic/logger'

const log = createLogger('sync-goose-hooks-writer')

const HOOKS_DIR = node_path.join(node_os.homedir(), '.intutic', 'hooks')
const EVENTS_DIR = node_path.join(node_os.homedir(), '.intutic', 'events')
const HOOK_SCRIPT = node_path.join(HOOKS_DIR, 'goose-pre-tool-use.sh')
const HOOK_EVENTS_LOG = node_path.join(EVENTS_DIR, 'hook-events.jsonl')
const GOOSE_CONFIG = node_path.join(node_os.homedir(), '.config', 'goose', 'config.yaml')

/**
 * Build the bash gate script content.
 *
 * Logic:
 *   1. Source ~/.intutic/env/runtime.env for credentials.
 *   2. Read full stdin JSON payload.
 *   3. POST to $INTUTIC_CONTROL_PLANE_URL/api/v1/hook-gate (10 s timeout).
 *   4. If curl fails → fail-open (exit 0).
 *   5. If response body contains `"allowed":false` → append JSONL event, exit 2.
 *   6. Otherwise → exit 0.
 */
function buildGooseHookScript(): string {
  return `#!/usr/bin/env bash
# Intutic Goose pre_tool_use governance gate.
# Auto-generated by intutic sync-daemon. DO NOT EDIT.
set -euo pipefail

RUNTIME_ENV="$HOME/.intutic/env/runtime.env"
HOOK_EVENTS_LOG=${JSON.stringify(HOOK_EVENTS_LOG)}
INTUTIC_CONTROL_PLANE_URL="https://api.intutic.ai"
INTUTIC_API_KEY=""
INTUTIC_WORKSPACE_ID=""

# Source runtime credentials (key rotation is automatic on next tool call)
[ -f "$RUNTIME_ENV" ] && source "$RUNTIME_ENV" 2>/dev/null || true

INPUT="$(cat)"
TOOL_NAME="$(echo "$INPUT" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('tool_name',''))" 2>/dev/null || true)"

# ── POST to hook-gate ─────────────────────────────────────────────────
GATE_URL="\${INTUTIC_CONTROL_PLANE_URL}/api/v1/hook-gate"
RESPONSE=""
if [ -n "$INTUTIC_API_KEY" ]; then
  RESPONSE="$(curl -s --max-time 10 -X POST \\
    -H "Content-Type: application/json" \\
    -H "Authorization: Bearer $INTUTIC_API_KEY" \\
    -d "$INPUT" \\
    "$GATE_URL" 2>/dev/null)" || true
fi

# Fail-open: empty response (curl error / no key) → allow
if [ -z "$RESPONSE" ]; then
  exit 0
fi

# Check decision
ALLOWED="$(echo "$RESPONSE" | python3 -c "import sys,json; d=json.load(sys.stdin); print(str(d.get('allowed', True)).lower())" 2>/dev/null || echo "true")"

if [ "$ALLOWED" = "false" ]; then
  REASON="$(echo "$RESPONSE" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('reason',''))" 2>/dev/null || true)"
  TS="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  INCIDENT_ID="$(printf '%s' "\${TS}\${TOOL_NAME}\${INTUTIC_WORKSPACE_ID}" | sha1sum 2>/dev/null | cut -c1-16 || echo "$(date +%s)")"
  ENTRY="{\\"event\\":\\"tool_blocked\\",\\"toolName\\":\\"\${TOOL_NAME}\\",\\"reason\\":\\"\${REASON}\\",\\"workspaceId\\":\\"\${INTUTIC_WORKSPACE_ID}\\",\\"harnessType\\":\\"goose\\",\\"timestamp\\":\\"\${TS}\\",\\"incidentId\\":\\"\${INCIDENT_ID}\\"}"
  mkdir -p "$(dirname "$HOOK_EVENTS_LOG")"
  printf '%s\\n' "$ENTRY" >> "$HOOK_EVENTS_LOG" 2>/dev/null || true
  echo "[Intutic Governance] BLOCKED: $REASON" >&2
  exit 2
fi

exit 0
`
}

/**
 * Merge `hooks.pre_tool_use` into Goose config.yaml using string operations.
 *
 * Reads the existing file (if any), checks if `pre_tool_use:` is already
 * present under a `hooks:` section, and adds it only if absent.
 * Creates the file (with a minimal `hooks:` block) if it does not exist.
 */
async function mergeGooseConfig(): Promise<void> {
  let existing = ''
  try {
    existing = await node_fs.readFile(GOOSE_CONFIG, 'utf-8')
  } catch {
    existing = ''
  }

  const hookLine = `  pre_tool_use: ${HOOK_SCRIPT}`

  // Already registered — nothing to do
  if (existing.includes('pre_tool_use:') && existing.includes(HOOK_SCRIPT)) {
    log.debug({ action: 'goose_config_noop', path: GOOSE_CONFIG }, 'Goose config already contains pre_tool_use hook')
    return
  }

  if (existing.includes('hooks:')) {
    // hooks: block exists — insert our line after the `hooks:` line
    existing = existing.replace(/^hooks:/m, `hooks:\n${hookLine}`)
  } else {
    // No hooks: block — append
    existing = existing.trimEnd() + `\nhooks:\n${hookLine}\n`
  }

  await node_fs.mkdir(node_path.dirname(GOOSE_CONFIG), { recursive: true })
  const tmp = GOOSE_CONFIG + '.intutic-tmp'
  await node_fs.writeFile(tmp, existing, 'utf-8')
  await node_fs.rename(tmp, GOOSE_CONFIG)

  log.info(
    { action: 'goose_config_written', path: GOOSE_CONFIG },
    'Goose config.yaml updated with pre_tool_use hook',
  )
}

/**
 * Write the Goose pre_tool_use hook script and register it in config.yaml.
 *
 * @param workspaceRoot - Absolute path to the workspace root (unused directly;
 *   included for API symmetry with other hook writers).
 */
export async function writeGooseHooks(workspaceRoot: string): Promise<void> {
  // Ensure target directories exist
  await node_fs.mkdir(HOOKS_DIR, { recursive: true })
  await node_fs.mkdir(EVENTS_DIR, { recursive: true })

  // Write hook script atomically
  const tmp = HOOK_SCRIPT + '.intutic-tmp'
  await node_fs.writeFile(tmp, buildGooseHookScript(), 'utf-8')
  await node_fs.rename(tmp, HOOK_SCRIPT)
  await node_fs.chmod(HOOK_SCRIPT, 0o755)

  log.info(
    { action: 'goose_hook_script_written', path: HOOK_SCRIPT },
    'Goose pre_tool_use hook script written',
  )

  // Register in config.yaml
  await mergeGooseConfig()

  log.info(
    { action: 'goose_hooks_done', workspaceRoot },
    'Goose native hooks written successfully',
  )
}
