/**
 * gooseHooks.ts — Goose PreToolUse governance plugin injection.
 *
 * Writes the Intutic governance plugin to the Goose plugin directory:
 *   ~/.agents/plugins/intutic-governance/hooks/hooks.json
 *   ~/.agents/plugins/intutic-governance/scripts/intutic-check.sh
 *
 * Also merges the Intutic proxy URL into ~/.config/goose/config.yaml.
 * After writing, calls gooseHardener to apply chmod 444 + immutable flags.
 *
 * LLD #14 — Phase 3 cross-harness defence
 * HLD §3.14 — Three-Tier Defense Cascade
 *
 * @module
 */

import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import * as os from 'node:os'
import { createLogger } from '@intutic/logger'
import { keepOriginal, noteWritten } from '../disconnect/originals.js'
import { newIso } from '@intutic/id'
import { hardenGoosePlugin, unharden } from './gooseHardener.js'
import { emitShellGate, SHELL_EXTRACT, SHELL_FAIL_CLOSED, REVIEW_REQUESTS_BASENAME } from './gateBody.js'
import { parseDocument, isMap, isScalar } from 'yaml'

const log = createLogger('sync-goose-hooks')

const PLUGIN_DIR = path.join(os.homedir(), '.agents', 'plugins', 'intutic-governance')
const GOOSE_CONFIG = path.join(os.homedir(), '.config', 'goose', 'config.yaml')

/**
 * Write Goose governance plugin and harden it.
 *
 * @param proxyUrl    - Intutic proxy URL written into the plugin script.
 * @param workspaceRoot - Absolute workspace root (for hook events log path).
 * @param workspaceId - Workspace ID embedded in hook event payloads.
 */
export async function writeGooseHooks(proxyUrl: string, workspaceRoot = os.homedir(), workspaceId = ''): Promise<void> {
  const hooksDir = path.join(PLUGIN_DIR, 'hooks')
  const scriptsDir = path.join(PLUGIN_DIR, 'scripts')
  await keepOriginal(path.join(hooksDir, 'hooks.json'), workspaceRoot)
  await keepOriginal(path.join(scriptsDir, 'intutic-check.sh'), workspaceRoot)
  await fs.mkdir(hooksDir, { recursive: true })
  await fs.mkdir(scriptsDir, { recursive: true })

  // ── hooks.json ──────────────────────────────────────────────────────
  const hooksConfig = {
    _comment: 'Intutic governance plugin — auto-generated. DO NOT EDIT.',
    _lastSync: newIso(),
    name: 'intutic-governance',
    version: '1.0.0',
    hooks: {
      PreToolUse: {
        command: path.join(scriptsDir, 'intutic-check.sh'),
        failClosed: true,
      },
      PostToolUse: {
        command: path.join(scriptsDir, 'intutic-check.sh --event post'),
        failClosed: false,
      },
    },
  }

  const hooksJsonPath = path.join(hooksDir, 'hooks.json')

  // Unharden before writing (in case we're refreshing an existing install)
  await unharden(hooksJsonPath)

  const hooksJson = JSON.stringify(hooksConfig, null, 2) + '\n'
  const tmpHooks = hooksJsonPath + '.intutic-tmp'
  await fs.writeFile(tmpHooks, hooksJson, 'utf-8')
  await fs.rename(tmpHooks, hooksJsonPath)
  await noteWritten(hooksJsonPath, workspaceRoot, hooksJson)

  // ── intutic-check.sh ─────────────────────────────────────────────────
  const checkScriptPath = path.join(scriptsDir, 'intutic-check.sh')
  await unharden(checkScriptPath)

  const hookEventsLog = path.join(workspaceRoot, '.intutic', 'events', 'hook-events.jsonl')
  // Ensure events dir exists
  await fs.mkdir(path.join(workspaceRoot, '.intutic', 'events'), { recursive: true })

  const checkScript = `#!/usr/bin/env bash
# Intutic Goose PreToolUse governance gate.
# Auto-generated by intutic sync-daemon. DO NOT EDIT.
# Proxy: ${proxyUrl}
# Generated: ${newIso()}
set -euo pipefail
${SHELL_FAIL_CLOSED}
EVENT="\${1:-pre}"
INPUT="\$(cat)"
${SHELL_EXTRACT}

HOOK_EVENTS_LOG=${JSON.stringify(hookEventsLog)}

# ── Runtime credentials (sourced from ~/.intutic/env/runtime.env) ────────────────────────
# These are defaults, and they are also the only thing standing between
# \`set -u\` and a fatal unbound-variable error: log_event reads all three, so on
# a machine with no runtime.env to source, an unset name kills the gate before
# it can exit 2. Spelling matters — INTUTIC_, never INTUITIC_.
RUNTIME_ENV="$HOME/.intutic/env/runtime.env"
INTUTIC_HOST="https://api.intutic.ai"
INTUTIC_API_KEY=""
INTUTIC_WORKSPACE_ID=${JSON.stringify(workspaceId)}
[ -f "$RUNTIME_ENV" ] && source "$RUNTIME_ENV" 2>/dev/null || true

log_event() {
  local verdict="\$1" tool="\$2" reason="\$3"
  # \`tool\` and \`reason\` carry agent-controlled text — the tool name, and the
  # target path quoted into the block reason — and both are spliced into the
  # JSON string below. Escape first: one unescaped quote yields a line
  # JSON.parse rejects, and drainHookEvents drops malformed lines then wipes the
  # log on a successful drain, so the record of a block is destroyed rather than
  # delayed. A crafted path could otherwise close the string and forge fields.
  tool="\${tool//\\\\/\\\\\\\\}";     tool="\${tool//\\"/\\\\\\"}"
  reason="\${reason//\\\\/\\\\\\\\}"; reason="\${reason//\\"/\\\\\\"}"
  # Every C0 control character, not just newline and carriage return. JSON
  # forbids all of U+0000-U+001F unescaped, so a plain TAB in a filename — no
  # adversary required — was still enough to produce a line JSON.parse rejects.
  # (NUL cannot appear in a bash variable, so the range starts at \\x01.)
  tool="\${tool//[\$'\\x01'-\$'\\x1f']/ }"; reason="\${reason//[\$'\\x01'-\$'\\x1f']/ }"
  # The workspace id is spliced into the same JSON string. It comes from
  # runtime.env on disk rather than from the agent, so it is lower risk — but a
  # value with a quote in it breaks every audit line the same way, and "lower
  # risk" is not "cannot happen" for a file the operator edits by hand.
  local ws="\${INTUTIC_WORKSPACE_ID}"
  ws="\${ws//\\\\/\\\\\\\\}"; ws="\${ws//\\"/\\\\\\"}"; ws="\${ws//[\$'\\x01'-\$'\\x1f']/ }"
  local ts; ts="\$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  local incident_id; incident_id="\$(printf '%s' "\${ts}\${tool}\${INTUTIC_WORKSPACE_ID}" | sha1sum 2>/dev/null | cut -c1-16 || echo \"\$(date +%s)\")"
  local entry="{\\"event\\":\\"\${verdict}\\",\\"toolName\\":\\"\${tool}\\",\\"reason\\":\\"\${reason}\\",\\"workspaceId\\":\\"\${ws}\\",\\"harnessType\\":\\"goose\\",\\"timestamp\\":\\"\${ts}\\",\\"incidentId\\":\\"\${incident_id}\\"}"
  # Path B: reliable file append
  printf '%s\\n' "\$entry" >> "\$HOOK_EVENTS_LOG" 2>/dev/null || true
  # Path A: fire-and-forget HTTP (non-blocking, near-real-time)
  if [ -n "\$INTUTIC_API_KEY" ]; then
    curl -s -o /dev/null --max-time 3 -X POST \\
      -H "Content-Type: application/json" \\
      -H "Authorization: Bearer \$INTUTIC_API_KEY" \\
      -d "{\\"events\\":[\$entry]}" \\
      "\${INTUTIC_HOST}/api/v1/hook-events" & disown 2>/dev/null || true
  fi
}

${emitShellGate({ harness: 'goose', reviewRequestFile: path.join(workspaceRoot, '.intutic', 'events', REVIEW_REQUESTS_BASENAME) })}

log_event "tool_allowed" "\$TOOL" ""
exit 0
`

  const tmpScript = checkScriptPath + '.intutic-tmp'
  await fs.writeFile(tmpScript, checkScript, 'utf-8')
  await fs.rename(tmpScript, checkScriptPath)
  await fs.chmod(checkScriptPath, 0o755)
  await noteWritten(checkScriptPath, workspaceRoot, checkScript)

  // Apply immutable flags after writing
  await hardenGoosePlugin(PLUGIN_DIR)

  log.info(
    { action: 'goose_plugin_written', pluginDir: PLUGIN_DIR },
    'Goose governance plugin written and hardened',
  )

  // ── Merge proxy URL into goose config.yaml ───────────────────────────
  await mergeGooseConfig(proxyUrl)
}

/**
 * Set Intutic's two keys in goose's `config.yaml` text: `provider.host` (the
 * proxy) and `hooks.pre_tool_use` (the gate script). Edited through the
 * `yaml` document model, so every other key, comment and list is kept. A text
 * replace of the first `host:` line used to rewrite whichever key of that name
 * came first, such as an extension's or an MCP server's.
 *
 * An empty `proxyUrl` leaves `provider.host` alone: the settings guard
 * re-runs this writer to restore the plugin without a URL to hand.
 *
 * Returns `null`, to leave the file untouched, when the text is not YAML, is
 * not a mapping, or holds `provider` or `hooks` as something other than a
 * mapping.
 */
export function mergeGooseConfigYaml(raw: string, proxyUrl: string, hookScript: string): string | null {
  const doc = parseDocument(raw)
  if (doc.errors.length > 0) return null
  if (doc.contents !== null && !isMap(doc.contents)) return null
  for (const key of ['provider', 'hooks']) {
    const node = doc.get(key, true)
    if (node === undefined || isMap(node)) continue
    // `provider:` with no value: replaced by the mapping below.
    if (isScalar(node) && node.value === null) doc.delete(key)
    else return null
  }
  if (proxyUrl) doc.setIn(['provider', 'host'], proxyUrl)
  doc.setIn(['hooks', 'pre_tool_use'], hookScript)
  return doc.toString()
}

/**
 * Merge the provider host **and** the `hooks.pre_tool_use` registration into
 * `~/.config/goose/config.yaml`.
 *
 * The hook registration used to live in a second module, `gooseHooksWriter.ts`,
 * which wrote its own gate script and registered *that* one here — so goose had
 * two co-installed gates with contradictory models: this one, which enforces
 * locally and fails closed, and that one, which POSTed to the control plane and
 * failed open. Absorbing the registration here settles it: both mechanisms
 * name the same script.
 */
async function mergeGooseConfig(proxyUrl: string): Promise<void> {
  let raw = ''
  try {
    raw = await fs.readFile(GOOSE_CONFIG, 'utf-8')
  } catch {
    // No config.yaml yet (first run) or unreadable: written fresh below.
  }

  const existing = mergeGooseConfigYaml(raw, proxyUrl, path.join(PLUGIN_DIR, 'scripts', 'intutic-check.sh'))
  if (existing === null) {
    log.warn({ action: 'goose_config_merge_skipped', path: GOOSE_CONFIG }, `${GOOSE_CONFIG} is not a YAML mapping Intutic can merge into — left untouched`)
    return
  }
  if (existing === raw) return

  const tmpConfig = GOOSE_CONFIG + '.intutic-tmp'
  await keepOriginal(GOOSE_CONFIG, os.homedir())
  await fs.mkdir(path.dirname(GOOSE_CONFIG), { recursive: true })
  await fs.writeFile(tmpConfig, existing, 'utf-8')
  await fs.rename(tmpConfig, GOOSE_CONFIG)

  log.info({ action: 'goose_config_written', path: GOOSE_CONFIG }, 'Goose config.yaml updated with proxy host')
}
