/**
 * hermesHooks.ts — Hermes AI agent governance hook injection.
 *
 * Hermes is a skills-based AI agent that reads `~/.hermes/config.yaml`
 * for configuration. Hook commands are registered under `hooks.preToolUse`.
 * This module:
 *
 * 1. YAML-safe-merges `~/.hermes/config.yaml` to register the hook command.
 * 2. Writes `~/.intutic/hooks/hermes-check.sh` — dual-path bash governance hook.
 * 3. Writes `~/.hermes/skills/intutic-governance/SKILL.md` — governance skill.
 * 4. Writes `.intutic/env/hermes.env` — env snippet for IDE/shell integration.
 *
 * WS-C1 — Hermes harness (Phase 3 cross-harness defence)
 * LLD #14 — Phase 3 cross-harness defence (Gap 3)
 * HLD §3.14 — Three-Tier Defense Cascade (Tier 1 Native Gating)
 *
 * @module
 */

import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import * as os from 'node:os'
import { createLogger } from '@intutic/logger'
import { newIso } from '@intutic/id'

const log = createLogger('sync-hermes-hooks')

/** Path to the Hermes global config file. */
const HERMES_CONFIG = path.join(os.homedir(), '.hermes', 'config.yaml')

/** Governance-sensitive paths that the hook gate protects. */
const PROTECTED_PATHS = [
  '.gemini/settings.json',
  '.intutic/hooks',
  '.intutic/integrity.json',
  '.intutic/events',
  '.claude/settings.json',
  '.cursor/hooks.json',
  '.codeium/windsurf/hooks.json',
  '.cline/hooks',
  '.agents/plugins/intutic-governance',
  '.openhands/hooks.json',
  '.hermes/config.yaml',
  '.hermes/skills/intutic-governance',
]

// ─── Bash hook script template ────────────────────────────────────────────────

function buildHermesCheckScript(
  proxyUrl: string,
  workspaceRoot: string,
  workspaceId: string,
): string {
  const hookEventsLog = path.join(workspaceRoot, '.intutic', 'events', 'hook-events.jsonl')
  const runtimeEnv = path.join(os.homedir(), '.intutic', 'env', 'runtime.env')
  return `#!/usr/bin/env bash
# Intutic Hermes PreToolUse governance gate.
# Auto-generated by intutic sync-daemon. DO NOT EDIT.
# Proxy: ${proxyUrl}
# Generated: ${newIso()}
# Workspace: ${workspaceId}
set -euo pipefail

# Source runtime credentials (never embedded in this file)
if [ -f "${runtimeEnv}" ]; then
  # shellcheck disable=SC1090
  source "${runtimeEnv}"
fi

INTUTIC_HOST="\${INTUTIC_HOST:-https://api.intutic.ai}"
INTUTIC_API_KEY="\${INTUTIC_API_KEY:-}"
INTUTIC_WORKSPACE_ID="\${INTUTIC_WORKSPACE_ID:-${workspaceId}}"

INPUT="$(cat)"
TOOL_NAME="$(echo "$INPUT" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('tool_name',''))" 2>/dev/null || true)"
TARGET_PATH="$(echo "$INPUT" | python3 -c "import sys,json; d=json.load(sys.stdin); i=d.get('tool_input',{}); print(i.get('path',i.get('file_path','')))" 2>/dev/null || true)"
COMMAND="$(echo "$INPUT" | python3 -c "import sys,json; d=json.load(sys.stdin); i=d.get('tool_input',{}); print(i.get('command',i.get('cmd','')))" 2>/dev/null || true)"

HOOK_EVENTS_LOG=${JSON.stringify(hookEventsLog)}

log_event() {
  local verdict="\$1" tool="\$2" reason="\$3"
  local ts; ts="\$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  # incidentId = sha1(timestamp + toolName + workspaceId).slice(0,16)
  local incident_id; incident_id="\$(echo -n \"\${ts}\${tool}\${INTUTIC_WORKSPACE_ID}\" | sha1sum | cut -c1-16)"
  local entry="{\\\"event\\\":\\\"toolGovernance\\\",\\\"verdict\\\":\\\"\${verdict}\\\",\\\"toolName\\\":\\\"\${tool}\\\",\\\"reason\\\":\\\"\${reason}\\\",\\\"workspaceId\\\":\\\"\${INTUTIC_WORKSPACE_ID}\\\",\\\"harnessType\\\":\\\"hermes\\\",\\\"incidentId\\\":\\\"\${incident_id}\\\",\\\"timestamp\\\":\\\"\${ts}\\\"}"
  # Path B: reliable file append (sync-daemon drains on FSEvents change)
  printf '%s\\n' "\$entry" >> "\$HOOK_EVENTS_LOG" 2>/dev/null || true
  # Path A: fire-and-forget HTTP POST (near-real-time dashboard, non-blocking)
  if [ -n "\$INTUTIC_API_KEY" ]; then
    curl -sf -X POST "\${INTUTIC_HOST}/api/v1/hook-events" \\
      -H "Content-Type: application/json" \\
      -H "Authorization: Bearer \${INTUTIC_API_KEY}" \\
      -d "{\\\"events\\\":[\$entry]}" \\
      --max-time 5 >/dev/null 2>&1 &
  fi
}

PROTECTED_PATHS=(
${PROTECTED_PATHS.map((p) => `  "${p}"`).join('\n')}
)

# 1. Protected-path guard
for p in "\${PROTECTED_PATHS[@]}"; do
  if echo "$TARGET_PATH" | grep -qF "$p"; then
    REASON="Attempt to modify governance-protected path \\"$TARGET_PATH\\""
    echo "[Intutic Governance] BLOCKED: $REASON" >&2
    log_event "tool_blocked" "$TOOL_NAME" "$REASON"
    exit 2
  fi
done

# 2. Bash/shell command guard — block governance bypass patterns
if [ -n "$COMMAND" ]; then
  BYPASS_PATTERNS=(
    "chflags nouchg"
    "chattr -i"
    "rm -rf .intutic"
    "rm -rf .hermes/config"
    "HERMES_PRE_TOOL_HOOK="
    "rm -rf .gemini/settings"
  )
  for pattern in "\${BYPASS_PATTERNS[@]}"; do
    if echo "$COMMAND" | grep -qF "$pattern"; then
      REASON="Shell command matches governance bypass pattern: \\"$pattern\\""
      echo "[Intutic Governance] BLOCKED: $REASON" >&2
      log_event "tool_blocked" "$TOOL_NAME" "$REASON"
      exit 2
    fi
  done
fi

log_event "tool_allowed" "$TOOL_NAME" ""
exit 0
`
}

// ─── YAML merge helpers ───────────────────────────────────────────────────────

/**
 * YAML-safe merge of the Hermes config.
 *
 * Strategy (no YAML library — pure string manipulation):
 * - If file doesn't exist: write fresh with just the hooks block.
 * - If file exists and already contains `preToolUse:`: replace the command line.
 * - If file exists but has no `preToolUse:`: append the hooks block.
 * - If file has `hooks:` but no `preToolUse:`: insert inside existing hooks section.
 */
async function mergeHermesConfig(hookScriptPath: string): Promise<void> {
  const hooksBlock = [
    'hooks:',
    '  preToolUse:',
    `    command: ${hookScriptPath}`,
  ].join('\n')

  let existing: string | null = null
  try {
    existing = await fs.readFile(HERMES_CONFIG, 'utf-8')
  } catch {
    // File doesn't exist — write fresh
  }

  let merged: string

  if (existing === null) {
    // Fresh write
    merged = hooksBlock + '\n'
  } else if (/^\s*preToolUse:/m.test(existing)) {
    // Replace the existing command line under preToolUse:
    merged = existing.replace(/^(\s*command:\s*).*$/m, `$1${hookScriptPath}`)
  } else if (/^hooks:/m.test(existing)) {
    // hooks: block exists but no preToolUse: — insert inside hooks section
    merged = existing.replace(
      /^(hooks:\s*)$/m,
      `$1\n  preToolUse:\n    command: ${hookScriptPath}`,
    )
  } else {
    // No hooks: block at all — append
    merged = existing.trimEnd() + '\n\n' + hooksBlock + '\n'
  }

  const tmpPath = HERMES_CONFIG + '.intutic-tmp'
  await fs.writeFile(tmpPath, merged, 'utf-8')
  await fs.rename(tmpPath, HERMES_CONFIG)
}

// ─── Governance skill template ────────────────────────────────────────────────

function buildGovernanceSkill(proxyUrl: string): string {
  return `---
name: intutic-governance
description: Intutic governance awareness. Always check compliance before tool calls.
triggers:
  - before any tool call
  - before any file write
  - before any shell command
---

# Intutic Governance Policy

Before every tool call, you MUST verify compliance with workspace SOPs.
A pre-tool-use hook (\`~/.intutic/hooks/hermes-check.sh\`) enforces these rules automatically.

If a tool call is blocked, do NOT attempt to circumvent the governance gate.
To update policy, use the Intutic control plane at \`${proxyUrl}\`.
`
}

// ─── Main export ──────────────────────────────────────────────────────────────

/**
 * Write the Hermes governance hook script, merge config, and write the
 * governance skill for the Hermes AI agent.
 *
 * Safe to call repeatedly — uses atomic rename so partial writes never
 * leave a corrupt state.
 *
 * @param workspaceRoot - Absolute workspace root path.
 * @param proxyUrl      - Intutic proxy URL written into hook headers / skill.
 * @param workspaceId   - Workspace ID embedded in every hook event payload.
 */
export async function writeHermesHooks(
  workspaceRoot: string,
  proxyUrl: string,
  workspaceId = '',
): Promise<void> {
  // ── 1. Ensure directories ──────────────────────────────────────────────────

  const globalHookDir = path.join(os.homedir(), '.intutic', 'hooks')
  const hookEventsDir = path.join(workspaceRoot, '.intutic', 'events')
  const envDir = path.join(workspaceRoot, '.intutic', 'env')
  const hermesDir = path.join(os.homedir(), '.hermes')
  const skillsDir = path.join(hermesDir, 'skills', 'intutic-governance')

  await Promise.all([
    fs.mkdir(globalHookDir, { recursive: true }),
    fs.mkdir(hookEventsDir, { recursive: true }),
    fs.mkdir(envDir, { recursive: true }),
    fs.mkdir(hermesDir, { recursive: true }),
    fs.mkdir(skillsDir, { recursive: true }),
  ])

  // ── 2. Write bash hook script ──────────────────────────────────────────────

  const hookScriptPath = path.join(globalHookDir, 'hermes-check.sh')
  const tmpScript = hookScriptPath + '.intutic-tmp'
  await fs.writeFile(tmpScript, buildHermesCheckScript(proxyUrl, workspaceRoot, workspaceId), 'utf-8')
  await fs.rename(tmpScript, hookScriptPath)
  await fs.chmod(hookScriptPath, 0o755)

  log.info({ action: 'hermes_hook_script_written', path: hookScriptPath }, 'Hermes hook script written')

  // ── 3. YAML-safe merge into ~/.hermes/config.yaml ─────────────────────────

  await mergeHermesConfig(hookScriptPath)

  log.info(
    { action: 'hermes_config_merged', path: HERMES_CONFIG },
    'Merged Intutic hook into ~/.hermes/config.yaml',
  )

  // ── 4. Write governance skill ──────────────────────────────────────────────

  const skillPath = path.join(skillsDir, 'SKILL.md')
  const tmpSkill = skillPath + '.intutic-tmp'
  await fs.writeFile(tmpSkill, buildGovernanceSkill(proxyUrl), 'utf-8')
  await fs.rename(tmpSkill, skillPath)

  log.info(
    { action: 'hermes_skill_written', path: skillPath },
    'Hermes governance skill written',
  )

  // ── 5. Write env snippet ───────────────────────────────────────────────────

  const envSnippet = [
    `# Intutic Hermes governance env`,
    `INTUITIC_HERMES_HOOK=~/.intutic/hooks/hermes-check.sh`,
    `INTUITIC_HERMES_CONFIG=~/.hermes/config.yaml`,
  ].join('\n') + '\n'

  const envFilePath = path.join(envDir, 'hermes.env')
  const tmpEnv = envFilePath + '.intutic-tmp'
  await fs.writeFile(tmpEnv, envSnippet, 'utf-8')
  await fs.rename(tmpEnv, envFilePath)

  log.info(
    { action: 'hermes_env_written', path: envFilePath },
    'Hermes env snippet written',
  )
}
