/**
 * hermesHooks.ts — Hermes AI agent governance hook injection.
 *
 * Hermes is a skills-based AI agent that reads `~/.hermes/config.yaml`
 * for configuration. Hook commands are registered under `hooks.preToolUse`.
 * This module:
 *
 * 1. YAML-safe-merges `~/.hermes/config.yaml` to register the hook command.
 * 2. Writes `~/.intutic/hooks/hermes-check.sh` — dual-path bash governance hook.
 * 3. Writes `~/.hermes/skills/intutic-governance/SKILL.md` — governance skill.
 * 4. Writes `.intutic/env/hermes.env` — env snippet for IDE/shell integration.
 *
 * WS-C1 — Hermes harness (Phase 3 cross-harness defence)
 * LLD #14 — Phase 3 cross-harness defence (Gap 3)
 * HLD §3.14 — Three-Tier Defense Cascade (Tier 1 Native Gating)
 *
 * @module
 */

import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import * as os from 'node:os'
import { createLogger } from '@intutic/logger'
import { newIso } from '@intutic/id'
import { emitShellGate, SHELL_EXTRACT, SHELL_FAIL_CLOSED } from './gateBody.js'

const log = createLogger('sync-hermes-hooks')

/** Path to the Hermes global config file. */
const HERMES_CONFIG = path.join(os.homedir(), '.hermes', 'config.yaml')

/** Governance-sensitive paths that the hook gate protects. */
// ─── Bash hook script template ────────────────────────────────────────────────

function buildHermesCheckScript(
  proxyUrl: string,
  workspaceRoot: string,
  workspaceId: string,
): string {
  const hookEventsLog = path.join(workspaceRoot, '.intutic', 'events', 'hook-events.jsonl')
  const runtimeEnv = path.join(os.homedir(), '.intutic', 'env', 'runtime.env')
  return `#!/usr/bin/env bash
# Intutic Hermes PreToolUse governance gate.
# Auto-generated by intutic sync-daemon. DO NOT EDIT.
# Proxy: ${proxyUrl}
# Generated: ${newIso()}
# Workspace: ${workspaceId}
set -euo pipefail
${SHELL_FAIL_CLOSED}
# Source runtime credentials (never embedded in this file)
if [ -f "${runtimeEnv}" ]; then
  # shellcheck disable=SC1090
  source "${runtimeEnv}"
fi

INTUTIC_HOST="\${INTUTIC_HOST:-https://api.intutic.ai}"
INTUTIC_API_KEY="\${INTUTIC_API_KEY:-}"
INTUTIC_WORKSPACE_ID="\${INTUTIC_WORKSPACE_ID:-${workspaceId}}"

INPUT="$(cat)"
${SHELL_EXTRACT}

HOOK_EVENTS_LOG=${JSON.stringify(hookEventsLog)}

log_event() {
  local verdict="\$1" tool="\$2" reason="\$3"
  # \`tool\` and \`reason\` carry agent-controlled text — the tool name, and the
  # target path quoted into the block reason — and both are spliced into the
  # JSON string below. Escape first: one unescaped quote yields a line
  # JSON.parse rejects, and drainHookEvents drops malformed lines then wipes the
  # log on a successful drain, so the record of a block is destroyed rather than
  # delayed. A crafted path could otherwise close the string and forge fields.
  tool="\${tool//\\\\/\\\\\\\\}";     tool="\${tool//\\"/\\\\\\"}"
  reason="\${reason//\\\\/\\\\\\\\}"; reason="\${reason//\\"/\\\\\\"}"
  # Every C0 control character, not just newline and carriage return. JSON
  # forbids all of U+0000-U+001F unescaped, so a plain TAB in a filename — no
  # adversary required — was still enough to produce a line JSON.parse rejects.
  # (NUL cannot appear in a bash variable, so the range starts at \\x01.)
  tool="\${tool//[\$'\\x01'-\$'\\x1f']/ }"; reason="\${reason//[\$'\\x01'-\$'\\x1f']/ }"
  # The workspace id is spliced into the same JSON string. It comes from
  # runtime.env on disk rather than from the agent, so it is lower risk — but a
  # value with a quote in it breaks every audit line the same way, and "lower
  # risk" is not "cannot happen" for a file the operator edits by hand.
  local ws="\${INTUTIC_WORKSPACE_ID}"
  ws="\${ws//\\\\/\\\\\\\\}"; ws="\${ws//\\"/\\\\\\"}"; ws="\${ws//[\$'\\x01'-\$'\\x1f']/ }"
  local ts; ts="\$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  # incidentId = sha1(timestamp + toolName + workspaceId).slice(0,16)
  local incident_id; incident_id="\$(echo -n \"\${ts}\${tool}\${INTUTIC_WORKSPACE_ID}\" | sha1sum | cut -c1-16)"
  local entry="{\\\"event\\\":\\\"\${verdict}\\\",\\\"toolName\\\":\\\"\${tool}\\\",\\\"reason\\\":\\\"\${reason}\\\",\\\"workspaceId\\\":\\\"\${INTUTIC_WORKSPACE_ID}\\\",\\\"harnessType\\\":\\\"hermes\\\",\\\"incidentId\\\":\\\"\${incident_id}\\\",\\\"timestamp\\\":\\\"\${ts}\\\"}"
  # Path B: reliable file append (sync-daemon drains on FSEvents change)
  printf '%s\\n' "\$entry" >> "\$HOOK_EVENTS_LOG" 2>/dev/null || true
  # Path A: fire-and-forget HTTP POST (near-real-time dashboard, non-blocking)
  if [ -n "\$INTUTIC_API_KEY" ]; then
    curl -sf -X POST "\${INTUTIC_HOST}/api/v1/hook-events" \\
      -H "Content-Type: application/json" \\
      -H "Authorization: Bearer \${INTUTIC_API_KEY}" \\
      -d "{\\\"events\\\":[\$entry]}" \\
      --max-time 5 >/dev/null 2>&1 &
  fi
}

${emitShellGate({ harness: "hermes" })}
log_event "tool_allowed" "$TOOL_NAME" ""
exit 0
`
}

// ─── YAML merge helpers ───────────────────────────────────────────────────────

/**
 * YAML-safe merge of the Hermes config.
 *
 * Strategy (no YAML library — pure string manipulation):
 * - If file doesn't exist: write fresh with just the hooks block.
 * - If file exists and already contains `preToolUse:`: replace the command line.
 * - If file exists but has no `preToolUse:`: append the hooks block.
 * - If file has `hooks:` but no `preToolUse:`: insert inside existing hooks section.
 */
async function mergeHermesConfig(hookScriptPath: string): Promise<void> {
  const hooksBlock = [
    'hooks:',
    '  preToolUse:',
    `    command: ${hookScriptPath}`,
  ].join('\n')

  let existing: string | null = null
  try {
    existing = await fs.readFile(HERMES_CONFIG, 'utf-8')
  } catch {
    // File doesn't exist — write fresh
  }

  let merged: string

  if (existing === null) {
    // Fresh write
    merged = hooksBlock + '\n'
  } else if (/^\s*preToolUse:/m.test(existing)) {
    // Replace the existing command line under preToolUse:
    merged = existing.replace(/^(\s*command:\s*).*$/m, `$1${hookScriptPath}`)
  } else if (/^hooks:/m.test(existing)) {
    // hooks: block exists but no preToolUse: — insert inside hooks section
    merged = existing.replace(
      /^(hooks:\s*)$/m,
      `$1\n  preToolUse:\n    command: ${hookScriptPath}`,
    )
  } else {
    // No hooks: block at all — append
    merged = existing.trimEnd() + '\n\n' + hooksBlock + '\n'
  }

  const tmpPath = HERMES_CONFIG + '.intutic-tmp'
  await fs.writeFile(tmpPath, merged, 'utf-8')
  await fs.rename(tmpPath, HERMES_CONFIG)
}

// ─── Governance skill template ────────────────────────────────────────────────

function buildGovernanceSkill(proxyUrl: string): string {
  return `---
name: intutic-governance
description: Intutic governance awareness. Always check compliance before tool calls.
triggers:
  - before any tool call
  - before any file write
  - before any shell command
---

# Intutic Governance Policy

Before every tool call, you MUST verify compliance with workspace SOPs.
A pre-tool-use hook (\`~/.intutic/hooks/hermes-check.sh\`) enforces these rules automatically.

If a tool call is blocked, do NOT attempt to circumvent the governance gate.
To update policy, use the Intutic control plane at \`${proxyUrl}\`.
`
}

// ─── Main export ──────────────────────────────────────────────────────────────

/**
 * Write the Hermes governance hook script, merge config, and write the
 * governance skill for the Hermes AI agent.
 *
 * Safe to call repeatedly — uses atomic rename so partial writes never
 * leave a corrupt state.
 *
 * @param workspaceRoot - Absolute workspace root path.
 * @param proxyUrl      - Intutic proxy URL written into hook headers / skill.
 * @param workspaceId   - Workspace ID embedded in every hook event payload.
 */
export async function writeHermesHooks(
  workspaceRoot: string,
  proxyUrl: string,
  workspaceId = '',
): Promise<void> {
  // ── 1. Ensure directories ──────────────────────────────────────────────────

  const globalHookDir = path.join(os.homedir(), '.intutic', 'hooks')
  const hookEventsDir = path.join(workspaceRoot, '.intutic', 'events')
  const envDir = path.join(workspaceRoot, '.intutic', 'env')
  const hermesDir = path.join(os.homedir(), '.hermes')
  const skillsDir = path.join(hermesDir, 'skills', 'intutic-governance')

  await Promise.all([
    fs.mkdir(globalHookDir, { recursive: true }),
    fs.mkdir(hookEventsDir, { recursive: true }),
    fs.mkdir(envDir, { recursive: true }),
    fs.mkdir(hermesDir, { recursive: true }),
    fs.mkdir(skillsDir, { recursive: true }),
  ])

  // ── 2. Write bash hook script ──────────────────────────────────────────────

  const hookScriptPath = path.join(globalHookDir, 'hermes-check.sh')
  const tmpScript = hookScriptPath + '.intutic-tmp'
  await fs.writeFile(tmpScript, buildHermesCheckScript(proxyUrl, workspaceRoot, workspaceId), 'utf-8')
  await fs.rename(tmpScript, hookScriptPath)
  await fs.chmod(hookScriptPath, 0o755)

  log.info({ action: 'hermes_hook_script_written', path: hookScriptPath }, 'Hermes hook script written')

  // ── 3. YAML-safe merge into ~/.hermes/config.yaml ─────────────────────────

  await mergeHermesConfig(hookScriptPath)

  log.info(
    { action: 'hermes_config_merged', path: HERMES_CONFIG },
    'Merged Intutic hook into ~/.hermes/config.yaml',
  )

  // ── 4. Write governance skill ──────────────────────────────────────────────

  const skillPath = path.join(skillsDir, 'SKILL.md')
  const tmpSkill = skillPath + '.intutic-tmp'
  await fs.writeFile(tmpSkill, buildGovernanceSkill(proxyUrl), 'utf-8')
  await fs.rename(tmpSkill, skillPath)

  log.info(
    { action: 'hermes_skill_written', path: skillPath },
    'Hermes governance skill written',
  )

  // ── 5. Write env snippet ───────────────────────────────────────────────────

  const envSnippet = [
    `# Intutic Hermes governance env`,
    `INTUTIC_HERMES_HOOK=~/.intutic/hooks/hermes-check.sh`,
    `INTUTIC_HERMES_CONFIG=~/.hermes/config.yaml`,
  ].join('\n') + '\n'

  const envFilePath = path.join(envDir, 'hermes.env')
  const tmpEnv = envFilePath + '.intutic-tmp'
  await fs.writeFile(tmpEnv, envSnippet, 'utf-8')
  await fs.rename(tmpEnv, envFilePath)

  log.info(
    { action: 'hermes_env_written', path: envFilePath },
    'Hermes env snippet written',
  )
}
