/**
 * museHooks.ts — Meta "Muse Code" PreToolUse/PermissionRequest hook injection.
 *
 * Muse Code (binary `muse`, model Muse Spark, beta since 2026-08-05) exposes
 * 12 lifecycle hook events; two are blocking — `PreToolUse` and
 * `PermissionRequest` — and are what this writer targets. Hooks are
 * configured at three tiers:
 *
 *   - Project-level: `<workspaceRoot>/.muse/hooks.json`
 *   - User-level:    settings embedded directly in `~/.config/muse/settings.json`
 *   - Managed:       a `managed_hooks_path` setting in `~/.config/muse/settings.json`
 *                     pointing at a SEPARATE hooks file — registered here at
 *                     `~/.config/muse/intutic-managed-hooks.json`. This is the
 *                     "pre-approved" tier: per the phase brief, hooks registered
 *                     through it do not trigger a user trust/approval prompt the
 *                     way a plain user-level hooks.json entry would.
 *
 * This writer uses the managed tier (narrow merge into settings.json — never a
 * wholesale overwrite, so `schema_version`, `mcp_servers`, and anything else a
 * user or `mcpAutoWrite.ts` put there survives) PLUS the project-level tier,
 * for defense in depth: `managed_hooks_path` is a single global setting, so a
 * machine where it has not landed yet (first sync, or a settings.json write
 * that failed) still gets project-scoped coverage the same sync cycle. This is
 * the same two-tier shape `codexHooks.ts` uses for Codex's user+project
 * `hooks.json` files — see that module's doc comment.
 *
 * ## The block/deny wire contract is UNVERIFIED — see TD-362
 *
 * Muse Code's own documentation does not state whether a PreToolUse/
 * PermissionRequest hook refuses via a non-zero exit code or a JSON object on
 * stdout, and the `muse` binary could not be installed in the environment this
 * writer was authored in to confirm it empirically (beta product, no public
 * package registry entry found). This writer uses the **same exit-2 contract
 * `codexHooks.ts` uses** — the closest architectural analog (a JS gate reading
 * JSON on stdin, registered at both a project and a user-scoped `hooks.json`)
 * — rather than inventing a new one. TD-362 records this as an explicit
 * assumption pending real installation.
 *
 * @module
 */

import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import * as os from 'node:os'
import { createLogger } from '@intutic/logger'
import { newIso } from '@intutic/id'
import { emitJsGate, emitJsFailClosedPrelude } from './gateBody.js'

const log = createLogger('sync-muse-hooks')

/** The two blocking lifecycle events this writer registers against. Muse Code
 *  has ten other (non-blocking) lifecycle hooks this codebase does not gate. */
const BLOCKING_EVENTS = ['PreToolUse', 'PermissionRequest'] as const

/**
 * The pre-tool gate script — receives Muse's hook JSON on stdin, exits 0 to
 * allow or 2 to block. Registered for BOTH `PreToolUse` and
 * `PermissionRequest` — the same script handles either event, since both are
 * expected to carry a tool-call-shaped payload (tool name + tool input); the
 * shared envelope guard refuses anything that does not.
 */
function buildHookScript(proxyUrl: string, workspaceRoot: string, workspaceId: string): string {
  const hookEventsLog = path.join(workspaceRoot, '.intutic', 'events', 'hook-events.jsonl')
  return `#!/usr/bin/env node
/**
 * Intutic Muse Code governance gate.
 * Auto-generated by intutic sync-daemon. DO NOT EDIT.
 * Proxy: ${proxyUrl}
 * Generated: ${newIso()}
 *
 * Registered for PreToolUse AND PermissionRequest — see museHooks.ts's module
 * doc comment for why the block/deny contract below (exit 2) is an ASSUMED
 * contract (TD-362), not a confirmed one.
 */
${emitJsFailClosedPrelude({ harness: 'muse-code', contract: 'exit2' })}
const path = require('path');
const os = require('os');
const fs = require('fs');
const crypto = require('crypto');
const https = require('https');

// Runtime credentials
const _runtimeEnvPath = path.join(os.homedir(), '.intutic', 'env', 'runtime.env');
let _intuticHost = 'https://api.intutic.ai', _intuticKey = '', _intuticWsId = ${JSON.stringify(workspaceId)};
try {
  fs.readFileSync(_runtimeEnvPath, 'utf-8').split('\\n').forEach(line => {
    const eq = line.indexOf('='); if (eq < 0) return;
    const k = line.slice(0, eq).trim(), v = line.slice(eq + 1).trim();
    if (k === 'INTUTIC_HOST' && v) _intuticHost = v;
    if (k === 'INTUTIC_API_KEY' && v) _intuticKey = v;
    if (k === 'INTUTIC_WORKSPACE_ID' && v) _intuticWsId = v;
  });
} catch {}

${emitJsGate({ harness: 'muse-code', contract: 'exit2' })}

let _intuticSessionId = '';
function logEvent(verdict, toolName, reason) {
  try {
    const ts = new Date().toISOString();
    const incidentId = crypto.createHash('sha1').update(ts + toolName + _intuticWsId).digest('hex').slice(0, 16);
    const entry = JSON.stringify({
      event: verdict,
      toolName, reason: reason || '',
      workspaceId: _intuticWsId,
      harnessType: 'muse-code',
      timestamp: ts,
      incidentId,
      ...(_intuticSessionId ? { sessionId: _intuticSessionId } : {}),
    }) + '\\n';
    fs.appendFileSync(${JSON.stringify(hookEventsLog)}, entry, { flag: 'a' });
    if (_intuticKey) {
      try {
        const body = JSON.stringify({ events: [JSON.parse(entry)] });
        const urlObj = new URL('/api/v1/hook-events', _intuticHost);
        const mod = urlObj.protocol === 'https:' ? https : require('http');
        const req = mod.request({ hostname: urlObj.hostname, port: urlObj.port || 443, path: urlObj.pathname, method: 'POST', headers: { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body), 'Authorization': 'Bearer ' + _intuticKey } });
        req.on('error', () => { /* fire-and-forget */ });
        req.write(body); req.end();
      } catch { /* never crash the hook */ }
    }
  } catch { /* never crash the hook */ }
}

let raw = '';
process.stdin.on('data', (c) => { raw += c; });
process.stdin.on('end', () => {
  try {
    const ctx = JSON.parse(raw);
    _intuticSessionId = ctx.session_id || ctx.sessionId || '';
    // Same envelope guard every JS writer applies — a payload with neither a
    // tool name nor a tool_input is anomalous for either event this script is
    // registered against and is refused rather than allowed.
    intuticGuardEnvelope(ctx, ['tool_name', 'toolName', 'tool_input', 'toolInput'], logEvent);
    const input = ctx.tool_input || ctx.toolInput || {};
    const toolName = ctx.tool_name || ctx.toolName || 'tool';

    const targetPath = input.path || input.file_path || input.filePath || input.file ||
      input.target || input.notebook_path || '';
    const command = input.command || input.cmd || input.script || '';

    intuticGate(toolName, targetPath, command, logEvent, _intuticWsId, input);

    // Allow
    logEvent('tool_allowed', toolName, '');
    process.exit(0);
  } catch (err) {
    // Fail CLOSED
    const errMsg = String(err);
    process.stderr.write('[Intutic Governance] Hook error (fail-closed): ' + errMsg + '\\n');
    logEvent('tool_blocked', 'unknown', errMsg);
    process.exit(2);
  }
});
`
}

/**
 * Merge the Intutic PreToolUse + PermissionRequest entries into a Muse
 * hooks-shaped JSON file, preserving everything the user (or, for the
 * managed-hooks file, a prior sync) put there.
 *
 * Shared by both the project-level `.muse/hooks.json` and the managed-hooks
 * file `managed_hooks_path` points at — both are assumed to carry the same
 * `{ hooks: { <Event>: [{ matcher, hooks: [{ type, command }] }] } }` shape
 * `codexHooks.ts` established for a Claude-Code-compatible `hooks.json`; see
 * TD-362 for why that shape is an assumption for Muse specifically.
 *
 * De-duplication is by command (any entry whose hooks all invoke this gate
 * script is ours and is replaced), matching every other JSON hook writer in
 * this codebase — repeated syncs are idempotent and never stack duplicates.
 */
async function mergeMuseHooksJson(configPath: string, hookScriptPath: string): Promise<void> {
  let existing: Record<string, unknown> = {}
  try {
    existing = JSON.parse(await fs.readFile(configPath, 'utf-8'))
  } catch {
    // File doesn't exist or is malformed — start fresh.
  }

  const existingHooks = (existing.hooks as Record<string, unknown>) ?? {}
  const intuticCmd = `node "${hookScriptPath}"`

  const nextHooks: Record<string, unknown> = { ...existingHooks }
  for (const event of BLOCKING_EVENTS) {
    const existingEntries = Array.isArray(existingHooks[event]) ? (existingHooks[event] as unknown[]) : []
    const filtered = existingEntries.filter((entry: unknown) => {
      if (typeof entry !== 'object' || entry === null) return true
      const inner = ((entry as Record<string, unknown>).hooks as unknown[]) ?? []
      return !(
        inner.length > 0 &&
        inner.every(
          (h: unknown) =>
            typeof h === 'object' && h !== null && (h as Record<string, unknown>).command === intuticCmd,
        )
      )
    })
    nextHooks[event] = [
      ...filtered,
      {
        // One catch-all matcher, same convention as codexHooks.ts: the gate
        // itself decides from the arguments, so a tool name nobody
        // anticipated is still evaluated rather than silently unmatched.
        matcher: '.*',
        hooks: [{ type: 'command', command: intuticCmd }],
      },
    ]
  }

  const merged = {
    ...existing,
    description:
      'Intutic governance hooks (auto-managed; your own hooks are preserved). ' +
      `Last sync: ${newIso()}`,
    hooks: nextHooks,
  }

  const tmp = configPath + '.intutic-tmp'
  await fs.mkdir(path.dirname(configPath), { recursive: true })
  await fs.writeFile(tmp, JSON.stringify(merged, null, 2) + '\n', 'utf-8')
  await fs.rename(tmp, configPath)
}

/**
 * Narrow merge-write of `managed_hooks_path` into `~/.config/muse/settings.json`.
 *
 * Never a wholesale overwrite: every other key (`schema_version` — mandatory
 * per the phase brief, defaulted to `1` if this is the first write anyone has
 * ever made to the file — `mcp_servers`, anything a user or `mcpAutoWrite.ts`
 * put there) is preserved. Only `managed_hooks_path` is set/updated.
 */
async function mergeMuseSettingsJson(settingsPath: string, managedHooksPath: string): Promise<void> {
  let existing: Record<string, unknown> = {}
  try {
    existing = JSON.parse(await fs.readFile(settingsPath, 'utf-8'))
  } catch {
    // File doesn't exist or is malformed — start fresh.
  }

  const merged = {
    // `schema_version` is documented as mandatory — never write the file
    // without it, but never clobber a value that is already there.
    schema_version: existing.schema_version ?? 1,
    ...existing,
    managed_hooks_path: managedHooksPath,
  }

  const tmp = settingsPath + '.intutic-tmp'
  await fs.mkdir(path.dirname(settingsPath), { recursive: true })
  await fs.writeFile(tmp, JSON.stringify(merged, null, 2) + '\n', 'utf-8')
  await fs.rename(tmp, settingsPath)
}

/**
 * Write the Muse gate script and register it at the project tier and the
 * managed (pre-approved) tier.
 *
 * Safe to call repeatedly — uses atomic rename (`.intutic-tmp` → final path)
 * and command-keyed de-duplication in both hooks-shaped files.
 *
 * @param workspaceRoot - Absolute workspace root path.
 * @param proxyUrl      - Intutic proxy URL written into the gate header.
 * @param workspaceId   - Workspace ID embedded in every hook event payload.
 */
export async function writeMuseHooks(
  workspaceRoot: string,
  proxyUrl: string,
  workspaceId = '',
): Promise<void> {
  const hookScriptDir = path.join(workspaceRoot, '.intutic', 'hooks')
  await fs.mkdir(hookScriptDir, { recursive: true })
  await fs.mkdir(path.join(workspaceRoot, '.intutic', 'events'), { recursive: true })

  const hookScriptPath = path.join(hookScriptDir, 'muse-check.js')
  const tmpScript = hookScriptPath + '.intutic-tmp'
  await fs.writeFile(tmpScript, buildHookScript(proxyUrl, workspaceRoot, workspaceId), 'utf-8')
  await fs.rename(tmpScript, hookScriptPath)
  await fs.chmod(hookScriptPath, 0o755)

  // 1. Project-level: <root>/.muse/hooks.json
  const projectMuseDir = path.join(workspaceRoot, '.muse')
  await fs.mkdir(projectMuseDir, { recursive: true })
  await mergeMuseHooksJson(path.join(projectMuseDir, 'hooks.json'), hookScriptPath)
  log.info({ action: 'muse_hooks_written', level: 'project', path: projectMuseDir }, 'Muse Code project-level hooks written')

  // 2. Managed (pre-approved) tier: ~/.config/muse/intutic-managed-hooks.json,
  //    registered via managed_hooks_path in ~/.config/muse/settings.json.
  const museConfigDir = path.join(os.homedir(), '.config', 'muse')
  await fs.mkdir(museConfigDir, { recursive: true })
  const managedHooksPath = path.join(museConfigDir, 'intutic-managed-hooks.json')
  await mergeMuseHooksJson(managedHooksPath, hookScriptPath)

  const settingsPath = path.join(museConfigDir, 'settings.json')
  await mergeMuseSettingsJson(settingsPath, managedHooksPath)
  log.info(
    { action: 'muse_hooks_written', level: 'managed', path: managedHooksPath },
    'Muse Code managed-hooks tier registered via managed_hooks_path',
  )
}
