/**
 * openclawHooks.ts — Openclaw governance hook injection.
 *
 * Openclaw uses `~/.openclaw/openclaw.json` (JSON5 format — may have comments
 * and trailing commas). The hook entry is registered under
 * `hooks.internal.entries["intutic-governance"]`. This module:
 *
 * 1. JSON5-safe-merges `~/.openclaw/openclaw.json` with the hook entry.
 * 2. Writes `~/.intutic/hooks/openclaw-check.js` — dual-path Node.js hook.
 * 3. Writes `.intutic/env/openclaw.env` — env snippet.
 * 4. Optionally validates with `openclaw hooks check` (non-fatal).
 *
 * Hook protocol: stdin JSON `{tool_name, tool_input, transcript_path}`,
 * exit 0 = allow, exit 2 = block (stderr shown to agent).
 *
 * WS-C2 — Openclaw harness (Phase 3 cross-harness defence)
 * LLD #14 — Phase 3 cross-harness defence (Gap 3)
 * HLD §3.14 — Three-Tier Defense Cascade (Tier 1 Native Gating)
 *
 * @module
 */

import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import * as os from 'node:os'
import { exec } from 'node:child_process'
import { promisify } from 'node:util'
import { createLogger } from '@intutic/logger'
import { newIso } from '@intutic/id'

const log = createLogger('sync-openclaw-hooks')
const execAsync = promisify(exec)

/** Path to the Openclaw global config file. */
const OPENCLAW_CONFIG = path.join(os.homedir(), '.openclaw', 'openclaw.json')

/** Governance-sensitive paths that the hook gate protects. */
const PROTECTED_PATHS = [
  '.gemini/settings.json',
  '.intutic/hooks',
  '.intutic/integrity.json',
  '.intutic/events',
  '.claude/settings.json',
  '.cursor/hooks.json',
  '.codeium/windsurf/hooks.json',
  '.cline/hooks',
  '.agents/plugins/intutic-governance',
  '.openhands/hooks.json',
  '.openclaw/openclaw.json',
]

// ─── Node.js hook script template ────────────────────────────────────────────

function buildOpenclawCheckScript(
  hookEventsLog: string,
  workspaceId: string,
): string {
  return `#!/usr/bin/env node
/**
 * Intutic Openclaw PreToolUse execution gate.
 * Auto-generated by intutic sync-daemon. DO NOT EDIT.
 * Generated: ${newIso()}
 * Workspace: ${workspaceId}
 */
'use strict';
const path = require('path');
const os = require('os');
const fs = require('fs');
const crypto = require('crypto');
const https = require('https');

// ── Runtime credentials (sourced from ~/.intutic/env/runtime.env at invocation time) ──
const _runtimeEnvPath = path.join(os.homedir(), '.intutic', 'env', 'runtime.env');
let _intuticHost = 'https://api.intutic.ai', _intuticKey = '', _intuticWsId = ${JSON.stringify(workspaceId)};
try {
  fs.readFileSync(_runtimeEnvPath, 'utf-8').split('\\n').forEach(line => {
    const eq = line.indexOf('='); if (eq < 0) return;
    const k = line.slice(0, eq).trim(), v = line.slice(eq + 1).trim();
    if (k === 'INTUTIC_HOST' && v) _intuticHost = v;
    if (k === 'INTUTIC_API_KEY' && v) _intuticKey = v;
    if (k === 'INTUTIC_WORKSPACE_ID' && v) _intuticWsId = v;
  });
} catch { /* runtime.env not yet written — use defaults */ }

// Governance-sensitive paths that no agent may modify.
const PROTECTED_PATHS = ${JSON.stringify(PROTECTED_PATHS, null, 2)};

/**
 * Appends a governance event to the local hook-events log (Path B)
 * and fires a non-blocking HTTP POST to the control plane (Path A).
 */
function logEvent(verdict, toolName, reason) {
  try {
    const ts = new Date().toISOString();
    // incidentId = sha1(timestamp + toolName + workspaceId).slice(0,16)
    const incidentId = crypto.createHash('sha1').update(ts + toolName + _intuticWsId).digest('hex').slice(0, 16);
    const entry = JSON.stringify({
      event: verdict === 'blocked' ? 'tool_blocked' : 'tool_allowed',
      toolName,
      reason: reason || '',
      workspaceId: _intuticWsId,
      harnessType: 'openclaw',
      timestamp: ts,
      incidentId,
    }) + '\\n';
    // Path B: reliable file append (sync-daemon drains on FSEvents change)
    fs.appendFileSync(${JSON.stringify(hookEventsLog)}, entry, { flag: 'a' });
    // Path A: fire-and-forget HTTP POST (near-real-time dashboard, non-blocking)
    if (_intuticKey) {
      try {
        const body = JSON.stringify({ events: [JSON.parse(entry)] });
        const urlObj = new URL('/api/v1/hook-events', _intuticHost);
        const isHttps = urlObj.protocol === 'https:';
        const mod = isHttps ? https : require('http');
        const req = mod.request({
          hostname: urlObj.hostname,
          port: urlObj.port || (isHttps ? 443 : 80),
          path: urlObj.pathname,
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Content-Length': Buffer.byteLength(body),
            'Authorization': 'Bearer ' + _intuticKey,
          },
        });
        req.on('error', () => { /* fire-and-forget — ignore errors */ });
        req.write(body);
        req.end();
      } catch { /* never crash the hook */ }
    }
  } catch { /* never crash the hook */ }
}

// Read stdin containing Openclaw's tool context
let inputData = '';
process.stdin.on('data', (chunk) => { inputData += chunk; });
process.stdin.on('end', () => {
  try {
    const ctx = JSON.parse(inputData);
    const toolName = (ctx.tool_name || ctx.toolName || '').toLowerCase();
    const toolInput = ctx.tool_input || ctx.toolInput || {};

    // 1. Protected-path guard
    const targetPath = toolInput.path || toolInput.file_path || toolInput.new_path || toolInput.target || '';
    for (const p of PROTECTED_PATHS) {
      if (String(targetPath).includes(p) || String(targetPath).startsWith(p)) {
        const reason = \`Attempt to modify governance-protected path: "\${targetPath}". \` +
          'To change governance policy, update your SOP via the Intutic control plane.';
        console.error(\`[Intutic Governance] BLOCKED: \${reason}\`);
        logEvent('blocked', toolName, reason);
        process.exit(2);
      }
    }

    // 2. Bash/shell command guard — block governance bypass patterns
    const command = toolInput.command || toolInput.cmd || '';
    const BYPASS_PATTERNS = [
      'chflags nouchg',
      'chattr -i',
      'rm -rf .intutic',
      'rm -rf .openclaw',
      'OPENCLAW_PRE_TOOL_HOOK=',
      'rm -rf .gemini/settings',
    ];
    for (const pattern of BYPASS_PATTERNS) {
      if (String(command).includes(pattern)) {
        const reason = \`Shell command matches governance bypass pattern: "\${pattern}"\`;
        console.error(\`[Intutic Governance] BLOCKED: \${reason}\`);
        logEvent('blocked', toolName, reason);
        process.exit(2);
      }
    }

    logEvent('allowed', toolName, '');
    process.exit(0);
  } catch (err) {
    // Fail CLOSED — any hook execution error blocks the tool call.
    console.error('[Intutic Governance] Hook error (blocking for safety):', err);
    logEvent('blocked', 'unknown', String(err));
    process.exit(2);
  }
});
`
}

// ─── JSON5 merge helpers ──────────────────────────────────────────────────────

/**
 * Attempt to parse a JSON5-like string by progressively stripping
 * non-standard syntax. Returns a plain JS object or throws if unparseable.
 */
function parseJson5Like(raw: string): Record<string, unknown> {
  // Attempt 1: vanilla JSON
  try {
    return JSON.parse(raw) as Record<string, unknown>
  } catch {
    // pass
  }

  // Attempt 2: strip single-line // comments
  let stripped = raw.replace(/\/\/[^\n]*/g, '')
  try {
    return JSON.parse(stripped) as Record<string, unknown>
  } catch {
    // pass
  }

  // Attempt 3: also strip trailing commas before } or ]
  stripped = stripped.replace(/,(\s*[}\]])/g, '$1')
  return JSON.parse(stripped) as Record<string, unknown>
}

/**
 * Deep-merge `hooks.internal.entries["intutic-governance"]` into the parsed
 * openclaw config object and return the merged result.
 */
function mergeOpenclawConfig(
  existing: Record<string, unknown>,
  hookScriptPath: string,
): Record<string, unknown> {
  const hooks = (existing.hooks as Record<string, unknown> | undefined) ?? {}
  const internal = (hooks.internal as Record<string, unknown> | undefined) ?? {}
  const entries = (internal.entries as Record<string, unknown> | undefined) ?? {}

  return {
    ...existing,
    hooks: {
      ...hooks,
      internal: {
        ...internal,
        entries: {
          ...entries,
          'intutic-governance': {
            enabled: true,
            event: 'PreToolUse',
            command: hookScriptPath,
          },
        },
      },
    },
  }
}

// ─── Main export ──────────────────────────────────────────────────────────────

/**
 * Write the Openclaw governance hook script and merge hook configuration
 * into `~/.openclaw/openclaw.json`.
 *
 * Safe to call repeatedly — uses atomic rename so partial writes never
 * leave a corrupt state.
 *
 * @param workspaceRoot - Absolute workspace root path.
 * @param proxyUrl      - Intutic proxy URL written into hook headers.
 * @param workspaceId   - Workspace ID embedded in every hook event payload.
 */
export async function writeOpenclawHooks(
  workspaceRoot: string,
  proxyUrl: string,
  workspaceId = '',
): Promise<void> {
  // ── 1. Ensure directories ──────────────────────────────────────────────────

  const globalHookDir = path.join(os.homedir(), '.intutic', 'hooks')
  const hookEventsDir = path.join(workspaceRoot, '.intutic', 'events')
  const envDir = path.join(workspaceRoot, '.intutic', 'env')
  const openclawDir = path.join(os.homedir(), '.openclaw')

  await Promise.all([
    fs.mkdir(globalHookDir, { recursive: true }),
    fs.mkdir(hookEventsDir, { recursive: true }),
    fs.mkdir(envDir, { recursive: true }),
    fs.mkdir(openclawDir, { recursive: true }),
  ])

  // ── 2. Write Node.js hook script ──────────────────────────────────────────

  const hookScriptPath = path.join(globalHookDir, 'openclaw-check.js')
  const hookEventsLog = path.join(hookEventsDir, 'hook-events.jsonl')

  const tmpScript = hookScriptPath + '.intutic-tmp'
  await fs.writeFile(tmpScript, buildOpenclawCheckScript(hookEventsLog, workspaceId), 'utf-8')
  await fs.rename(tmpScript, hookScriptPath)
  await fs.chmod(hookScriptPath, 0o755)

  log.info({ action: 'openclaw_hook_script_written', path: hookScriptPath }, 'Openclaw hook script written')

  // ── 3. JSON5-safe merge into ~/.openclaw/openclaw.json ────────────────────

  let existingConfig: Record<string, unknown> = {}
  try {
    const raw = await fs.readFile(OPENCLAW_CONFIG, 'utf-8')
    existingConfig = parseJson5Like(raw)
  } catch {
    // File doesn't exist or is unparseable — start fresh
  }

  const mergedConfig = mergeOpenclawConfig(existingConfig, hookScriptPath)

  const tmpConfig = OPENCLAW_CONFIG + '.intutic-tmp'
  await fs.writeFile(tmpConfig, JSON.stringify(mergedConfig, null, 2) + '\n', 'utf-8')
  await fs.rename(tmpConfig, OPENCLAW_CONFIG)

  log.info(
    { action: 'openclaw_config_merged', path: OPENCLAW_CONFIG },
    'Merged Intutic hook into ~/.openclaw/openclaw.json',
  )

  // ── 4. Write env snippet ───────────────────────────────────────────────────

  const envSnippet = [
    `# Intutic openclaw governance env`,
    `INTUITIC_OPENCLAW_HOOK=~/.intutic/hooks/openclaw-check.js`,
    `INTUITIC_OPENCLAW_CONFIG=~/.openclaw/openclaw.json`,
    `# Validate: openclaw hooks check`,
  ].join('\n') + '\n'

  const envFilePath = path.join(envDir, 'openclaw.env')
  const tmpEnv = envFilePath + '.intutic-tmp'
  await fs.writeFile(tmpEnv, envSnippet, 'utf-8')
  await fs.rename(tmpEnv, envFilePath)

  log.info(
    { action: 'openclaw_env_written', path: envFilePath },
    'Openclaw env snippet written',
  )

  // ── 5. Optional validation (non-fatal) ────────────────────────────────────

  try {
    const { stdout, stderr } = await execAsync('openclaw hooks check', { timeout: 5000 })
    log.info(
      { action: 'openclaw_hooks_check', stdout: stdout.trim(), stderr: stderr.trim() },
      'openclaw hooks check passed',
    )
  } catch (err) {
    // Not installed or check failed — non-fatal
    log.debug({ action: 'openclaw_hooks_check_skipped', err }, 'openclaw hooks check skipped (binary not in PATH or check failed)')
  }

  void proxyUrl // proxyUrl captured in hook script header via newIso comment
}
