/**
 * openhandsHooksWriter.ts — OpenHands PreToolUse native hook writer.
 *
 * Writes two artefacts:
 *   1. `~/.intutic/hooks/pre-tool-check.sh` — shared bash gate script that
 *      sources runtime credentials, POSTs to the Intutic hook-gate endpoint,
 *      exits 2 on block (fail-open on curl error). Sets HARNESS=openhands in
 *      the request body so the control plane can route correctly.
 *   2. `<workspaceRoot>/.openhands/hooks.json` — registers the script as the
 *      PreToolUse handler with a 10-second timeout.
 *
 * LLD #14 — Phase 4 WS-4C native hook script writers
 * HLD §3.14 — Three-Tier Defense Cascade (Tier 1 Native Gating)
 *
 * @module
 */

import * as node_fs from 'node:fs/promises'
import * as node_path from 'node:path'
import * as node_os from 'node:os'
import { createLogger } from '@intutic/logger'

const log = createLogger('sync-openhands-hooks-writer')

const HOOKS_DIR = node_path.join(node_os.homedir(), '.intutic', 'hooks')
const EVENTS_DIR = node_path.join(node_os.homedir(), '.intutic', 'events')
const HOOK_SCRIPT = node_path.join(HOOKS_DIR, 'pre-tool-check.sh')
const HOOK_EVENTS_LOG = node_path.join(EVENTS_DIR, 'hook-events.jsonl')

/**
 * Build the shared bash gate script.
 *
 * The script is designed to be shared across harnesses that invoke a bash
 * pre-tool-use hook. It sets HARNESS=openhands in the POST body so the
 * control-plane can distinguish the origin.
 *
 * Logic:
 *   1. Source ~/.intutic/env/runtime.env for credentials.
 *   2. Read full stdin JSON payload.
 *   3. Merge HARNESS=openhands into the payload.
 *   4. POST to $INTUTIC_CONTROL_PLANE_URL/api/v1/hook-gate (10 s timeout).
 *   5. Fail-open if curl returns an error or no API key is set.
 *   6. Exit 2 + append JSONL event if `"allowed":false`.
 *   7. Exit 0 otherwise.
 */
function buildPreToolCheckScript(): string {
  return `#!/usr/bin/env bash
# Intutic shared pre-tool-check governance gate.
# Auto-generated by intutic sync-daemon. DO NOT EDIT.
# Used by: OpenHands (and any other bash-based hook harness).
set -euo pipefail

HARNESS="openhands"
RUNTIME_ENV="$HOME/.intutic/env/runtime.env"
HOOK_EVENTS_LOG=${JSON.stringify(HOOK_EVENTS_LOG)}
INTUTIC_CONTROL_PLANE_URL="https://api.intutic.ai"
INTUTIC_API_KEY=""
INTUTIC_WORKSPACE_ID=""

# Source runtime credentials (key rotation is automatic on next tool call)
[ -f "$RUNTIME_ENV" ] && source "$RUNTIME_ENV" 2>/dev/null || true

INPUT="$(cat)"
TOOL_NAME="$(echo "$INPUT" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('tool_name',''))" 2>/dev/null || true)"

# Augment body with harness identifier
BODY="$(echo "$INPUT" | python3 -c "
import sys, json
d = json.load(sys.stdin)
d['harness'] = '$HARNESS'
d['workspaceId'] = '$INTUTIC_WORKSPACE_ID'
print(json.dumps(d))
" 2>/dev/null || echo "$INPUT")"

# ── POST to hook-gate ─────────────────────────────────────────────────
GATE_URL="\${INTUTIC_CONTROL_PLANE_URL}/api/v1/hook-gate"
RESPONSE=""
if [ -n "$INTUTIC_API_KEY" ]; then
  RESPONSE="$(curl -s --max-time 10 -X POST \\
    -H "Content-Type: application/json" \\
    -H "Authorization: Bearer $INTUTIC_API_KEY" \\
    -d "$BODY" \\
    "$GATE_URL" 2>/dev/null)" || true
fi

# Fail-open: empty response (curl error / no key) → allow
if [ -z "$RESPONSE" ]; then
  exit 0
fi

# Parse decision
ALLOWED="$(echo "$RESPONSE" | python3 -c "import sys,json; d=json.load(sys.stdin); print(str(d.get('allowed', True)).lower())" 2>/dev/null || echo "true")"

if [ "$ALLOWED" = "false" ]; then
  REASON="$(echo "$RESPONSE" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('reason',''))" 2>/dev/null || true)"
  TS="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  INCIDENT_ID="$(printf '%s' "\${TS}\${TOOL_NAME}\${INTUTIC_WORKSPACE_ID}" | sha1sum 2>/dev/null | cut -c1-16 || echo "$(date +%s)")"
  ENTRY="{\\"event\\":\\"tool_blocked\\",\\"toolName\\":\\"\${TOOL_NAME}\\",\\"reason\\":\\"\${REASON}\\",\\"workspaceId\\":\\"\${INTUTIC_WORKSPACE_ID}\\",\\"harnessType\\":\\"\${HARNESS}\\",\\"timestamp\\":\\"\${TS}\\",\\"incidentId\\":\\"\${INCIDENT_ID}\\"}"
  mkdir -p "$(dirname "$HOOK_EVENTS_LOG")"
  printf '%s\\n' "$ENTRY" >> "$HOOK_EVENTS_LOG" 2>/dev/null || true
  echo "[Intutic Governance] BLOCKED: $REASON" >&2
  exit 2
fi

exit 0
`
}

/**
 * Build the .openhands/hooks.json document that registers the PreToolUse hook.
 *
 * @param hookScriptPath - Absolute path to the bash gate script.
 */
function buildOpenHandsHooksJson(hookScriptPath: string): Record<string, unknown> {
  return {
    _comment: 'Intutic governance hooks — auto-generated. DO NOT EDIT.',
    hooks: [
      {
        type: 'PreToolUse',
        command: hookScriptPath,
        timeout: 10,
      },
    ],
  }
}

/**
 * Write OpenHands PreToolUse hook script and hooks.json.
 *
 * @param workspaceRoot - Absolute path to the workspace root.
 */
export async function writeOpenHandsHooks(workspaceRoot: string): Promise<void> {
  // ── Ensure directories exist ─────────────────────────────────────────
  await node_fs.mkdir(HOOKS_DIR, { recursive: true })
  await node_fs.mkdir(EVENTS_DIR, { recursive: true })

  // ── 1. Write shared bash gate script ────────────────────────────────
  const tmpScript = HOOK_SCRIPT + '.intutic-tmp'
  await node_fs.writeFile(tmpScript, buildPreToolCheckScript(), 'utf-8')
  await node_fs.rename(tmpScript, HOOK_SCRIPT)
  await node_fs.chmod(HOOK_SCRIPT, 0o755)

  log.info(
    { action: 'openhands_hook_script_written', path: HOOK_SCRIPT },
    'Shared pre-tool-check.sh written',
  )

  // ── 2. Write .openhands/hooks.json ──────────────────────────────────
  const openhandsDir = node_path.join(workspaceRoot, '.openhands')
  await node_fs.mkdir(openhandsDir, { recursive: true })

  const hooksJsonPath = node_path.join(openhandsDir, 'hooks.json')
  const hooksDoc = buildOpenHandsHooksJson(HOOK_SCRIPT)

  const tmpHooks = hooksJsonPath + '.intutic-tmp'
  await node_fs.writeFile(tmpHooks, JSON.stringify(hooksDoc, null, 2) + '\n', 'utf-8')
  await node_fs.rename(tmpHooks, hooksJsonPath)

  log.info(
    { action: 'openhands_hooks_json_written', path: hooksJsonPath },
    'OpenHands hooks.json written',
  )
}
