/**
 * openclawHooks.ts — OpenClaw plugin gate.
 *
 * OpenClaw has two hook systems, and only one of them can stop a tool call.
 * Its *internal* hooks (`hooks.internal.entries` in `~/.openclaw/openclaw.json`,
 * `HOOK.md` handlers) react to command, session and Gateway events; the
 * dispatcher catches a handler's error and carries on, and tool calls are not
 * among their events at all. Earlier versions of this writer registered the
 * gate there, as `{ event: 'PreToolUse', command }`, a shape OpenClaw keeps
 * (hook entries are open-ended) and never runs. Tool calls are intercepted by
 * a *plugin* hook, `before_tool_call`, registered with `api.on(...)`:
 * https://github.com/openclaw/openclaw/blob/59309cc7777e07d52ca1be94bf8c25fd685919bc/docs/automation/hooks.md
 * ("Choose the right surface": intercepting tools is a plugin hook).
 *
 * ## The plugin
 *
 * A standalone plugin file needs no manifest when it is listed in
 * `plugins.load.paths`; its id is the file's basename, so the file is
 * `intutic-governance.cjs` and exports `{ id: 'intutic-governance', register }`
 * (`docs/plugins/hooks/tool-policy.md` "Sender-aware policy in one file";
 * `src/plugins/discovery.ts` `discoverFromPath`; the loader test "loads
 * multiple manifestless standalone files"). `.cjs`, so the module format does
 * not depend on any `package.json` above it. A plugin from a configured path
 * is enabled by default unless a non-empty `plugins.allow` leaves it out
 * (`src/plugins/config-activation-shared.ts`), so the id is added to an
 * existing allowlist and nothing is written when there is none.
 *
 * `before_tool_call` receives `{ toolName, params, toolCallId?, runId?,
 * derivedPaths? }` and `ctx.sessionId`, and refuses with `{ block: true,
 * blockReason }`, which is terminal (`docs/plugins/hooks/tool-policy.md`,
 * `src/plugins/hook-types.ts`). The global hook runner runs it fail-closed: a
 * handler that throws or outlives its timeout blocks the call
 * (`src/plugins/hook-runner-global.ts`: `before_tool_call: "fail-closed"`;
 * default 15 s, `docs/plugins/hooks/reference.md`). That timeout cannot stop
 * synchronous code, so the hook registers `timeoutMs: HOOK_TIMEOUT_SECONDS *
 * 1000` and the gate runs under its own deadline inside it
 * (`gateDeadlineMs('openclaw')`).
 *
 * The plugin embeds the shared `emitJsGate` body (`'throw'` contract) and
 * returns OpenClaw's block result for the refusal it throws. Any other fault
 * is a block too. MCP tools reach the hook as `<server>__<tool>`
 * (`src/agents/agent-bundle-mcp-names.ts`, `TOOL_NAME_SEPARATOR`), which the
 * plugin composes into `mcp__<server>__<tool>` for the allowlist.
 *
 * The file lives under `~/.intutic/hooks/`, a governance-protected path, so an
 * agent cannot edit it under any gated harness.
 *
 * @module
 */

import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import * as os from 'node:os'
import { createLogger } from '@intutic/logger'
import { keepOriginal, writeOwnedFile } from '../disconnect/originals.js'
import { newIso } from '@intutic/id'
import { HOOK_TIMEOUT_SECONDS } from '@intutic/shared-types'
import { emitJsGate, REVIEW_REQUESTS_BASENAME } from './gateBody.js'

const log = createLogger('sync-openclaw-hooks')

/** The plugin id, which OpenClaw takes from the standalone file's basename. */
export const OPENCLAW_PLUGIN_ID = 'intutic-governance'

/** The plugin file, relative to the home directory. */
export const OPENCLAW_PLUGIN_FILE = path.join('.intutic', 'hooks', 'openclaw', `${OPENCLAW_PLUGIN_ID}.cjs`)

/** The first line of the plugin's header, which disconnect recognises it by. */
export const OPENCLAW_PLUGIN_MARKER = 'Intutic OpenClaw governance plugin.'

function openclawConfigPath(): string {
  return path.join(os.homedir(), '.openclaw', 'openclaw.json')
}

/** The absolute path of the plugin file for the current home directory. */
export function openclawPluginPath(): string {
  return path.join(os.homedir(), OPENCLAW_PLUGIN_FILE)
}

// ─── The plugin ──────────────────────────────────────────────────────────────

export function buildOpenclawPlugin(proxyUrl: string, workspaceRoot: string, workspaceId: string): string {
  const hookEventsLog = path.join(workspaceRoot, '.intutic', 'events', 'hook-events.jsonl')
  return `/**
 * ${OPENCLAW_PLUGIN_MARKER}
 * Auto-generated by intutic sync-daemon. DO NOT EDIT.
 * Proxy: ${proxyUrl}
 * Generated: ${newIso()}
 *
 * A before_tool_call plugin hook, loaded through plugins.load.paths in
 * ~/.openclaw/openclaw.json. Refuses a tool call by returning
 * { block: true, blockReason }. See
 * services/sync-daemon/src/harness/openclawHooks.ts.
 */
'use strict';
const path = require('path');
const os = require('os');
const fs = require('fs');
const crypto = require('crypto');
const https = require('https');

// Runtime credentials, read when OpenClaw loads the plugin.
const _runtimeEnvPath = path.join(os.homedir(), '.intutic', 'env', 'runtime.env');
let _intuticHost = 'https://api.intutic.ai', _intuticKey = '', _intuticWsId = ${JSON.stringify(workspaceId)};
try {
  fs.readFileSync(_runtimeEnvPath, 'utf-8').split('\\n').forEach(line => {
    const eq = line.indexOf('='); if (eq < 0) return;
    const k = line.slice(0, eq).trim(), v = line.slice(eq + 1).trim();
    if (k === 'INTUTIC_HOST' && v) _intuticHost = v;
    if (k === 'INTUTIC_API_KEY' && v) _intuticKey = v;
    if (k === 'INTUTIC_WORKSPACE_ID' && v) _intuticWsId = v;
  });
} catch {}

${emitJsGate({ harness: 'openclaw', contract: 'throw', reviewRequestFile: path.join(workspaceRoot, '.intutic', 'events', REVIEW_REQUESTS_BASENAME) })}

let _intuticSessionId = '';
function logEvent(verdict, toolName, reason) {
  try {
    const ts = new Date().toISOString();
    const incidentId = crypto.createHash('sha1').update(ts + toolName + _intuticWsId).digest('hex').slice(0, 16);
    // The event's id: random, made once here, and resent with the line it is
    // written into, so the control plane processes the event once.
    const eventId = crypto.randomBytes(16).toString('hex');
    const entry = JSON.stringify({
      event: verdict,
      toolName, reason: reason || '',
      workspaceId: _intuticWsId,
      harnessType: 'openclaw',
      timestamp: ts,
      incidentId,
      eventId,
      ...(_intuticSessionId ? { sessionId: _intuticSessionId } : {}),
    }) + '\\n';
    const logPath = ${JSON.stringify(hookEventsLog)};
    try { fs.mkdirSync(path.dirname(logPath), { recursive: true }); } catch {}
    fs.appendFileSync(logPath, entry, { flag: 'a' });
    if (_intuticKey) {
      try {
        const body = JSON.stringify({ events: [JSON.parse(entry)] });
        const urlObj = new URL('/api/v1/hook-events', _intuticHost);
        const isHttps = urlObj.protocol === 'https:';
        const mod = isHttps ? https : require('http');
        const req = mod.request({ hostname: urlObj.hostname, port: urlObj.port || (isHttps ? 443 : 80), path: urlObj.pathname, method: 'POST', headers: { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body), 'Authorization': 'Bearer ' + _intuticKey } });
        req.on('error', () => { /* fire-and-forget */ });
        req.write(body); req.end();
      } catch { /* never crash the hook */ }
    }
  } catch { /* never crash the hook */ }
}

/**
 * One tool call. Returns to allow; throws '[Intutic Governance] …' to refuse.
 * Params that are not an object are refused outright: the gate reads paths
 * and commands out of them, and a shape it cannot read is not one it can
 * allow. apply_patch names its files in derivedPaths, and each is checked.
 */
function intuticEvaluate(event, ctx) {
  _intuticSessionId = String((ctx && (ctx.sessionId || ctx.sessionKey)) || '');
  let tool = String((event && event.toolName) || 'tool');
  // OpenClaw names an MCP tool <server>__<tool>; the allowlist reads
  // mcp__<server>__<tool>. No built-in tool id has a double underscore.
  if (tool.indexOf('__') > 0 && tool.indexOf('mcp__') !== 0) tool = 'mcp__' + tool;
  const params = event && event.params;
  if (!params || typeof params !== 'object' || Array.isArray(params)) {
    const reason = '[Intutic Governance] BLOCKED: tool "' + tool + '" was called with parameters the gate cannot read (' +
      (params === null ? 'null' : typeof params) + '); refusing rather than allowing a call it cannot evaluate.';
    try { logEvent('tool_blocked', tool, reason); } catch (e) {}
    throw new Error(reason);
  }
  const command = params.command || params.cmd || params.script || '';
  const direct = params.path || params.file_path || params.filePath || params.target || '';
  const derived = event && Array.isArray(event.derivedPaths) ? event.derivedPaths.filter((p) => typeof p === 'string' && p) : [];
  const targets = derived.length > 0 ? (direct ? [direct].concat(derived) : derived) : [direct];
  for (const target of targets) intuticGate(tool, target, command, logEvent, _intuticWsId, params, _intuticSessionId);
  logEvent('tool_allowed', tool, '');
}

/** Fail closed: a fault inside the gate is a refusal, never an allow. */
function beforeToolCall(event, ctx) {
  try {
    intuticEvaluate(event, ctx);
    return undefined;
  } catch (err) {
    let reason = String((err && err.message) || err);
    if (reason.indexOf('[Intutic Governance]') !== 0) {
      reason = '[Intutic Governance] BLOCKED: gate fault (failing closed): ' + reason;
      try { logEvent('tool_blocked', String((event && event.toolName) || 'unknown'), reason); } catch (e) {}
    }
    return { block: true, blockReason: reason };
  }
}

module.exports = {
  id: ${JSON.stringify(OPENCLAW_PLUGIN_ID)},
  name: 'Intutic governance',
  description: 'Refuses tool calls that break the workspace policy before they run.',
  register(api) {
    api.on('before_tool_call', beforeToolCall, { timeoutMs: ${HOOK_TIMEOUT_SECONDS * 1000} });
  },
};
`
}

// ─── ~/.openclaw/openclaw.json ───────────────────────────────────────────────

/**
 * Attempt to parse a JSON5-like string by progressively stripping
 * non-standard syntax. Returns a plain JS object or throws if unparseable.
 */
export function parseJson5Like(raw: string): Record<string, unknown> {
  // Attempt 1: vanilla JSON
  try {
    return JSON.parse(raw) as Record<string, unknown>
  } catch {
    // pass
  }

  // Attempt 2: strip single-line // comments
  let stripped = raw.replace(/\/\/[^\n]*/g, '')
  try {
    return JSON.parse(stripped) as Record<string, unknown>
  } catch {
    // pass
  }

  // Attempt 3: also strip trailing commas before } or ]
  stripped = stripped.replace(/,(\s*[}\]])/g, '$1')
  return JSON.parse(stripped) as Record<string, unknown>
}

const asObject = (v: unknown): Record<string, unknown> =>
  typeof v === 'object' && v !== null && !Array.isArray(v) ? (v as Record<string, unknown>) : {}

/**
 * Adds the plugin to `plugins.load.paths`, and its id to `plugins.allow` when
 * that list is non-empty (an empty or absent one allows every plugin).
 * Everything else is kept, and a second run adds nothing.
 */
export function mergeOpenclawConfig(existing: Record<string, unknown>, pluginPath: string): Record<string, unknown> {
  const plugins = asObject(existing.plugins)
  const load = asObject(plugins.load)
  const paths = Array.isArray(load.paths) ? load.paths : []
  const allow = Array.isArray(plugins.allow) ? plugins.allow : undefined
  return {
    ...existing,
    plugins: {
      ...plugins,
      ...(allow && allow.length > 0 && !allow.includes(OPENCLAW_PLUGIN_ID) ? { allow: [...allow, OPENCLAW_PLUGIN_ID] } : {}),
      load: { ...load, paths: paths.includes(pluginPath) ? paths : [...paths, pluginPath] },
    },
  }
}

/** Why the plugin will not load even once it is listed, when the config says so. */
function configBlocksPlugin(config: Record<string, unknown>): string | null {
  const plugins = asObject(config.plugins)
  if (plugins.enabled === false) return 'plugins.enabled is false'
  if (Array.isArray(plugins.deny) && plugins.deny.includes(OPENCLAW_PLUGIN_ID)) return `plugins.deny lists ${OPENCLAW_PLUGIN_ID}`
  if (asObject(asObject(plugins.entries)[OPENCLAW_PLUGIN_ID]).enabled === false) return `plugins.entries.${OPENCLAW_PLUGIN_ID}.enabled is false`
  return null
}

// ─── Main export ──────────────────────────────────────────────────────────────

/**
 * Write the OpenClaw governance plugin and list it in
 * `~/.openclaw/openclaw.json`.
 *
 * Safe to call repeatedly: the plugin is replaced by atomic rename and the
 * config merge is idempotent. A config file that does not parse is left as
 * it is, and reported.
 *
 * @param workspaceRoot - Absolute workspace root path.
 * @param proxyUrl      - Intutic proxy URL written into the plugin header.
 * @param workspaceId   - Workspace ID embedded in every hook event payload.
 */
export async function writeOpenclawHooks(
  workspaceRoot: string,
  proxyUrl: string,
  workspaceId = '',
): Promise<void> {
  await fs.mkdir(path.join(workspaceRoot, '.intutic', 'events'), { recursive: true })

  const pluginPath = openclawPluginPath()
  await writeOwnedFile(pluginPath, workspaceRoot, buildOpenclawPlugin(proxyUrl, workspaceRoot, workspaceId))
  log.info({ action: 'openclaw_plugin_written', path: pluginPath }, 'OpenClaw governance plugin written')

  const configPath = openclawConfigPath()
  let raw: string | null = null
  try {
    raw = await fs.readFile(configPath, 'utf-8')
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== 'ENOENT') {
      log.warn({ action: 'config_merge_skipped', path: configPath, error: String(err) }, `Could not read ${configPath} — left untouched`)
      return
    }
  }
  let existing: Record<string, unknown> = {}
  if (raw !== null && raw.trim() !== '') {
    try {
      existing = asObject(parseJson5Like(raw))
    } catch {
      log.warn(
        { action: 'config_merge_skipped', path: configPath },
        `${configPath} does not parse — left untouched; fix it and the next sync will list the Intutic plugin`,
      )
      return
    }
  }

  const blocked = configBlocksPlugin(existing)
  if (blocked) {
    log.warn({ action: 'openclaw_plugin_disabled', path: configPath, reason: blocked }, `OpenClaw will not load the Intutic plugin: ${blocked}`)
  }

  await keepOriginal(configPath, workspaceRoot)
  await fs.mkdir(path.dirname(configPath), { recursive: true })
  const tmp = configPath + '.intutic-tmp'
  await fs.writeFile(tmp, JSON.stringify(mergeOpenclawConfig(existing, pluginPath), null, 2) + '\n', 'utf-8')
  await fs.rename(tmp, configPath)
  log.info({ action: 'openclaw_config_merged', path: configPath }, 'Listed the Intutic plugin in ~/.openclaw/openclaw.json')
}

/**
 * OpenClaw's agent workspace, where it loads `AGENTS.md` and its other
 * bootstrap files every session — never from a project:
 * `agents.defaults.workspace` in `~/.openclaw/openclaw.json`, else
 * `OPENCLAW_WORKSPACE_DIR`, else `~/.openclaw/workspace`
 * (https://github.com/openclaw/openclaw/blob/98457908cf3e4fbbd0354b530e0aa0d15b560158/docs/gateway/config-agents/workspace-and-bootstrap.md).
 */
export async function openclawAgentWorkspace(): Promise<string> {
  const home = os.homedir()
  const expand = (p: string) => (p === '~' || p.startsWith('~/') ? path.join(home, p.slice(1)) : path.resolve(p))
  try {
    const doc = parseJson5Like(await fs.readFile(path.join(home, '.openclaw', 'openclaw.json'), 'utf-8'))
    const agents = doc.agents as { defaults?: { workspace?: unknown } } | undefined
    const configured = agents?.defaults?.workspace
    if (typeof configured === 'string' && configured.trim() !== '') return expand(configured.trim())
  } catch {
    // No config, or one that does not parse: the defaults apply.
  }
  const fromEnv = process.env.OPENCLAW_WORKSPACE_DIR
  if (fromEnv) return expand(fromEnv)
  return path.join(home, '.openclaw', 'workspace')
}
