/**
 * openhandsHooks.ts — OpenHands .openhands/hooks.json injection
 * and llm.base_url proxy write.
 *
 * OpenHands supports PreToolUse, Stop, SessionStart hooks via
 * a JSON file at .openhands/hooks.json in the repository root.
 * The hooks file lives within the agent's sandbox working directory,
 * so we also register it with the drift watcher.
 *
 * LLD #14 — Phase 3 cross-harness defence
 * HLD §3.14 — Three-Tier Defense Cascade
 *
 * @module
 */

import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import { createLogger } from '@intutic/logger'
import { newIso } from '@intutic/id'
import { emitShellGate, SHELL_EXTRACT } from './gateBody.js'

const log = createLogger('sync-openhands-hooks')

/**
 * Write .openhands/hooks.json and the pre-tool-check shell script.
 * Also merges llm.base_url into config.toml if it exists.
 *
 * @param workspaceRoot - Absolute workspace root.
 * @param proxyUrl      - Intutic proxy URL.
 * @param workspaceId   - Workspace ID embedded in hook event payloads.
 */
export async function writeOpenHandsHooks(
  workspaceRoot: string,
  proxyUrl: string,
  workspaceId = '',
): Promise<void> {
  const openhandsDir = path.join(workspaceRoot, '.openhands')
  await fs.mkdir(openhandsDir, { recursive: true })

  const hookScriptDir = path.join(workspaceRoot, '.intutic', 'hooks')
  await fs.mkdir(hookScriptDir, { recursive: true })
  const hookScriptPath = path.join(hookScriptDir, 'openhands-check.sh')

  // Ensure hook events log directory exists
  const hookEventsLog = path.join(workspaceRoot, '.intutic', 'events', 'hook-events.jsonl')
  await fs.mkdir(path.join(workspaceRoot, '.intutic', 'events'), { recursive: true })

  // ── Shell hook script ──────────────────────────────────────────────
  // OpenHands passes tool name and input as env vars + JSON body.
  // Exits 2 to block, 0 to allow.
  const hookScript = `#!/usr/bin/env bash
# Intutic OpenHands PreToolUse governance gate.
# Auto-generated by intutic sync-daemon. DO NOT EDIT.
# Proxy: ${proxyUrl}
# Generated: ${newIso()}
set -euo pipefail

INPUT="$(cat)"
${SHELL_EXTRACT}

HOOK_EVENTS_LOG=${JSON.stringify(hookEventsLog)}

# ── Runtime credentials (sourced from ~/.intutic/env/runtime.env) ────────────────────────
# These are defaults, and they are also the only thing standing between
# \`set -u\` and a fatal unbound-variable error: log_event reads all three, so on
# a machine with no runtime.env to source, an unset name kills the gate before
# it can exit 2. Spelling matters — INTUTIC_, never INTUITIC_.
RUNTIME_ENV="$HOME/.intutic/env/runtime.env"
INTUTIC_HOST="https://api.intutic.ai"
INTUTIC_API_KEY=""
INTUTIC_WORKSPACE_ID=${JSON.stringify(workspaceId)}
[ -f "$RUNTIME_ENV" ] && source "$RUNTIME_ENV" 2>/dev/null || true

log_event() {
  local verdict="\$1" tool="\$2" reason="\$3"
  # \`tool\` and \`reason\` carry agent-controlled text — the tool name, and the
  # target path quoted into the block reason — and both are spliced into the
  # JSON string below. Escape first: one unescaped quote yields a line
  # JSON.parse rejects, and drainHookEvents drops malformed lines then wipes the
  # log on a successful drain, so the record of a block is destroyed rather than
  # delayed. A crafted path could otherwise close the string and forge fields.
  tool="\${tool//\\\\/\\\\\\\\}";     tool="\${tool//\\"/\\\\\\"}"
  reason="\${reason//\\\\/\\\\\\\\}"; reason="\${reason//\\"/\\\\\\"}"
  # Every C0 control character, not just newline and carriage return. JSON
  # forbids all of U+0000-U+001F unescaped, so a plain TAB in a filename — no
  # adversary required — was still enough to produce a line JSON.parse rejects.
  # (NUL cannot appear in a bash variable, so the range starts at \\x01.)
  tool="\${tool//[\$'\\x01'-\$'\\x1f']/ }"; reason="\${reason//[\$'\\x01'-\$'\\x1f']/ }"
  # The workspace id is spliced into the same JSON string. It comes from
  # runtime.env on disk rather than from the agent, so it is lower risk — but a
  # value with a quote in it breaks every audit line the same way, and "lower
  # risk" is not "cannot happen" for a file the operator edits by hand.
  local ws="\${INTUTIC_WORKSPACE_ID}"
  ws="\${ws//\\\\/\\\\\\\\}"; ws="\${ws//\\"/\\\\\\"}"; ws="\${ws//[\$'\\x01'-\$'\\x1f']/ }"
  local ts; ts="\$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  local incident_id; incident_id="\$(printf '%s' "\${ts}\${tool}\${INTUTIC_WORKSPACE_ID}" | sha1sum 2>/dev/null | cut -c1-16 || echo \"\$(date +%s)\")"
  local entry="{\\"event\\":\\"\${verdict}\\",\\"toolName\\":\\"\${tool}\\",\\"reason\\":\\"\${reason}\\",\\"workspaceId\\":\\"\${ws}\\",\\"harnessType\\":\\"openhands\\",\\"timestamp\\":\\"\${ts}\\",\\"incidentId\\":\\"\${incident_id}\\"}"
  # Path B: reliable file append
  printf '%s\\n' "\$entry" >> "\$HOOK_EVENTS_LOG" 2>/dev/null || true
  # Path A: fire-and-forget HTTP (non-blocking, near-real-time)
  if [ -n "\$INTUTIC_API_KEY" ]; then
    curl -s -o /dev/null --max-time 3 -X POST \\
      -H "Content-Type: application/json" \\
      -H "Authorization: Bearer \$INTUTIC_API_KEY" \\
      -d "{\\"events\\":[\$entry]}" \\
      "\${INTUTIC_HOST}/api/v1/hook-events" & disown 2>/dev/null || true
  fi
}

${emitShellGate({ harness: "openhands" })}
log_event "tool_allowed" "\$TOOL_NAME" ""
exit 0
`

  const tmpScript = hookScriptPath + '.oh-tmp'
  await fs.writeFile(tmpScript, hookScript, 'utf-8')
  await fs.rename(tmpScript, hookScriptPath)
  await fs.chmod(hookScriptPath, 0o755)

  // ── .openhands/hooks.json ──────────────────────────────────────────
  const hooksConfig = {
    _comment: 'Intutic governance hooks — auto-generated. DO NOT EDIT.',
    _lastSync: newIso(),
    hooks: [
      {
        type: 'PreToolUse',
        command: hookScriptPath,
        failClosed: true,
      },
      {
        type: 'Stop',
        command: `${hookScriptPath} --event stop`,
        failClosed: false,
      },
    ],
  }

  const hooksPath = path.join(openhandsDir, 'hooks.json')
  const tmpHooks = hooksPath + '.intutic-tmp'
  await fs.writeFile(tmpHooks, JSON.stringify(hooksConfig, null, 2) + '\n', 'utf-8')
  await fs.rename(tmpHooks, hooksPath)

  log.info({ action: 'openhands_hooks_written', path: hooksPath }, 'OpenHands hooks written')

  // ── config.toml llm.base_url injection ────────────────────────────
  await mergeOpenHandsConfig(workspaceRoot, proxyUrl)
}

/**
 * Merge llm.base_url into OpenHands config.toml.
 * Looks for the file in the workspace root and the user config directory.
 */
async function mergeOpenHandsConfig(workspaceRoot: string, proxyUrl: string): Promise<void> {
  const candidates = [
    path.join(workspaceRoot, 'config.toml'),
    path.join(process.env.HOME ?? '', '.openhands', 'config.toml'),
  ]

  for (const configPath of candidates) {
    let existing = ''
    try {
      existing = await fs.readFile(configPath, 'utf-8')
    } catch {
      // File doesn't exist (or is unreadable) — deliberate fail-open: fall
      // through with `existing` at its '' initialiser so the block below
      // creates a minimal config instead of aborting the whole sync.
    }

    // Inject or update [llm] section with base_url
    if (existing.includes('[llm]')) {
      // Update existing [llm] section
      if (existing.includes('base_url')) {
        existing = existing.replace(
          /^base_url\s*=\s*.*/m,
          `base_url = "${proxyUrl}"`,
        )
      } else {
        existing = existing.replace(
          /\[llm\]/,
          `[llm]\nbase_url = "${proxyUrl}"`,
        )
      }
    } else {
      existing += `\n[llm]\nbase_url = "${proxyUrl}"\n`
    }

    const tmpConfig = configPath + '.intutic-tmp'
    await fs.mkdir(path.dirname(configPath), { recursive: true })
    await fs.writeFile(tmpConfig, existing, 'utf-8')
    await fs.rename(tmpConfig, configPath)
    log.info({ action: 'openhands_config_written', path: configPath }, 'OpenHands config.toml updated with proxy base_url')
  }
}
