/**
 * openhandsHooks.ts — OpenHands .openhands/hooks.json injection
 * and llm.base_url proxy write.
 *
 * OpenHands supports PreToolUse, Stop, SessionStart hooks via
 * a JSON file at .openhands/hooks.json in the repository root.
 * The hooks file lives within the agent's sandbox working directory,
 * so we also register it with the drift watcher.
 *
 * LLD #14 — Phase 3 cross-harness defence
 * HLD §3.14 — Three-Tier Defense Cascade
 *
 * @module
 */

import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import * as os from 'node:os'
import { createLogger } from '@intutic/logger'
import { keepOriginal, noteWritten } from '../disconnect/originals.js'
import { newIso } from '@intutic/id'
import { emitShellGate, SHELL_EXTRACT, SHELL_FAIL_CLOSED } from './gateBody.js'
import { parse as parseToml } from 'smol-toml'
import { anthropicBaseUrl, openaiBaseUrl } from '@intutic/shared-types'

const log = createLogger('sync-openhands-hooks')

/**
 * Write .openhands/hooks.json and the pre-tool-check shell script.
 * Also points `[llm] base_url` in ~/.openhands/config.toml at the proxy when
 * that file exists.
 *
 * @param workspaceRoot - Absolute workspace root.
 * @param proxyUrl      - Intutic proxy URL.
 * @param workspaceId   - Workspace ID embedded in hook event payloads.
 */
export async function writeOpenHandsHooks(
  workspaceRoot: string,
  proxyUrl: string,
  workspaceId = '',
): Promise<void> {
  const openhandsDir = path.join(workspaceRoot, '.openhands')
  const hooksPath = path.join(openhandsDir, 'hooks.json')
  // Written whole, over whatever hooks the user had there: kept for disconnect.
  await keepOriginal(hooksPath, workspaceRoot)
  await fs.mkdir(openhandsDir, { recursive: true })

  const hookScriptDir = path.join(workspaceRoot, '.intutic', 'hooks')
  await fs.mkdir(hookScriptDir, { recursive: true })
  const hookScriptPath = path.join(hookScriptDir, 'openhands-check.sh')

  // Ensure hook events log directory exists
  const hookEventsLog = path.join(workspaceRoot, '.intutic', 'events', 'hook-events.jsonl')
  await fs.mkdir(path.join(workspaceRoot, '.intutic', 'events'), { recursive: true })

  // ── Shell hook script ──────────────────────────────────────────────
  // OpenHands passes tool name and input as env vars + JSON body.
  // Exits 2 to block, 0 to allow.
  const hookScript = `#!/usr/bin/env bash
# Intutic OpenHands PreToolUse governance gate.
# Auto-generated by intutic sync-daemon. DO NOT EDIT.
# Proxy: ${proxyUrl}
# Generated: ${newIso()}
set -euo pipefail
${SHELL_FAIL_CLOSED}
INPUT="$(cat)"
${SHELL_EXTRACT}

HOOK_EVENTS_LOG=${JSON.stringify(hookEventsLog)}

# ── Runtime credentials (sourced from ~/.intutic/env/runtime.env) ────────────────────────
# These are defaults, and they are also the only thing standing between
# \`set -u\` and a fatal unbound-variable error: log_event reads all three, so on
# a machine with no runtime.env to source, an unset name kills the gate before
# it can exit 2. Spelling matters — INTUTIC_, never INTUITIC_.
RUNTIME_ENV="$HOME/.intutic/env/runtime.env"
INTUTIC_HOST="https://api.intutic.ai"
INTUTIC_API_KEY=""
INTUTIC_WORKSPACE_ID=${JSON.stringify(workspaceId)}
[ -f "$RUNTIME_ENV" ] && source "$RUNTIME_ENV" 2>/dev/null || true

log_event() {
  local verdict="\$1" tool="\$2" reason="\$3"
  # \`tool\` and \`reason\` carry agent-controlled text — the tool name, and the
  # target path quoted into the block reason — and both are spliced into the
  # JSON string below. Escape first: one unescaped quote yields a line
  # JSON.parse rejects, and drainHookEvents drops malformed lines then wipes the
  # log on a successful drain, so the record of a block is destroyed rather than
  # delayed. A crafted path could otherwise close the string and forge fields.
  tool="\${tool//\\\\/\\\\\\\\}";     tool="\${tool//\\"/\\\\\\"}"
  reason="\${reason//\\\\/\\\\\\\\}"; reason="\${reason//\\"/\\\\\\"}"
  # Every C0 control character, not just newline and carriage return. JSON
  # forbids all of U+0000-U+001F unescaped, so a plain TAB in a filename — no
  # adversary required — was still enough to produce a line JSON.parse rejects.
  # (NUL cannot appear in a bash variable, so the range starts at \\x01.)
  tool="\${tool//[\$'\\x01'-\$'\\x1f']/ }"; reason="\${reason//[\$'\\x01'-\$'\\x1f']/ }"
  # The workspace id is spliced into the same JSON string. It comes from
  # runtime.env on disk rather than from the agent, so it is lower risk — but a
  # value with a quote in it breaks every audit line the same way, and "lower
  # risk" is not "cannot happen" for a file the operator edits by hand.
  local ws="\${INTUTIC_WORKSPACE_ID}"
  ws="\${ws//\\\\/\\\\\\\\}"; ws="\${ws//\\"/\\\\\\"}"; ws="\${ws//[\$'\\x01'-\$'\\x1f']/ }"
  local ts; ts="\$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  local incident_id; incident_id="\$(printf '%s' "\${ts}\${tool}\${INTUTIC_WORKSPACE_ID}" | sha1sum 2>/dev/null | cut -c1-16 || echo \"\$(date +%s)\")"
  local entry="{\\"event\\":\\"\${verdict}\\",\\"toolName\\":\\"\${tool}\\",\\"reason\\":\\"\${reason}\\",\\"workspaceId\\":\\"\${ws}\\",\\"harnessType\\":\\"openhands\\",\\"timestamp\\":\\"\${ts}\\",\\"incidentId\\":\\"\${incident_id}\\"}"
  # Path B: reliable file append
  printf '%s\\n' "\$entry" >> "\$HOOK_EVENTS_LOG" 2>/dev/null || true
  # Path A: fire-and-forget HTTP (non-blocking, near-real-time)
  if [ -n "\$INTUTIC_API_KEY" ]; then
    curl -s -o /dev/null --max-time 3 -X POST \\
      -H "Content-Type: application/json" \\
      -H "Authorization: Bearer \$INTUTIC_API_KEY" \\
      -d "{\\"events\\":[\$entry]}" \\
      "\${INTUTIC_HOST}/api/v1/hook-events" & disown 2>/dev/null || true
  fi
}

${emitShellGate({ harness: "openhands" })}
log_event "tool_allowed" "\$TOOL_NAME" ""
exit 0
`

  const tmpScript = hookScriptPath + '.oh-tmp'
  await fs.writeFile(tmpScript, hookScript, 'utf-8')
  await fs.rename(tmpScript, hookScriptPath)
  await fs.chmod(hookScriptPath, 0o755)

  // ── .openhands/hooks.json ──────────────────────────────────────────
  const hooksConfig = {
    _comment: 'Intutic governance hooks — auto-generated. DO NOT EDIT.',
    _lastSync: newIso(),
    hooks: [
      {
        type: 'PreToolUse',
        command: hookScriptPath,
        failClosed: true,
      },
      {
        type: 'Stop',
        command: `${hookScriptPath} --event stop`,
        failClosed: false,
      },
    ],
  }

  const hooksJson = JSON.stringify(hooksConfig, null, 2) + '\n'
  const tmpHooks = hooksPath + '.intutic-tmp'
  await fs.writeFile(tmpHooks, hooksJson, 'utf-8')
  await fs.rename(tmpHooks, hooksPath)
  await noteWritten(hooksPath, workspaceRoot, hooksJson)

  log.info({ action: 'openhands_hooks_written', path: hooksPath }, 'OpenHands hooks written')

  // ── user-level config.toml llm.base_url ───────────────────────────
  // The workspace config.toml is the adapter's: it merges `[llm] base_url`
  // there (`mergeOpenHandsToml`).
  await mergeUserOpenHandsConfig(proxyUrl)
}

/**
 * Point `[llm] base_url` in `~/.openhands/config.toml` at the proxy, when that
 * file exists. Only that key is set; a file that does not parse is left alone.
 * An empty `proxyUrl` (the settings guard restoring hooks.json) changes
 * nothing.
 */
async function mergeUserOpenHandsConfig(proxyUrl: string): Promise<void> {
  if (!proxyUrl) return
  const configPath = path.join(os.homedir(), '.openhands', 'config.toml')
  let raw: string
  try {
    raw = await fs.readFile(configPath, 'utf-8')
  } catch {
    return
  }
  const next = mergeOpenHandsBaseUrl(raw, proxyUrl)
  if (next === null) {
    log.warn({ action: 'openhands_config_merge_skipped', path: configPath }, `${configPath} is not valid TOML — left untouched`)
    return
  }
  if (next === raw) return
  const tmpConfig = configPath + '.intutic-tmp'
  await keepOriginal(configPath, os.homedir())
  await fs.writeFile(tmpConfig, next, 'utf-8')
  await fs.rename(tmpConfig, configPath)
  log.info({ action: 'openhands_config_written', path: configPath }, 'OpenHands config.toml updated with proxy base_url')
}

// ─── config.toml merge ───────────────────────────────────────────────────────

/** First line of the file earlier adapter versions wrote over config.toml. */
const LEGACY_HEADER = '# Intutic Governance Rules (auto-generated)'

function parsesAsToml(text: string): Record<string, unknown> | null {
  try {
    return parseToml(text) as Record<string, unknown>
  } catch {
    return null
  }
}

/**
 * Tables only OpenHands' own `config.toml` uses, from its configuration
 * template (https://github.com/OpenHands/OpenHands/blob/0.59.0/config.template.toml:
 * `[core]`, `[llm]`, `[agent]`, `[sandbox]`, `[security]`, `[condenser]`,
 * `[kubernetes]`, `[mcp]`, `[model_routing]`). `[llm]`, `[mcp]` and
 * `[security]` are left out: other tools use those names too. `[intutic]` is
 * the table an earlier `intutic connect` wrote.
 */
const OPENHANDS_TABLES = ['core', 'agent', 'sandbox', 'condenser', 'intutic']

/**
 * Whether `config.toml` text is an OpenHands configuration. A file named
 * `config.toml` is also every Hugo site's and many other tools', so the name
 * alone is not evidence.
 */
export function isOpenHandsConfig(raw: string): boolean {
  const parsed = parsesAsToml(raw)
  if (parsed === null) return false
  return OPENHANDS_TABLES.some((t) => typeof parsed[t] === 'object' && parsed[t] !== null && !Array.isArray(parsed[t]))
}

/** Index of the line that starts table `name`, or -1. */
function tableStart(lines: string[], name: string): number {
  return lines.findIndex((l) => l.trim() === `[${name}]`)
}

/** Index just past the last line of the table starting at `start`. */
function tableEnd(lines: string[], start: number): number {
  const next = lines.findIndex((l, i) => i > start && /^\s*\[/.test(l))
  return next === -1 ? lines.length : next
}

/** The proxy URL in the form the configured model's SDK expects. */
function llmBaseUrl(parsed: Record<string, unknown>, proxyUrl: string): string {
  const llm = (parsed['llm'] ?? {}) as Record<string, unknown>
  const model = typeof llm['model'] === 'string' ? llm['model'] : ''
  return /^(anthropic\/|claude)/.test(model) ? anthropicBaseUrl(proxyUrl) : openaiBaseUrl(proxyUrl)
}

/**
 * Set `base_url` inside the `[llm]` table only, adding the table when there
 * is none. A `base_url` in any other table (`[llm.<name>]`, `[mcp]`, …) is
 * not this key and is left as it is.
 */
function setLlmBaseUrl(lines: string[], baseUrl: string): void {
  const baseLine = `base_url = ${JSON.stringify(baseUrl)}`
  const llmStart = tableStart(lines, 'llm')
  if (llmStart === -1) {
    while (lines.length > 0 && lines[lines.length - 1].trim() === '') lines.pop()
    lines.push('', '[llm]', baseLine, '')
    return
  }
  const end = tableEnd(lines, llmStart)
  const existing = lines.findIndex((l, i) => i > llmStart && i < end && /^\s*base_url\s*=/.test(l))
  if (existing !== -1) lines[existing] = baseLine
  else lines.splice(llmStart + 1, 0, baseLine)
}

/**
 * Point `[llm] base_url` in an OpenHands `config.toml` at the proxy and keep
 * the rest of the file. Returns `null` when the text is not valid TOML.
 */
export function mergeOpenHandsBaseUrl(raw: string, proxyUrl: string): string | null {
  const parsed = parsesAsToml(raw)
  if (parsed === null) return null
  const baseUrl = llmBaseUrl(parsed, proxyUrl)
  const lines = raw.split('\n')
  setLlmBaseUrl(lines, baseUrl)
  const next = (lines[0] === '' ? lines.slice(1) : lines).join('\n')
  const check = parsesAsToml(next)
  if (check === null || (check['llm'] as Record<string, unknown> | undefined)?.['base_url'] !== baseUrl) return null
  return next
}

/**
 * Point `[llm] base_url` in the workspace's OpenHands `config.toml` at the
 * proxy, in the form the configured model's SDK expects (LiteLLM appends
 * `/v1/messages` to an Anthropic base and `/chat/completions` to an
 * OpenAI-style one), and keep the rest of the file.
 *
 * Earlier versions also wrote the rule sets into an `[intutic]` table, which
 * OpenHands never reads (the rules now go into a microagent, see the
 * adapter); that table is dropped. Earlier still, versions replaced the
 * whole file, so a file starting with their header holds nothing of the
 * user's and is regenerated.
 *
 * Edited line by line so the user's own settings and comments survive; the
 * result is parsed before it is returned. Returns `null` when the existing
 * file is not valid TOML.
 */
export function mergeOpenHandsToml(raw: string, proxyUrl: string): string | null {
  const source = raw.startsWith(LEGACY_HEADER) ? '' : raw
  if (parsesAsToml(source) === null) return null
  const lines = source.split('\n')
  const oldIntutic = tableStart(lines, 'intutic')
  if (oldIntutic !== -1) {
    lines.splice(oldIntutic, tableEnd(lines, oldIntutic) - oldIntutic)
    while (lines.length > 1 && lines[lines.length - 1].trim() === '' && lines[lines.length - 2].trim() === '') lines.pop()
  }
  return mergeOpenHandsBaseUrl(lines.join('\n'), proxyUrl)
}
