/**
 * openWebuiHooks.ts — Open WebUI governance filter generator.
 *
 * Open WebUI uses Python `inlet()` filter functions loaded from the admin UI.
 * This module generates an `intutic-governance-filter.py` file and an env
 * snippet with installation instructions.
 *
 * The generated Python filter:
 *   - Reads ~/.intutic/env/runtime.env at call time for fresh credentials.
 *   - Logs every prompt (inlet) via dual-path: file append + urllib.request.
 *   - Generates incidentId via hashlib.sha1.
 *
 * LLD #14 — Phase 3 cross-harness defence (Gap 3, WS-B)
 * HLD §3.14 — Three-Tier Defense Cascade (Tier 1 Native Gating)
 *
 * @module
 */

import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import * as os from 'node:os'
import { createLogger } from '@intutic/logger'
import { newIso } from '@intutic/id'

const log = createLogger('sync-open-webui-hooks')

/** Default target directory for the Open WebUI governance filter. */
const OPEN_WEBUI_DIR = path.join(os.homedir(), '.open-webui')

// ─── Python filter template ───────────────────────────────────────────────────

function buildOpenWebuiFilter(workspaceId: string, proxyUrl: string): string {
  return `"""
Intutic Governance Filter for Open WebUI.
Auto-generated by intutic sync-daemon. DO NOT EDIT.
Generated: ${newIso()}
Proxy: ${proxyUrl}
Workspace: ${workspaceId}
"""
import os
import json
import urllib.request
import hashlib
import time
from typing import Optional
from datetime import datetime, timezone

WORKSPACE_ID = ${JSON.stringify(workspaceId)}
HARNESS_TYPE = "open-webui"
RUNTIME_ENV_PATH = os.path.expanduser("~/.intutic/env/runtime.env")


def _load_runtime_env():
    env = {
        "INTUTIC_HOST": "https://api.intutic.ai",
        "INTUTIC_API_KEY": "",
        "INTUTIC_WORKSPACE_ID": WORKSPACE_ID,
    }
    try:
        with open(RUNTIME_ENV_PATH) as f:
            for line in f:
                line = line.strip()
                if "=" in line and not line.startswith("#"):
                    k, v = line.split("=", 1)
                    env[k.strip()] = v.strip()
    except Exception:
        pass
    return env


def _log_event(env: dict, event: dict):
    """Dual-path log: Path B file append + Path A urllib.request (fire-and-forget)."""
    # Path B — reliable file append
    try:
        log_path = os.path.expanduser("~/.intutic/events/open-webui-hook-events.jsonl")
        os.makedirs(os.path.dirname(log_path), exist_ok=True)
        with open(log_path, "a") as f:
            f.write(json.dumps(event) + "\\n")
    except Exception:
        pass

    # Path A — fire-and-forget HTTP POST
    if env.get("INTUTIC_API_KEY"):
        try:
            body = json.dumps({"events": [event]}).encode()
            req = urllib.request.Request(
                f"{env['INTUTIC_HOST']}/api/v1/hook-events",
                data=body,
                headers={
                    "Content-Type": "application/json",
                    "Authorization": f"Bearer {env['INTUTIC_API_KEY']}",
                },
                method="POST",
            )
            urllib.request.urlopen(req, timeout=3)
        except Exception:
            pass


class Filter:
    """Intutic governance inlet filter for Open WebUI."""

    def inlet(self, body: dict, __user__: Optional[dict] = None) -> dict:
        """Called before every prompt — log to Intutic governance."""
        env = _load_runtime_env()
        ts = datetime.now(timezone.utc).isoformat()
        model = body.get("model", "unknown")
        workspace_id = env["INTUTIC_WORKSPACE_ID"]
        incident_id = hashlib.sha1(
            f"{ts}{model}{workspace_id}".encode()
        ).hexdigest()[:16]
        event = {
            "event": "tool_allowed",
            "toolName": f"open-webui:{model}",
            "reason": "",
            "workspaceId": workspace_id,
            "harnessType": HARNESS_TYPE,
            "timestamp": ts,
            "incidentId": incident_id,
        }
        _log_event(env, event)
        return body

    def outlet(self, body: dict, __user__: Optional[dict] = None) -> dict:
        """Pass-through outlet — no modification required."""
        return body
`
}

// ─── Main export ──────────────────────────────────────────────────────────────

/**
 * Write the Open WebUI governance filter and installation instructions.
 *
 *  1. Creates `~/.open-webui/intutic-governance-filter.py` — Python inlet filter.
 *  2. Writes `.intutic/env/open-webui.env` with installation instructions.
 *
 * Safe to call repeatedly — uses atomic rename (`.intutic-tmp` → final path).
 *
 * @param workspaceRoot - Absolute workspace root path.
 * @param proxyUrl      - Intutic proxy URL embedded in filter header.
 * @param workspaceId   - Workspace ID embedded in every filter event payload.
 */
export async function writeOpenWebuiHooks(
  workspaceRoot: string,
  proxyUrl: string,
  workspaceId = '',
): Promise<void> {
  // ── 1. Ensure directories ──────────────────────────────────────────────────

  const envDir = path.join(workspaceRoot, '.intutic', 'env')

  await Promise.all([
    fs.mkdir(OPEN_WEBUI_DIR, { recursive: true }),
    fs.mkdir(envDir, { recursive: true }),
  ])

  // ── 2. Write Python filter (atomic) ───────────────────────────────────────

  const filterPath = path.join(OPEN_WEBUI_DIR, 'intutic-governance-filter.py')
  const tmpFilter = filterPath + '.intutic-tmp'
  await fs.writeFile(tmpFilter, buildOpenWebuiFilter(workspaceId, proxyUrl), 'utf-8')
  await fs.rename(tmpFilter, filterPath)

  log.info(
    { action: 'open_webui_filter_written', path: filterPath },
    'Open WebUI governance filter written',
  )

  // ── 3. Write .intutic/env/open-webui.env (atomic) ─────────────────────────

  const envContent = [
    `# Intutic Open WebUI governance env — auto-generated ${newIso()}`,
    `# This file is managed by the Intutic sync-daemon. DO NOT EDIT.`,
    `INTUTIC_OPEN_WEBUI_FILTER=${filterPath}`,
    `# To install: copy the filter file to your Open WebUI Functions directory via the admin UI.`,
    `# Admin > Settings > Functions > + New Function > paste content of:`,
    `#   ${filterPath}`,
    workspaceId ? `INTUTIC_WORKSPACE_ID=${workspaceId}` : '',
  ].filter((l) => l !== '').join('\n') + '\n'

  const envFilePath = path.join(envDir, 'open-webui.env')
  const tmpEnv = envFilePath + '.intutic-tmp'
  await fs.writeFile(tmpEnv, envContent, 'utf-8')
  await fs.rename(tmpEnv, envFilePath)

  log.info(
    { action: 'open_webui_env_written', path: envFilePath },
    'Open WebUI env snippet written',
  )
}
