/**
 * piHooks.ts — Pi (earendil-works/pi) coding agent governance hook injection.
 *
 * Pi uses:
 * - `~/.pi/hooks.json` for PreToolUse hook matchers (stdin JSON, exit 2 = block)
 * - `~/.pi/models.json` for per-provider base URL routing
 *
 * This module:
 * 1. Writes/merges `~/.pi/hooks.json` with intutic-governance hook entries.
 * 2. Writes/merges `~/.pi/models.json` to redirect LLM providers via proxyUrl.
 * 3. Writes `~/.intutic/hooks/pi-check.sh` — dual-path bash governance hook.
 * 4. Writes `.intutic/env/pi.env` — env snippet for IDE/shell integration.
 *
 * WS-C3 — Pi harness (Phase 3 cross-harness defence)
 * LLD #14 — Phase 3 cross-harness defence (Gap 3)
 * HLD §3.14 — Three-Tier Defense Cascade (Tier 1 Native Gating)
 *
 * @module
 */

import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import * as os from 'node:os'
import { createLogger } from '@intutic/logger'
import { newIso } from '@intutic/id'
import { emitShellGate, SHELL_EXTRACT, SHELL_FAIL_CLOSED } from './gateBody.js'

const log = createLogger('sync-pi-hooks')

/** Path to the Pi hooks config. */
const PI_HOOKS_CONFIG = path.join(os.homedir(), '.pi', 'hooks.json')

/** Path to the Pi models config. */
const PI_MODELS_CONFIG = path.join(os.homedir(), '.pi', 'models.json')

/** Governance-sensitive paths that the hook gate protects. */
// ─── Pi hook entry types ──────────────────────────────────────────────────────

interface PiHookCommand {
  type: 'command'
  command: string
}

interface PiHookMatcher {
  matcher: string
  hooks: PiHookCommand[]
}

interface PiHooksConfig {
  hooks?: {
    PreToolUse?: PiHookMatcher[]
    [key: string]: unknown
  }
  [key: string]: unknown
}

interface PiProvider {
  baseUrl?: string
  [key: string]: unknown
}

interface PiModelsConfig {
  providers?: Record<string, PiProvider>
  [key: string]: unknown
}

// ─── Bash hook script template ────────────────────────────────────────────────

function buildPiCheckScript(
  proxyUrl: string,
  workspaceRoot: string,
  workspaceId: string,
): string {
  const hookEventsLog = path.join(workspaceRoot, '.intutic', 'events', 'hook-events.jsonl')
  const runtimeEnv = path.join(os.homedir(), '.intutic', 'env', 'runtime.env')
  return `#!/usr/bin/env bash
# Intutic Pi (earendil-works/pi) PreToolUse governance gate.
# Auto-generated by intutic sync-daemon. DO NOT EDIT.
# Proxy: ${proxyUrl}
# Generated: ${newIso()}
# Workspace: ${workspaceId}
set -euo pipefail
${SHELL_FAIL_CLOSED}
# Source runtime credentials (never embedded in this file)
if [ -f "${runtimeEnv}" ]; then
  # shellcheck disable=SC1090
  source "${runtimeEnv}"
fi

INTUTIC_HOST="\${INTUTIC_HOST:-https://api.intutic.ai}"
INTUTIC_API_KEY="\${INTUTIC_API_KEY:-}"
INTUTIC_WORKSPACE_ID="\${INTUTIC_WORKSPACE_ID:-${workspaceId}}"

INPUT="$(cat)"
${SHELL_EXTRACT}

HOOK_EVENTS_LOG="${hookEventsLog}"

log_event() {
  local verdict="$1" tool="$2" reason="$3"
  # \`tool\`, \`reason\` and \`SESSION_ID\` carry agent-controlled text — the tool
  # name, the target path quoted into the block reason, and a field lifted
  # straight out of the hook's stdin — and all three are spliced into the JSON
  # string below. Escape first: one unescaped quote yields a line JSON.parse
  # rejects, and drainHookEvents drops malformed lines then wipes the log on a
  # successful drain, so the record of a block is destroyed rather than delayed.
  # A crafted path could otherwise close the string and forge fields.
  tool="\${tool//\\\\/\\\\\\\\}";     tool="\${tool//\\"/\\\\\\"}"
  reason="\${reason//\\\\/\\\\\\\\}"; reason="\${reason//\\"/\\\\\\"}"
  # Every C0 control character, not just newline and carriage return. JSON
  # forbids all of U+0000-U+001F unescaped, so a plain TAB in a filename — no
  # adversary required — was still enough to produce a line JSON.parse rejects.
  # (NUL cannot appear in a bash variable, so the range starts at \\x01.)
  tool="\${tool//[\$'\\x01'-\$'\\x1f']/ }"; reason="\${reason//[\$'\\x01'-\$'\\x1f']/ }"
  # The workspace id is spliced into the same JSON string. It comes from
  # runtime.env on disk rather than from the agent, so it is lower risk — but a
  # value with a quote in it breaks every audit line the same way, and "lower
  # risk" is not "cannot happen" for a file the operator edits by hand.
  local ws="\${INTUTIC_WORKSPACE_ID}"
  ws="\${ws//\\\\/\\\\\\\\}"; ws="\${ws//\\"/\\\\\\"}"; ws="\${ws//[\$'\\x01'-\$'\\x1f']/ }"
  local sid="\$SESSION_ID"
  sid="\${sid//\\\\/\\\\\\\\}"; sid="\${sid//\\"/\\\\\\"}"
  sid="\${sid//\$'\\n'/ }";     sid="\${sid//\$'\\r'/ }"
  local ts; ts="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  # incidentId = sha1(timestamp + toolName + workspaceId).slice(0,16)
  local incident_id; incident_id="$(printf '%s' "\${ts}\${tool}\${INTUTIC_WORKSPACE_ID}" | sha1sum 2>/dev/null | cut -c1-16 || echo "$(date +%s)")"
  local entry="{\\"event\\":\\"\${verdict}\\",\\"toolName\\":\\"\${tool}\\",\\"reason\\":\\"\${reason}\\",\\"workspaceId\\":\\"\${ws}\\",\\"harnessType\\":\\"pi\\",\\"incidentId\\":\\"\${incident_id}\\",\\"timestamp\\":\\"\${ts}\\"\${sid:+,\\"sessionId\\":\\"\${sid}\\"}}"
  # Path B: reliable file append (sync-daemon drains on FSEvents change)
  printf '%s\\n' "\$entry" >> "\$HOOK_EVENTS_LOG" 2>/dev/null || true
  # Path A: fire-and-forget HTTP POST (near-real-time dashboard, non-blocking)
  if [ -n "\$INTUTIC_API_KEY" ]; then
    curl -s -o /dev/null --max-time 3 -X POST \\
      -H "Content-Type: application/json" \\
      -H "Authorization: Bearer \$INTUTIC_API_KEY" \\
      -d "{\\"events\\":[\$entry]}" \\
      "\${INTUTIC_HOST}/api/v1/hook-events" & disown 2>/dev/null || true
  fi
}

${emitShellGate({ harness: "pi" })}
log_event "tool_allowed" "$TOOL_NAME" ""
exit 0
`
}

// ─── Pi hooks.json merge ──────────────────────────────────────────────────────

/**
 * Build the 4 canonical Pi PreToolUse hook matchers pointing at the given
 * hook script path. The wildcard `.*` matcher catches all tools not matched
 * by the more specific matchers above it.
 */
function buildPiHookMatchers(hookScriptPath: string): PiHookMatcher[] {
  return [
    { matcher: 'Bash', hooks: [{ type: 'command', command: hookScriptPath }] },
    { matcher: 'Edit', hooks: [{ type: 'command', command: hookScriptPath }] },
    { matcher: 'Write', hooks: [{ type: 'command', command: hookScriptPath }] },
    { matcher: '.*', hooks: [{ type: 'command', command: hookScriptPath }] },
  ]
}

/**
 * Merge Pi hooks.json — upsert intutic-governance entries under
 * `hooks.PreToolUse`. Existing entries with our command path are filtered out
 * then re-added so there are no duplicates.
 */
function mergePiHooks(existing: PiHooksConfig, hookScriptPath: string): PiHooksConfig {
  const preToolUse = existing.hooks?.PreToolUse ?? []

  // Filter out any existing entries that reference our hook script
  const filtered = preToolUse.filter(
    (m) => !m.hooks.some((h) => h.command === hookScriptPath),
  )

  return {
    ...existing,
    hooks: {
      ...(existing.hooks ?? {}),
      PreToolUse: [...filtered, ...buildPiHookMatchers(hookScriptPath)],
    },
  }
}

// ─── Pi models.json merge ─────────────────────────────────────────────────────

/**
 * Merge Pi models.json — update existing providers' baseUrl and add
 * missing providers. The three canonical providers are anthropic, openai,
 * and google.
 */
function mergePiModels(existing: PiModelsConfig, proxyUrl: string): PiModelsConfig {
  const providers = existing.providers ?? {}
  const targetProviders = ['anthropic', 'openai', 'google']

  const mergedProviders: Record<string, PiProvider> = { ...providers }
  for (const provider of targetProviders) {
    mergedProviders[provider] = {
      ...(providers[provider] ?? {}),
      baseUrl: proxyUrl,
    }
  }

  return {
    ...existing,
    providers: mergedProviders,
  }
}

// ─── Main export ──────────────────────────────────────────────────────────────

/**
 * Write the Pi governance hook script, merge hooks.json and models.json,
 * and write the env snippet.
 *
 * Safe to call repeatedly — uses atomic rename so partial writes never
 * leave a corrupt state.
 *
 * @param workspaceRoot - Absolute workspace root path.
 * @param proxyUrl      - Intutic proxy URL for LLM provider routing.
 * @param workspaceId   - Workspace ID embedded in every hook event payload.
 */
export async function writePiHooks(
  workspaceRoot: string,
  proxyUrl: string,
  workspaceId = '',
): Promise<void> {
  // ── 1. Ensure directories ──────────────────────────────────────────────────

  const globalHookDir = path.join(os.homedir(), '.intutic', 'hooks')
  const hookEventsDir = path.join(workspaceRoot, '.intutic', 'events')
  const envDir = path.join(workspaceRoot, '.intutic', 'env')
  const piDir = path.join(os.homedir(), '.pi')

  await Promise.all([
    fs.mkdir(globalHookDir, { recursive: true }),
    fs.mkdir(hookEventsDir, { recursive: true }),
    fs.mkdir(envDir, { recursive: true }),
    fs.mkdir(piDir, { recursive: true }),
  ])

  // ── 2. Write bash hook script ──────────────────────────────────────────────

  const hookScriptPath = path.join(globalHookDir, 'pi-check.sh')
  const tmpScript = hookScriptPath + '.intutic-tmp'
  await fs.writeFile(tmpScript, buildPiCheckScript(proxyUrl, workspaceRoot, workspaceId), 'utf-8')
  await fs.rename(tmpScript, hookScriptPath)
  await fs.chmod(hookScriptPath, 0o755)

  log.info({ action: 'pi_hook_script_written', path: hookScriptPath }, 'Pi hook script written')

  // ── 3. Write/merge ~/.pi/hooks.json ───────────────────────────────────────

  let existingHooks: PiHooksConfig = {}
  try {
    const raw = await fs.readFile(PI_HOOKS_CONFIG, 'utf-8')
    existingHooks = JSON.parse(raw) as PiHooksConfig
  } catch {
    // File doesn't exist or is unparseable — start fresh
  }

  const mergedHooks = mergePiHooks(existingHooks, hookScriptPath)

  const tmpHooks = PI_HOOKS_CONFIG + '.intutic-tmp'
  await fs.writeFile(tmpHooks, JSON.stringify(mergedHooks, null, 2) + '\n', 'utf-8')
  await fs.rename(tmpHooks, PI_HOOKS_CONFIG)

  log.info(
    { action: 'pi_hooks_written', path: PI_HOOKS_CONFIG },
    'Pi hooks.json written',
  )

  // ── 4. Write/merge ~/.pi/models.json ──────────────────────────────────────

  let existingModels: PiModelsConfig = {}
  try {
    const raw = await fs.readFile(PI_MODELS_CONFIG, 'utf-8')
    existingModels = JSON.parse(raw) as PiModelsConfig
  } catch {
    // File doesn't exist or is unparseable — start fresh
  }

  const mergedModels = mergePiModels(existingModels, proxyUrl)

  const tmpModels = PI_MODELS_CONFIG + '.intutic-tmp'
  await fs.writeFile(tmpModels, JSON.stringify(mergedModels, null, 2) + '\n', 'utf-8')
  await fs.rename(tmpModels, PI_MODELS_CONFIG)

  log.info(
    { action: 'pi_models_written', path: PI_MODELS_CONFIG },
    'Pi models.json written',
  )

  // ── 5. Write env snippet ───────────────────────────────────────────────────

  const envSnippet = [
    `# Intutic pi governance env`,
    `INTUTIC_PI_HOOK=~/.intutic/hooks/pi-check.sh`,
    `INTUTIC_PI_HOOKS_CONFIG=~/.pi/hooks.json`,
    `INTUTIC_PI_MODELS_CONFIG=~/.pi/models.json`,
    `OPENAI_BASE_URL=${proxyUrl}`,
    `ANTHROPIC_BASE_URL=${proxyUrl}`,
  ].join('\n') + '\n'

  const envFilePath = path.join(envDir, 'pi.env')
  const tmpEnv = envFilePath + '.intutic-tmp'
  await fs.writeFile(tmpEnv, envSnippet, 'utf-8')
  await fs.rename(tmpEnv, envFilePath)

  log.info(
    { action: 'pi_env_written', path: envFilePath },
    'Pi env snippet written',
  )
}
