/**
 * piHooks.ts — Pi (earendil-works/pi) extension gate and provider routing.
 *
 * Pi has no hook file. Its hooks are extensions: TypeScript or JavaScript
 * modules it loads into its own process from `~/.pi/agent/extensions/` (and a
 * trusted project's `.pi/extensions/`), each a default-exported factory that
 * receives the `ExtensionAPI`. Earlier versions of this writer registered a
 * Claude-Code-style `PreToolUse` hook in `~/.pi/hooks.json`, a file Pi never
 * reads, and pointed providers at the proxy in `~/.pi/models.json`, where Pi
 * does not look either: both live in the agent directory, `~/.pi/agent`.
 * Sources, at earendil-works/pi 6fb2e7815167e6b19006fc526d1a5d0f5f998787:
 *
 * - discovery: `packages/coding-agent/src/core/extensions/loader.ts`
 *   (`discoverExtensionsInDir`: direct `*.ts`/`*.js` files, or `<dir>/index.*`;
 *   loaded with jiti, `{ default: true }`, and the default export must be a
 *   function), `packages/coding-agent/docs/configuration.md` (the agent
 *   directory and `models.json`);
 * - the hook: `pi.on("tool_call", handler)`, with
 *   `event = { type: "tool_call", toolName, toolCallId, input }`, refused by
 *   returning `{ block: true, reason }` (`core/extensions/types.ts`,
 *   `ToolCallEventResult`). The agent loop turns the reason into the error
 *   result the model reads (`packages/agent/src/agent-loop.ts`).
 * - failure: "A `tool_call` handler failure blocks the tool as a fail-safe"
 *   (`docs/extensions.md`); `ExtensionRunner.emitToolCall` awaits each
 *   handler with no timeout (`core/extensions/runner.ts`), so a handler that
 *   hangs hangs Pi. The gate body therefore runs under `GATE_DEADLINE_MS`,
 *   from the start of each call, and refuses past it.
 *
 * The extension embeds the shared `emitJsGate` body (`'throw'` contract) and
 * returns Pi's block result for the refusal it throws; any other fault is a
 * block too. Pi names MCP tools `mcp__<server>__<tool>` already
 * (`docs/mcp.md`), and calls a tool makes through `ctx.executeTool()` pass
 * through `tool_call` handlers like the model's own (`docs/extensions.md`).
 *
 * The file is ESM with `createRequire`, the shape the OpenCode plugin uses:
 * Node (Pi needs 22.19 or later) detects the module syntax, and jiti
 * transforms the file where native loading fails and in Pi's compiled binary
 * (`core/extensions/jiti-loader.ts`, `loader.ts`).
 *
 * Only the default agent directory is written. A user who moves it with
 * `PI_CODING_AGENT_DIR` copies the extension there (the Pi integration page
 * says so).
 *
 * @module
 */

import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import * as os from 'node:os'
import { createLogger } from '@intutic/logger'
import { keepOriginal, writeOwnedFile } from '../disconnect/originals.js'
import { newIso } from '@intutic/id'
import { emitJsGate, REVIEW_REQUESTS_BASENAME } from './gateBody.js'
import { readJsonObjectForMerge } from './jsonMergeTarget.js'
import { anthropicBaseUrl, openaiBaseUrl } from '@intutic/shared-types'

const log = createLogger('sync-pi-hooks')

/** Pi's default agent directory, relative to the home directory. */
export const PI_AGENT_DIR = path.join('.pi', 'agent')

/** The extension file, relative to the home directory. */
export const PI_EXTENSION_FILE = path.join(PI_AGENT_DIR, 'extensions', 'intutic-governance.js')

/** The first line of the extension's header, which disconnect recognises it by. */
export const PI_EXTENSION_MARKER = 'Intutic Pi governance extension.'

interface PiProvider {
  baseUrl?: string
  [key: string]: unknown
}

interface PiModelsConfig {
  providers?: Record<string, PiProvider>
  [key: string]: unknown
}

// ─── The extension ───────────────────────────────────────────────────────────

export function buildPiExtension(proxyUrl: string, workspaceRoot: string, workspaceId: string): string {
  const hookEventsLog = path.join(workspaceRoot, '.intutic', 'events', 'hook-events.jsonl')
  return `/**
 * ${PI_EXTENSION_MARKER}
 * Auto-generated by intutic sync-daemon. DO NOT EDIT.
 * Proxy: ${proxyUrl}
 * Generated: ${newIso()}
 *
 * A tool_call handler Pi loads from its extensions directory. Refuses a tool
 * call by returning { block: true, reason }. See
 * services/sync-daemon/src/harness/piHooks.ts.
 */
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const path = require('path');
const os = require('os');
const fs = require('fs');
const crypto = require('crypto');
const https = require('https');

// Runtime credentials, read when Pi loads the extension.
const _runtimeEnvPath = path.join(os.homedir(), '.intutic', 'env', 'runtime.env');
let _intuticHost = 'https://api.intutic.ai', _intuticKey = '', _intuticWsId = ${JSON.stringify(workspaceId)};
try {
  fs.readFileSync(_runtimeEnvPath, 'utf-8').split('\\n').forEach(line => {
    const eq = line.indexOf('='); if (eq < 0) return;
    const k = line.slice(0, eq).trim(), v = line.slice(eq + 1).trim();
    if (k === 'INTUTIC_HOST' && v) _intuticHost = v;
    if (k === 'INTUTIC_API_KEY' && v) _intuticKey = v;
    if (k === 'INTUTIC_WORKSPACE_ID' && v) _intuticWsId = v;
  });
} catch {}

${emitJsGate({ harness: 'pi', contract: 'throw', reviewRequestFile: path.join(workspaceRoot, '.intutic', 'events', REVIEW_REQUESTS_BASENAME) })}

let _intuticSessionId = '';
function logEvent(verdict, toolName, reason) {
  try {
    const ts = new Date().toISOString();
    const incidentId = crypto.createHash('sha1').update(ts + toolName + _intuticWsId).digest('hex').slice(0, 16);
    // The event's id: random, made once here, and resent with the line it is
    // written into, so the control plane processes the event once.
    const eventId = crypto.randomBytes(16).toString('hex');
    const entry = JSON.stringify({
      event: verdict,
      toolName, reason: reason || '',
      workspaceId: _intuticWsId,
      harnessType: 'pi',
      timestamp: ts,
      incidentId,
      eventId,
      ...(_intuticSessionId ? { sessionId: _intuticSessionId } : {}),
    }) + '\\n';
    const logPath = ${JSON.stringify(hookEventsLog)};
    try { fs.mkdirSync(path.dirname(logPath), { recursive: true }); } catch {}
    fs.appendFileSync(logPath, entry, { flag: 'a' });
    if (_intuticKey) {
      try {
        const body = JSON.stringify({ events: [JSON.parse(entry)] });
        const urlObj = new URL('/api/v1/hook-events', _intuticHost);
        const isHttps = urlObj.protocol === 'https:';
        const mod = isHttps ? https : require('http');
        const req = mod.request({ hostname: urlObj.hostname, port: urlObj.port || (isHttps ? 443 : 80), path: urlObj.pathname, method: 'POST', headers: { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body), 'Authorization': 'Bearer ' + _intuticKey } });
        req.on('error', () => { /* fire-and-forget */ });
        req.write(body); req.end();
      } catch { /* never crash the hook */ }
    }
  } catch { /* never crash the hook */ }
}

/**
 * One tool call. Returns to allow; throws '[Intutic Governance] …' to refuse.
 * Input that is not an object is refused outright: the gate reads paths and
 * commands out of it, and a shape it cannot read is not one it can allow.
 */
function intuticEvaluate(event, ctx) {
  _intuticSessionId = '';
  try { _intuticSessionId = String(ctx.sessionManager.getSessionId() || ''); } catch (e) {}
  const tool = String((event && event.toolName) || 'tool');
  const input = event && event.input;
  if (!input || typeof input !== 'object' || Array.isArray(input)) {
    const reason = '[Intutic Governance] BLOCKED: tool "' + tool + '" was called with input the gate cannot read (' +
      (input === null ? 'null' : typeof input) + '); refusing rather than allowing a call it cannot evaluate.';
    try { logEvent('tool_blocked', tool, reason); } catch (e) {}
    throw new Error(reason);
  }
  const target = input.path || input.file_path || input.filePath || input.target || '';
  const command = input.command || input.cmd || input.script || '';
  intuticGate(tool, target, command, logEvent, _intuticWsId, input, _intuticSessionId);
  logEvent('tool_allowed', tool, '');
}

/**
 * Fail closed: a fault inside the gate is a refusal, never an allow. The gate
 * body reports a refusal on stderr for the hook processes; inside Pi that
 * line would land in the middle of the terminal UI, and the reason reaches
 * the user in the tool result anyway, so stderr is muted for the call. The
 * evaluation is synchronous, so nothing else logs in between.
 */
function toolCall(event, ctx) {
  const consoleError = console.error;
  console.error = () => {};
  try {
    intuticEvaluate(event, ctx);
    return undefined;
  } catch (err) {
    let reason = String((err && err.message) || err);
    if (reason.indexOf('[Intutic Governance]') !== 0) {
      reason = '[Intutic Governance] BLOCKED: gate fault (failing closed): ' + reason;
      try { logEvent('tool_blocked', String((event && event.toolName) || 'unknown'), reason); } catch (e) {}
    }
    return { block: true, reason };
  } finally {
    console.error = consoleError;
  }
}

export default function intuticGovernance(pi) {
  pi.on('tool_call', toolCall);
}
`
}

// ─── <agent-dir>/models.json ─────────────────────────────────────────────────

/**
 * Merge Pi models.json — point the anthropic and openai providers at the
 * proxy, each with the base URL its SDK expects (the Anthropic SDK appends
 * `/v1/messages`, the OpenAI one `/chat/completions`). Google is left alone:
 * the proxy does not serve the Gemini API, so routing it there would break it.
 * Every other provider and key is kept. A provider entry may carry `baseUrl`
 * alone (`ProviderConfigSchema` in `packages/coding-agent/src/core/model-config.ts`).
 */
export function mergePiModels(existing: PiModelsConfig, proxyUrl: string): PiModelsConfig {
  const providers = existing.providers ?? {}
  const targets: Record<string, string> = {
    anthropic: anthropicBaseUrl(proxyUrl),
    openai: openaiBaseUrl(proxyUrl),
  }

  const mergedProviders: Record<string, PiProvider> = { ...providers }
  for (const [provider, baseUrl] of Object.entries(targets)) {
    mergedProviders[provider] = {
      ...(providers[provider] ?? {}),
      baseUrl,
    }
  }

  return {
    ...existing,
    providers: mergedProviders,
  }
}

// ─── Main export ──────────────────────────────────────────────────────────────

/**
 * Write the Pi governance extension into `~/.pi/agent/extensions/` and merge
 * the proxy routing into `~/.pi/agent/models.json`.
 *
 * Safe to call repeatedly: atomic renames and a fixed file name, so repeated
 * syncs replace rather than stack. Pi discovers the extension by scanning the
 * directory; nothing registers it.
 *
 * @param workspaceRoot - Absolute workspace root path.
 * @param proxyUrl      - Intutic proxy URL for LLM provider routing.
 * @param workspaceId   - Workspace ID embedded in every hook event payload.
 */
export async function writePiHooks(
  workspaceRoot: string,
  proxyUrl: string,
  workspaceId = '',
): Promise<void> {
  await fs.mkdir(path.join(workspaceRoot, '.intutic', 'events'), { recursive: true })

  const extensionPath = path.join(os.homedir(), PI_EXTENSION_FILE)
  await writeOwnedFile(extensionPath, workspaceRoot, buildPiExtension(proxyUrl, workspaceRoot, workspaceId))
  log.info({ action: 'pi_extension_written', path: extensionPath }, 'Pi governance extension written')

  // A file that is not a plain JSON object is left untouched (and reported)
  // rather than replaced with only the Intutic entries.
  const modelsPath = path.join(os.homedir(), PI_AGENT_DIR, 'models.json')
  const existingModels = await readJsonObjectForMerge(modelsPath) as PiModelsConfig | null
  if (existingModels !== null) {
    await keepOriginal(modelsPath, workspaceRoot)
    await fs.mkdir(path.dirname(modelsPath), { recursive: true })
    const tmp = modelsPath + '.intutic-tmp'
    await fs.writeFile(tmp, JSON.stringify(mergePiModels(existingModels, proxyUrl), null, 2) + '\n', 'utf-8')
    await fs.rename(tmp, modelsPath)
    log.info({ action: 'pi_models_written', path: modelsPath }, 'Pi models.json written')
  }
}
