/**
 * rooCodeHooks.ts — Roo Code (ZooCode) governance hook generator.
 *
 * Roo Code uses `.roorules` for SOP rules and `.roomodes` for custom modes.
 * For hook interception, it reads hook config from `.roorules/hooks/hooks.json`.
 * The hook result format uses stdout JSON: {"cancel": true, "errorMessage": "..."}
 * rather than exit codes (unlike Claude Code's exit 2).
 *
 * Hook events are written via dual-path logEvent:
 *   Path B (reliable)  — synchronous append to .intutic/events/roo-hook-events.jsonl
 *   Path A (telemetry) — fire-and-forget https.request to the control plane
 *
 * LLD #14 — Phase 3 cross-harness defence (Gap 3, WS-B)
 * HLD §3.14 — Three-Tier Defense Cascade (Tier 1 Native Gating)
 *
 * @module
 */

import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import * as os from 'node:os'
import { createLogger } from '@intutic/logger'
import { newIso } from '@intutic/id'

const log = createLogger('sync-roo-code-hooks')

/** Governance-sensitive paths that the hook gate protects. */
const PROTECTED_PATHS = [
  path.join(os.homedir(), '.claude', 'settings.json'),
  path.join(os.homedir(), '.claude', 'settings.local.json'),
  '.claude/settings.json',
  '.claude/settings.local.json',
  '.intutic/hooks',
  '.intutic/integrity.json',
  '.intutic/context_integrity.json',
  '.roorules/hooks',
]

// ─── Node.js hook script template ─────────────────────────────────────────────

function buildRooCheckScript(
  proxyUrl: string,
  workspaceRoot: string,
  workspaceId: string,
): string {
  const hookEventsLog = path.join(workspaceRoot, '.intutic', 'events', 'roo-hook-events.jsonl')
  const runtimeEnvPath = path.join(os.homedir(), '.intutic', 'env', 'runtime.env')

  return `/**
 * Intutic Roo Code PreToolUse execution gate.
 * Auto-generated by intutic sync-daemon. DO NOT EDIT.
 *
 * Block format: stdout JSON {"cancel": true, "errorMessage": "..."}
 * Allow format: stdout JSON {"cancel": false}
 *
 * Dual-path logEvent:
 *   Path B — synchronous file append to roo-hook-events.jsonl
 *   Path A — fire-and-forget https.request to the control plane
 *
 * Proxy: ${proxyUrl}
 * Generated: ${newIso()}
 * Workspace: ${workspaceId}
 */
'use strict';
const path = require('path');
const os = require('os');
const fs = require('fs');
const https = require('https');
const crypto = require('crypto');
const url = require('url');

// ── Runtime env loader (Path A credentials) ──────────────────────────────────
const RUNTIME_ENV_PATH = ${JSON.stringify(runtimeEnvPath)};

function loadRuntimeEnv() {
  const env = {
    INTUTIC_HOST: 'https://api.intutic.ai',
    INTUTIC_API_KEY: '',
    INTUTIC_WORKSPACE_ID: ${JSON.stringify(workspaceId)},
  };
  try {
    const raw = fs.readFileSync(RUNTIME_ENV_PATH, 'utf-8');
    for (const line of raw.split('\\n')) {
      const stripped = line.trim();
      if (!stripped || stripped.startsWith('#') || !stripped.includes('=')) continue;
      const eq = stripped.indexOf('=');
      const k = stripped.slice(0, eq).trim();
      const v = stripped.slice(eq + 1).trim();
      env[k] = v;
    }
  } catch { /* file may not exist yet */ }
  return env;
}

// ── Governance-sensitive paths ────────────────────────────────────────────────
const PROTECTED_PATHS = ${JSON.stringify(PROTECTED_PATHS)};

// ── Dual-path logEvent ────────────────────────────────────────────────────────
const HOOK_EVENTS_LOG = ${JSON.stringify(hookEventsLog)};

function logEvent(env, verdict, toolName, reason) {
  const ts = new Date().toISOString();
  const incidentId = crypto.createHash('sha1')
    .update(ts + toolName + env.INTUTIC_WORKSPACE_ID)
    .digest('hex').slice(0, 16);

  const entry = {
    event: verdict === 'blocked' ? 'tool_blocked' : 'tool_allowed',
    toolName,
    reason: reason || '',
    workspaceId: env.INTUTIC_WORKSPACE_ID,
    harnessType: 'roo-code',
    timestamp: ts,
    incidentId,
  };

  // Path B — reliable file append
  try {
    const dir = path.dirname(HOOK_EVENTS_LOG);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.appendFileSync(HOOK_EVENTS_LOG, JSON.stringify(entry) + '\\n', { flag: 'a' });
  } catch { /* never crash the hook */ }

  // Path A — fire-and-forget https.request
  if (env.INTUTIC_API_KEY) {
    try {
      const body = Buffer.from(JSON.stringify({ events: [entry] }));
      const parsedUrl = url.parse(env.INTUTIC_HOST + '/api/v1/hook-events');
      const req = https.request({
        hostname: parsedUrl.hostname,
        port: parsedUrl.port || 443,
        path: parsedUrl.path,
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Content-Length': body.length,
          'Authorization': 'Bearer ' + env.INTUTIC_API_KEY,
        },
      });
      req.on('error', () => {}); // fire-and-forget
      req.write(body);
      req.end();
    } catch { /* never crash the hook */ }
  }
}

function block(env, toolName, reason) {
  logEvent(env, 'blocked', toolName, reason);
  process.stdout.write(JSON.stringify({ cancel: true, errorMessage: reason }));
  process.exit(0);
}

function allow(env, toolName) {
  logEvent(env, 'allowed', toolName, '');
  process.stdout.write(JSON.stringify({ cancel: false }));
  process.exit(0);
}

// ── Main ──────────────────────────────────────────────────────────────────────
const runtimeEnv = loadRuntimeEnv();
let inputData = '';
process.stdin.on('data', (chunk) => { inputData += chunk; });
process.stdin.on('end', () => {
  try {
    const ctx = JSON.parse(inputData);
    const toolName = (ctx.tool_name || ctx.toolName || '').toLowerCase();
    const toolInput = ctx.tool_input || ctx.toolInput || {};
    const toolInputStr = JSON.stringify(toolInput);

    // 1. Protected-path guard
    if (['edit', 'write', 'multiedit'].includes(toolName)) {
      const targetPath = toolInput.path || toolInput.file_path ||
        toolInput.new_path || toolInput.target || '';
      for (const p of PROTECTED_PATHS) {
        if (targetPath.includes(p) || String(targetPath).startsWith(p)) {
          const reason = 'Attempt to modify governance-protected path: "' + targetPath + '". ' +
            'To change governance policy, update your SOP via the Intutic control plane.';
          block(runtimeEnv, toolName, reason);
          return;
        }
      }
    }

    // 2. Bash/shell command bypass guard
    if (toolName === 'bash') {
      const cmd = toolInput.command || toolInput.cmd || '';
      const BYPASS_PATTERNS = [
        'chflags nouchg',
        'chattr -i',
        'rm -rf .intutic',
        'rm -rf .roorules',
      ];
      for (const pattern of BYPASS_PATTERNS) {
        if (cmd.includes(pattern)) {
          const reason = 'Shell command matches governance bypass pattern: "' + pattern + '"';
          block(runtimeEnv, toolName, reason);
          return;
        }
      }
    }

    allow(runtimeEnv, toolName);
  } catch (err) {
    // Fail closed on parse error
    const env = runtimeEnv;
    logEvent(env, 'blocked', 'unknown', String(err));
    process.stdout.write(JSON.stringify({ cancel: true, errorMessage: '[Intutic] Hook error: ' + String(err) }));
    process.exit(0);
  }
});
`.trim()
}

// ─── .roorules SOP content ────────────────────────────────────────────────────

function buildRooRulesContent(): string {
  return [
    '# Intutic Governance Rules (auto-generated)',
    '# DO NOT EDIT — managed by intutic sync daemon',
    `# Last sync: ${newIso()}`,
    '',
    '## Roo Code SOP Governance',
    '',
    'This workspace is governed by Intutic SOP policies. All tool executions are',
    'monitored and may be blocked according to the active SOPs configured in the',
    'Intutic control plane.',
    '',
    '### Protected Paths',
    '',
    'The following paths must not be modified by any agent:',
    '',
    ...PROTECTED_PATHS.map((p) => `- \`${p}\``),
    '',
    '### Hook Events',
    '',
    'All tool executions are logged to `.intutic/events/roo-hook-events.jsonl`',
    'and forwarded to the Intutic control plane on each sync cycle.',
    '',
  ].join('\n')
}

// ─── Main export ──────────────────────────────────────────────────────────────

/**
 * Write the Roo Code governance hook configuration:
 *  1. `.roorules` — SOP rules in Roo Code markdown format.
 *  2. `.roorules/hooks/hooks.json` — hook config pointing to the Node.js gate.
 *  3. `.intutic/hooks/roo-check.js` — Node.js dual-path hook (stdout cancel JSON).
 *
 * Safe to call repeatedly — uses atomic rename (`.intutic-tmp` → final path).
 *
 * @param workspaceRoot - Absolute workspace root path.
 * @param proxyUrl      - Intutic proxy URL written into the hook script header.
 * @param workspaceId   - Workspace ID embedded in every hook event payload.
 */
export async function writeRooCodeHooks(
  workspaceRoot: string,
  proxyUrl: string,
  workspaceId = '',
): Promise<void> {
  // ── 1. Ensure directories ──────────────────────────────────────────────────

  const hookScriptDir = path.join(workspaceRoot, '.intutic', 'hooks')
  const hookEventsDir = path.join(workspaceRoot, '.intutic', 'events')
  const rooRulesDir = path.join(workspaceRoot, '.roorules')
  const rooHooksDir = path.join(rooRulesDir, 'hooks')

  await Promise.all([
    fs.mkdir(hookScriptDir, { recursive: true }),
    fs.mkdir(hookEventsDir, { recursive: true }),
    fs.mkdir(rooHooksDir, { recursive: true }),
  ])

  // ── 2. Write hook script (atomic) ─────────────────────────────────────────

  const hookScriptPath = path.join(hookScriptDir, 'roo-check.js')
  const tmpScript = hookScriptPath + '.intutic-tmp'
  await fs.writeFile(tmpScript, buildRooCheckScript(proxyUrl, workspaceRoot, workspaceId), 'utf-8')
  await fs.rename(tmpScript, hookScriptPath)

  log.info({ action: 'roo_hook_script_written', path: hookScriptPath }, 'Roo Code hook script written')

  // ── 3. Write .roorules (atomic) ───────────────────────────────────────────

  const rooRulesPath = path.join(workspaceRoot, '.roorules')
  // .roorules is a file (not the directory used for hooks), so we check if
  // it's already a directory and write a README inside it instead.
  let rooRulesIsDir = false
  try {
    const stat = await fs.stat(rooRulesPath)
    rooRulesIsDir = stat.isDirectory()
  } catch {
    // Doesn't exist — write as file
  }

  if (rooRulesIsDir) {
    // Write README.md inside the directory
    const readmePath = path.join(rooRulesPath, 'README.md')
    const tmpReadme = readmePath + '.intutic-tmp'
    await fs.writeFile(tmpReadme, buildRooRulesContent(), 'utf-8')
    await fs.rename(tmpReadme, readmePath)
  } else {
    const tmpRooRules = rooRulesPath + '.intutic-tmp'
    await fs.writeFile(tmpRooRules, buildRooRulesContent(), 'utf-8')
    await fs.rename(tmpRooRules, rooRulesPath)
  }

  log.info({ action: 'roo_rules_written' }, 'Roo Code .roorules written')

  // ── 4. Write .roorules/hooks/hooks.json (atomic) ──────────────────────────

  const hooksJsonPath = path.join(rooHooksDir, 'hooks.json')
  const hooksConfig = {
    hooks: [
      {
        type: 'PreToolUse',
        matcher: '.*',
        command: `node ${hookScriptPath}`,
      },
    ],
  }

  const tmpHooksJson = hooksJsonPath + '.intutic-tmp'
  await fs.writeFile(tmpHooksJson, JSON.stringify(hooksConfig, null, 2) + '\n', 'utf-8')
  await fs.rename(tmpHooksJson, hooksJsonPath)

  log.info(
    { action: 'roo_hooks_json_written', path: hooksJsonPath },
    'Roo Code hooks.json written',
  )
}
