/**
 * windsurfHooks.ts — Windsurf Cascade hooks.json injection.
 *
 * Writes user-level (~/.codeium/windsurf/hooks.json) and workspace-level
 * (.windsurf/hooks.json) governance hooks using the Windsurf Cascade
 * hook system (exit code 2 = block).
 *
 * Also writes the proxy settings into ~/.codeium/windsurf/settings.json
 * so that Windsurf routes HTTP traffic through the Intutic TLS MITM proxy,
 * enabling governance of Cascade AI traffic that has no native base URL override.
 *
 * LLD #14 — Phase 3 cross-harness defence
 * HLD §3.14 — Three-Tier Defense Cascade
 *
 * @module
 */

import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import * as os from 'node:os'
import { createLogger } from '@intutic/logger'
import { newIso } from '@intutic/id'

const log = createLogger('sync-windsurf-hooks')

const WINDSURF_USER_DIR = path.join(os.homedir(), '.codeium', 'windsurf')

const PROTECTED_PATHS = [
  '.codeium/windsurf/hooks.json',
  '.windsurf/hooks.json',
  '.intutic/hooks',
  '.intutic/integrity.json',
  '.claude/settings.json',
  '.cursor/hooks.json',
  '.cline/hooks',
  '.agents/plugins/intutic-governance',
  '.openhands/hooks.json',
]

function buildHooksConfig(hookScriptPath: string) {
  return {
    _comment: 'Intutic governance hooks — auto-generated. DO NOT EDIT.',
    _lastSync: newIso(),
    hooks: {
      beforeShellExecution: {
        command: `node "${hookScriptPath}"`,
        failClosed: true,
      },
      beforeMCPExecution: {
        command: `node "${hookScriptPath}"`,
        failClosed: true,
      },
      beforeFileEdit: {
        command: `node "${hookScriptPath}"`,
        failClosed: true,
      },
    },
  }
}

function buildHookScript(proxyUrl: string, workspaceRoot: string, workspaceId: string): string {
  const hookEventsLog = path.join(workspaceRoot, '.intutic', 'events', 'hook-events.jsonl')
  return `#!/usr/bin/env node
/**
 * Intutic Windsurf governance gate.
 * Auto-generated by intutic sync-daemon. DO NOT EDIT.
 * Proxy: ${proxyUrl}
 * Generated: ${newIso()}
 */
const fs = require('fs');
const crypto = require('crypto');
const https = require('https');

// Runtime credentials
const _runtimeEnvPath = require('path').join(require('os').homedir(), '.intutic', 'env', 'runtime.env');
let _intuticHost = 'https://api.intutic.ai', _intuticKey = '', _intuticWsId = ${JSON.stringify(workspaceId)};
try {
  fs.readFileSync(_runtimeEnvPath, 'utf-8').split('\\n').forEach(line => {
    const eq = line.indexOf('='); if (eq < 0) return;
    const k = line.slice(0, eq).trim(), v = line.slice(eq + 1).trim();
    if (k === 'INTUTIC_HOST' && v) _intuticHost = v;
    if (k === 'INTUTIC_API_KEY' && v) _intuticKey = v;
    if (k === 'INTUTIC_WORKSPACE_ID' && v) _intuticWsId = v;
  });
} catch {}

const PROTECTED_PATHS = ${JSON.stringify(PROTECTED_PATHS)};

function logEvent(verdict, toolName, reason) {
  try {
    const ts = new Date().toISOString();
    const incidentId = crypto.createHash('sha1').update(ts + toolName + _intuticWsId).digest('hex').slice(0, 16);
    const entry = JSON.stringify({
      event: verdict === 'blocked' ? 'tool_blocked' : 'tool_allowed',
      toolName, reason: reason || '',
      workspaceId: _intuticWsId,
      harnessType: 'windsurf',
      timestamp: ts,
      incidentId,
    }) + '\\n';
    fs.appendFileSync(${JSON.stringify(hookEventsLog)}, entry, { flag: 'a' });
    if (_intuticKey) {
      try {
        const body = JSON.stringify({ events: [JSON.parse(entry)] });
        const urlObj = new URL('/api/v1/hook-events', _intuticHost);
        const mod = urlObj.protocol === 'https:' ? https : require('http');
        const req = mod.request({ hostname: urlObj.hostname, port: urlObj.port || 443, path: urlObj.pathname, method: 'POST', headers: { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body), 'Authorization': 'Bearer ' + _intuticKey } });
        req.on('error', () => { /* fire-and-forget */ });
        req.write(body); req.end();
      } catch { /* never crash the hook */ }
    }
  } catch { /* never crash the hook */ }
}

let raw = '';
process.stdin.on('data', (c) => { raw += c; });
process.stdin.on('end', () => {
  try {
    const ctx = JSON.parse(raw);
    const event = (ctx.event || '').toLowerCase();
    const input = ctx.input || ctx;

    const targetPath = input.path || input.file || input.target || '';
    for (const p of PROTECTED_PATHS) {
      if (String(targetPath).includes(p)) {
        const reason = 'Attempt to modify protected path "' + targetPath + '"';
        process.stderr.write('[Intutic Governance] BLOCKED: ' + reason + '\\n');
        logEvent('blocked', 'edit', reason);
        process.exit(2);
      }
    }

    // Scan shell commands for governance bypass patterns
    const command = input.command || input.cmd || '';
    const dangerPatterns = [
      /chflags\\s+nouchg/,
      /chattr\\s+-i\\s+/,
      /chmod\\s+[0-9]*[2367][0-9]*\\s+.*hooks/,
    ];
    for (const pat of dangerPatterns) {
      if (pat.test(command)) {
        const reason = 'Command matches bypass pattern: "' + command + '"';
        process.stderr.write('[Intutic Governance] BLOCKED: ' + reason + '\\n');
        logEvent('blocked', 'bash', reason);
        process.exit(2);
      }
    }

    logEvent('allowed', event || 'tool', '');
    process.exit(0);
  } catch (err) {
    const errMsg = String(err);
    process.stderr.write('[Intutic Governance] Hook error (fail-closed): ' + errMsg + '\\n');
    logEvent('blocked', 'unknown', errMsg);
    process.exit(2);
  }
});
`
}

/**
 * Write Windsurf hooks at user-level and workspace-level.
 * Also configures the HTTP proxy to route through Intutic's TLS MITM layer.
 *
 * @param workspaceRoot - Absolute workspace root.
 * @param proxyUrl      - Intutic proxy URL (used in the hook script comment).
 * @param proxyPort     - Local port where the Intutic proxy is listening (for TLS MITM).
 * @param workspaceId   - Workspace ID embedded in hook event payloads.
 */
export async function writeWindsurfHooks(
  workspaceRoot: string,
  proxyUrl: string,
  proxyPort = 8877,
  workspaceId = '',
): Promise<void> {
  const hookScriptDir = path.join(workspaceRoot, '.intutic', 'hooks')
  await fs.mkdir(hookScriptDir, { recursive: true })

  // Ensure hook events log directory exists
  await fs.mkdir(path.join(workspaceRoot, '.intutic', 'events'), { recursive: true })

  const hookScriptPath = path.join(hookScriptDir, 'windsurf-check.js')

  const tmpScript = hookScriptPath + '.ws-tmp'
  await fs.writeFile(tmpScript, buildHookScript(proxyUrl, workspaceRoot, workspaceId), 'utf-8')
  await fs.rename(tmpScript, hookScriptPath)
  await fs.chmod(hookScriptPath, 0o755)

  const config = buildHooksConfig(hookScriptPath)

  // 1. User-level hooks
  await fs.mkdir(WINDSURF_USER_DIR, { recursive: true })
  await atomicWriteJson(path.join(WINDSURF_USER_DIR, 'hooks.json'), config)
  log.info({ action: 'windsurf_hooks_written', level: 'user' }, 'Windsurf user-level hooks written')

  // 2. Workspace-level hooks (.windsurf/hooks.json)
  const wsWindsurfDir = path.join(workspaceRoot, '.windsurf')
  await fs.mkdir(wsWindsurfDir, { recursive: true })
  await atomicWriteJson(path.join(wsWindsurfDir, 'hooks.json'), {
    ...config,
    _note: 'Workspace-level hooks — agent may be able to modify this file. User-level hooks take precedence.',
  })
  log.info({ action: 'windsurf_hooks_written', level: 'workspace' }, 'Windsurf workspace-level hooks written')

  // 3. HTTP proxy settings → routes Windsurf's Cascade AI traffic through Intutic TLS MITM
  const wsSettings = {
    _comment: 'Intutic proxy settings — auto-generated. DO NOT EDIT.',
    _lastSync: newIso(),
    'http.proxy': `http://127.0.0.1:${proxyPort}`,
    'http.proxyStrictSSL': false, // Our CA cert handles validation
    'codeium.proxy': `http://127.0.0.1:${proxyPort}`,
  }
  await atomicWriteJson(path.join(WINDSURF_USER_DIR, 'settings.json'), wsSettings)
  log.info(
    { action: 'windsurf_proxy_configured', port: proxyPort },
    'Windsurf HTTP proxy configured for TLS MITM interception',
  )
}

async function atomicWriteJson(filePath: string, data: unknown): Promise<void> {
  const tmp = filePath + '.intutic-tmp'
  await fs.writeFile(tmp, JSON.stringify(data, null, 2) + '\n', 'utf-8')
  await fs.rename(tmp, filePath)
}
