/**
 * `intutic judge configure` — generate the local artifacts an on-prem
 * LLM-as-judge needs (LLD #70, model catalog & cohort wizard).
 *
 * Deliberately local-artifacts-only: it writes a `litellm_config.yaml` and
 * prints env / Helm snippets for the operator to apply themselves. It never
 * calls a remote API to flip anything on. `local_judge` is deliberately NOT
 * exposed through `PATCH /api/v1/gateways/:id/config`
 * (`services/control-plane/src/lib/gateway.ts`) — this command respects that
 * boundary by construction, not by omission.
 *
 * The catalog's `ref` (`${provider}/${id}`, e.g. `anthropic/claude-haiku-4-5`)
 * is already LiteLLM's own `litellm_params.model` format, so a selected
 * catalog entry needs no translation — see `infra/compose/litellm_config.yaml`
 * for the hand-written example this generates the same shape as.
 *
 * @module
 */

import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import pc from 'picocolors'
import { judgeModelChoices, findCatalogModel, normalizeModelRef } from '@intutic/shared-types'
import { createClackIO, type SetupIO } from './setup.js'

export interface JudgeConfigureOpts {
  /** Where to write the generated litellm_config.yaml. */
  out?: string
}

/** Uppercase `${PROVIDER}_API_KEY` env var LiteLLM reads for this provider's key. */
function apiKeyEnvVar(providerId: string): string {
  return `${providerId.toUpperCase()}_API_KEY`
}

/**
 * Build the litellm_config.yaml content for one judge model — the SAME
 * shape `infra/compose/litellm_config.yaml` hand-writes for its default
 * entry, generated instead of copy-pasted.
 */
export function buildLiteLLMConfigYaml(modelRef: string): string {
  const { provider, id } = normalizeModelRef(modelRef)
  const litellmModel = provider ? `${provider}/${id}` : id
  const alias = id || modelRef
  const apiKeyLine = provider ? `      api_key: os.environ/${apiKeyEnvVar(provider)}\n` : ''

  return (
    `# Generated by \`intutic judge configure\` (LLD #70). Same shape as\n` +
    `# infra/compose/litellm_config.yaml's hand-written example — add more\n` +
    `# model_list entries by hand following that file if you need more than\n` +
    `# the one judge model this command configured.\n\n` +
    `model_list:\n` +
    `  - model_name: ${alias}\n` +
    `    litellm_params:\n` +
    `      model: ${litellmModel}\n` +
    apiKeyLine +
    `\n` +
    `general_settings:\n` +
    `  master_key: os.environ/LITELLM_MASTER_KEY\n`
  )
}

function envBlock(modelAlias: string): string {
  return [
    '# Compose (infra/compose/docker-compose.gateway.yml) or your own env file:',
    'INTUTIC_GATEWAY_LOCAL_JUDGE=true',
    'LITELLM_LOCAL_URL=http://litellm:4000',
    'LITELLM_LOCAL_API_KEY=${LITELLM_MASTER_KEY}',
    `LITELLM_LOCAL_JUDGE_MODEL=${modelAlias}`,
  ].join('\n')
}

function helmSnippet(modelAlias: string): string {
  return [
    '# tools/helm/intutic-gateway values (or --set on `helm install`):',
    'proxy:',
    '  localJudge: true',
    'litellm:',
    '  enabled: true',
    `  judgeModel: "${modelAlias}"`,
    '  configMapName: ""  # leave empty to let the chart render one from this litellm_config.yaml; set your own for a pre-existing ConfigMap',
  ].join('\n')
}

export async function runJudgeConfigure(opts: JudgeConfigureOpts, io: SetupIO = createClackIO()): Promise<void> {
  io.intro(pc.bold('Intutic — On-Prem Judge Configuration'))
  io.log.info(
    'This writes local files only — it never calls a remote API. local_judge is deliberately ' +
      'not remotely configurable; apply what this generates yourself.',
  )

  // Unfiltered: a local LiteLLM instance can serve anything, including a
  // free-text alias not in the catalog at all.
  const CUSTOM = '__custom__'
  const choices = judgeModelChoices({ saasRoutableOnly: false })
  const pick = await io.select({
    message: 'Which model should the on-prem judge use?',
    options: [
      ...choices.slice(0, 30).map((m) => ({ value: m.ref, label: `${m.displayName} (${m.provider})` })),
      { value: CUSTOM, label: 'Enter a custom model reference (provider/model, or a local alias)…' },
    ],
  })
  // io.select returns setup.ts's private CANCELLED symbol on Ctrl-C, not
  // exported for identity comparison here — `typeof pick !== 'string'` is
  // the correct guard regardless, since every real answer is a string.
  if (typeof pick !== 'string') {
    io.outro('Cancelled.')
    return
  }

  let modelRef = pick
  if (pick === CUSTOM) {
    const custom = await io.text({ message: 'Model reference (e.g. anthropic/claude-haiku-4-5, or a local alias like my-org/local-qwen)' })
    if (typeof custom !== 'string' || !custom.trim()) {
      io.outro('Cancelled.')
      return
    }
    modelRef = custom.trim()
  }

  if (!findCatalogModel(modelRef)) {
    io.log.warn(`'${modelRef}' is not in the known model catalog — proceeding as a custom/local alias.`)
  }

  const yaml = buildLiteLLMConfigYaml(modelRef)
  const outPath = resolve(opts.out ?? './litellm_config.yaml')
  writeFileSync(outPath, yaml, 'utf-8')
  io.log.success(`Written to ${outPath}`)

  const { id: modelAlias } = normalizeModelRef(modelRef)
  io.note(envBlock(modelAlias || modelRef), 'Environment')
  io.note(helmSnippet(modelAlias || modelRef), 'Helm values')

  io.log.warn(
    'If this judge model will also be served by the SHARED (non-local) LiteLLM deployment, adding it to ' +
      'infra/kubernetes/base/litellm/config.yaml obligates matching entries in providerPricingService.ts\'s ' +
      'STATIC_FALLBACK_RATES and offline_bundle.json — modelNameParity.test.ts enforces this. Not required ' +
      'for a purely local/on-prem judge.',
  )

  io.outro(pc.bold('Done. Apply the env/Helm values above, then restart the gateway.'))
}
