/**
 * `intutic notifications` — notification rules: which events go to which
 * Slack channel, email addresses, webhook or PagerDuty service.
 *
 * Subcommands:
 *   - `intutic notifications list [--json]`
 *   - `intutic notifications create --event <type> --channel <channel> <target flag> [filters] [--json]`
 *   - `intutic notifications update <rule_id> [fields] [--json]`
 *   - `intutic notifications delete <rule_id> [--json]`
 *   - `intutic notifications rotate-secret <rule_id> [--json]`
 *
 * Server side: services/control-plane/src/routes/notifications.ts. A webhook
 * rule's signing secret is generated by the server and returned once — in the
 * response that created it (create, a switch to the webhook channel, or a
 * rotation) — so this prints it once, with a warning to copy it.
 *
 * @module
 */

import pc from 'picocolors'
import { log } from '../lib/logger.js'
import { fail, list, positiveInt, printSigningSecret, runApiCommand, type ApiCommandOpts } from './apiCommand.js'

const CHANNELS = ['slack', 'email', 'webhook', 'pagerduty'] as const
type Channel = (typeof CHANNELS)[number]

interface ChannelConfig {
  slackChannelId?: string
  slackChannelName?: string
  emailRecipients?: string[]
  webhookUrl?: string
  pagerdutyRoutingKey?: string
}

interface NotificationRule {
  ruleId: string
  eventType: string
  channel: Channel
  channelConfig: ChannelConfig
  filters: { severity?: string[]; harnessType?: string[]; userId?: string[] }
  cooldownMinutes: number
  enabled: boolean
  signingSecret?: string
}

/** The flags `create` and `update` share. */
export interface RuleFlags {
  event?: string
  channel?: string
  slackChannel?: string
  email?: string
  webhookUrl?: string
  pagerdutyKey?: string
  severity?: string
  harness?: string
  user?: string
  cooldown?: string
}

/**
 * The request body for the given flags: only the fields a flag set, so an
 * update leaves everything else as it is. Channel config and filters are each
 * replaced whole when any of their flags is given, as the route stores them.
 */
export function ruleBody(flags: RuleFlags): Record<string, unknown> {
  const body: Record<string, unknown> = {}
  if (flags.event !== undefined) body.eventType = flags.event
  if (flags.channel !== undefined) {
    if (!(CHANNELS as readonly string[]).includes(flags.channel)) {
      fail(`--channel must be one of ${CHANNELS.join(', ')}, got "${flags.channel}"`)
    }
    body.channel = flags.channel
  }

  const config: ChannelConfig = {}
  if (flags.slackChannel !== undefined) config.slackChannelId = flags.slackChannel
  if (flags.email !== undefined) config.emailRecipients = list(flags.email)
  if (flags.webhookUrl !== undefined) config.webhookUrl = flags.webhookUrl
  if (flags.pagerdutyKey !== undefined) config.pagerdutyRoutingKey = flags.pagerdutyKey
  if (Object.keys(config).length > 0) body.channelConfig = config

  const filters: NotificationRule['filters'] = {}
  if (flags.severity !== undefined) filters.severity = list(flags.severity)
  if (flags.harness !== undefined) filters.harnessType = list(flags.harness)
  if (flags.user !== undefined) filters.userId = list(flags.user)
  if (Object.keys(filters).length > 0) body.filters = filters

  if (flags.cooldown !== undefined) body.cooldownMinutes = positiveInt(flags.cooldown, '--cooldown')
  return body
}

function target(rule: NotificationRule): string {
  const c = rule.channelConfig
  switch (rule.channel) {
    case 'slack': return c.slackChannelName ?? c.slackChannelId ?? '—'
    case 'email': return c.emailRecipients?.join(', ') ?? '—'
    case 'webhook': return c.webhookUrl ?? '—'
    case 'pagerduty': return 'routing key set'
  }
}

function printRule(rule: NotificationRule): void {
  log.field('Rule ID', rule.ruleId)
  log.field('Event', rule.eventType)
  log.field('Channel', `${rule.channel} → ${target(rule)}`)
  const filters = Object.entries(rule.filters).filter(([, v]) => v && v.length > 0)
  if (filters.length > 0) log.field('Filters', filters.map(([k, v]) => `${k}=${(v as string[]).join(',')}`).join('; '))
  log.field('Cooldown', `${rule.cooldownMinutes} min`)
  log.field('Enabled', rule.enabled ? pc.green('yes') : pc.dim('no'))
}

/** `intutic notifications list` */
export async function runNotificationsList(opts: ApiCommandOpts): Promise<void> {
  await runApiCommand(
    opts,
    'Failed to list notification rules',
    (client) => client.get<{ rules: NotificationRule[] }>('/api/v1/notifications/rules'),
    (res) => {
      log.header('Intutic — Notification Rules')
      if (res.rules.length === 0) {
        log.dim('  No notification rules.')
        return
      }
      for (const rule of res.rules) {
        console.log('')
        printRule(rule)
      }
    },
  )
}

/** `intutic notifications create` */
export async function runNotificationsCreate(opts: ApiCommandOpts & RuleFlags & { disabled?: boolean }): Promise<void> {
  const body = ruleBody(opts)
  if (opts.disabled) body.enabled = false
  await runApiCommand(
    opts,
    'Failed to create notification rule',
    (client) => client.post<NotificationRule>('/api/v1/notifications/rules', body),
    (rule) => {
      log.success('Notification rule created.')
      printRule(rule)
      printSigningSecret(rule.signingSecret)
    },
  )
}

/** `intutic notifications update <rule_id>` */
export async function runNotificationsUpdate(
  ruleId: string,
  opts: ApiCommandOpts & RuleFlags & { enable?: boolean; disable?: boolean },
): Promise<void> {
  if (opts.enable && opts.disable) fail('Pass --enable or --disable, not both.')
  const body = ruleBody(opts)
  if (opts.enable) body.enabled = true
  if (opts.disable) body.enabled = false
  if (Object.keys(body).length === 0) fail('Nothing to update: pass at least one field to change.')
  await runApiCommand(
    opts,
    `Failed to update notification rule ${ruleId}`,
    (client) => client.put<NotificationRule>(`/api/v1/notifications/rules/${encodeURIComponent(ruleId)}`, body),
    (rule) => {
      log.success('Notification rule updated.')
      printRule(rule)
      printSigningSecret(rule.signingSecret)
    },
  )
}

/** `intutic notifications delete <rule_id>` */
export async function runNotificationsDelete(ruleId: string, opts: ApiCommandOpts): Promise<void> {
  await runApiCommand(
    opts,
    `Failed to delete notification rule ${ruleId}`,
    (client) => client.del<{ ok: boolean }>(`/api/v1/notifications/rules/${encodeURIComponent(ruleId)}`),
    () => log.success(`Notification rule ${ruleId} deleted.`),
  )
}

/** `intutic notifications rotate-secret <rule_id>` */
export async function runNotificationsRotateSecret(ruleId: string, opts: ApiCommandOpts): Promise<void> {
  await runApiCommand(
    opts,
    `Failed to replace the signing secret of ${ruleId}`,
    (client) =>
      client.post<{ ruleId: string; signingSecret: string }>(
        `/api/v1/notifications/rules/${encodeURIComponent(ruleId)}/signing-secret`,
      ),
    (res) => {
      log.success(`New signing secret for ${res.ruleId}; deliveries are signed with it from now on.`)
      printSigningSecret(res.signingSecret)
    },
  )
}
