import * as fs from 'fs';
import * as path from 'path';
import { tokens, type ColorRoles } from './tokens.js';

/**
 * Writes dist/variables.css from tokens.ts. Light is the default; dark applies
 * under `[data-theme='dark']` (the dashboard, which resolves "system" before
 * first paint) and `.dark` (VitePress). No media query here: each app decides
 * the theme, so an explicit choice always wins over the OS setting.
 */

const block = (entries: Record<string, string>, prefix: string) =>
  Object.entries(entries)
    .map(([name, value]) => `  --${prefix}${name}: ${value};`)
    .join('\n');

const colorBlock = (colors: ColorRoles, charts: string[], shadows: Record<string, string>) =>
  [
    block(colors, 'color-'),
    charts.map((value, i) => `  --chart-${i + 1}: ${value};`).join('\n'),
    block(shadows, 'shadow-'),
  ].join('\n\n');

const { typography: type } = tokens;

const fontFaces = type.faces
  .map(
    (face) => `@font-face {
  font-family: 'Grift';
  font-style: ${face.style};
  font-weight: ${face.weight};
  font-display: swap;
  src: url('/fonts/${face.file}') format('woff2');
}`,
  )
  .join('\n\n');

const css = `/* Generated by packages/theme/src/build-tokens.ts from tokens.ts. Do not edit. */

${fontFaces}

:root {
  color-scheme: light;

  --font-sans: ${type.fontSans};
  --font-mono: ${type.fontMono};

${block(type.size, 'text-')}

${block(type.weight, 'weight-')}

${block(type.leading, 'leading-')}

${block(type.tracking, 'tracking-')}

${block(tokens.space, 'space-')}

${block(tokens.radius, 'radius-')}

${block(tokens.motion.duration, 'duration-')}

${block(tokens.motion.ease, 'ease-')}

${block(tokens.zIndex, 'z-')}

${colorBlock(tokens.colors.light, tokens.charts.light, tokens.shadows.light)}
}

[data-theme='dark'],
.dark {
  color-scheme: dark;

${colorBlock(tokens.colors.dark, tokens.charts.dark, tokens.shadows.dark)}
}
`;

const distDir = path.resolve(process.cwd(), './dist');
fs.mkdirSync(distDir, { recursive: true });
fs.writeFileSync(path.resolve(distDir, './variables.css'), css);
console.log('Central CSS variables generated in dist/variables.css');
