package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/intutic/terraform-provider-intutic/internal/client"
)

// Notification-rule routes: routes/notifications.ts (createRuleSchema,
// updateRuleSchema, requireChannelConfigKey).
var notificationChannels = []string{"slack", "email", "webhook", "pagerduty"}

const rulesPath = "/api/v1/notifications/rules"

type notificationRuleResource struct{ client *client.Client }

type notificationRuleModel struct {
	ID              types.String `tfsdk:"id"`
	EventType       types.String `tfsdk:"event_type"`
	Channel         types.String `tfsdk:"channel"`
	SlackChannelID  types.String `tfsdk:"slack_channel_id"`
	SlackChannel    types.String `tfsdk:"slack_channel_name"`
	EmailRecipients types.List   `tfsdk:"email_recipients"`
	WebhookURL      types.String `tfsdk:"webhook_url"`
	PagerdutyKey    types.String `tfsdk:"pagerduty_routing_key"`
	Severity        types.List   `tfsdk:"filter_severity"`
	HarnessType     types.List   `tfsdk:"filter_harness_type"`
	UserID          types.List   `tfsdk:"filter_user_id"`
	CooldownMinutes types.Int64  `tfsdk:"cooldown_minutes"`
	Enabled         types.Bool   `tfsdk:"enabled"`
	SigningSecret   types.String `tfsdk:"signing_secret"`
}

type apiChannelConfig struct {
	SlackChannelID   *string  `json:"slackChannelId,omitempty"`
	SlackChannelName *string  `json:"slackChannelName,omitempty"`
	EmailRecipients  []string `json:"emailRecipients,omitempty"`
	WebhookURL       *string  `json:"webhookUrl,omitempty"`
	PagerdutyKey     *string  `json:"pagerdutyRoutingKey,omitempty"`
}

type apiFilters struct {
	Severity    []string `json:"severity,omitempty"`
	HarnessType []string `json:"harnessType,omitempty"`
	UserID      []string `json:"userId,omitempty"`
}

type apiRule struct {
	RuleID          string           `json:"ruleId"`
	EventType       string           `json:"eventType"`
	Channel         string           `json:"channel"`
	ChannelConfig   apiChannelConfig `json:"channelConfig"`
	Filters         apiFilters       `json:"filters"`
	CooldownMinutes int64            `json:"cooldownMinutes"`
	Enabled         bool             `json:"enabled"`
	SigningSecret   string           `json:"signingSecret"`
}

func newNotificationRuleResource() resource.Resource { return &notificationRuleResource{} }

var (
	_ resource.ResourceWithImportState    = (*notificationRuleResource)(nil)
	_ resource.ResourceWithValidateConfig = (*notificationRuleResource)(nil)
	_ resource.ResourceWithModifyPlan     = (*notificationRuleResource)(nil)
)

func (r *notificationRuleResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_notification_rule"
}

func (r *notificationRuleResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	filter := func(what string) schema.ListAttribute {
		return schema.ListAttribute{
			ElementType: types.StringType,
			Optional:    true,
			Description: "Only notify for events whose " + what + " is one of these.",
			Validators:  []validator.List{listvalidator.SizeAtLeast(1)},
		}
	}
	resp.Schema = schema.Schema{
		Description: "A notification rule (`/api/v1/notifications/rules`): which event goes to which Slack channel, " +
			"email addresses, webhook or PagerDuty service. Each channel needs its own target attribute. A webhook " +
			"rule is always signed; its signing secret is generated by the API, returned once and kept in state " +
			"as `signing_secret`.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				Description:   "The rule id (`nr_…`).",
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"event_type": schema.StringAttribute{
				Required:    true,
				Description: "The event that triggers the rule, for example `incident.created`.",
			},
			"channel": schema.StringAttribute{
				Required:    true,
				Description: "One of `slack`, `email`, `webhook`, `pagerduty`.",
				Validators:  []validator.String{stringvalidator.OneOf(notificationChannels...)},
			},
			"slack_channel_id":   schema.StringAttribute{Optional: true, Description: "For `slack`: the channel id."},
			"slack_channel_name": schema.StringAttribute{Optional: true, Description: "For `slack`: the channel name."},
			"email_recipients": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Description: "For `email`: 1–20 addresses, one message each.",
				Validators:  []validator.List{listvalidator.SizeBetween(1, 20)},
			},
			"webhook_url": schema.StringAttribute{
				Optional:    true,
				Description: "For `webhook`: an https URL on a public address.",
			},
			"pagerduty_routing_key": schema.StringAttribute{
				Optional:    true,
				Sensitive:   true,
				Description: "For `pagerduty`: the integration's routing key. The API only ever returns it masked.",
			},
			"filter_severity":     filter("severity"),
			"filter_harness_type": filter("harness type"),
			"filter_user_id":      filter("user id"),
			"cooldown_minutes": schema.Int64Attribute{
				Optional:    true,
				Computed:    true,
				Default:     int64default.StaticInt64(15),
				Description: "Minimum minutes between notifications from this rule (1–1440). Defaults to 15.",
				Validators:  []validator.Int64{int64validator.Between(1, 1440)},
			},
			"enabled": schema.BoolAttribute{
				Optional: true,
				Computed: true,
				Default:  booldefault.StaticBool(true),
			},
			"signing_secret": schema.StringAttribute{
				Computed:  true,
				Sensitive: true,
				Description: "For `webhook`: the secret that signs each delivery. Generated when the rule becomes a " +
					"webhook; null after an import, since the API returns it only once.",
			},
		},
	}
}

func (r *notificationRuleResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = configuredClient(req.ProviderData, &resp.Diagnostics)
}

// ValidateConfig is requireChannelConfigKey: each channel needs its target.
func (r *notificationRuleResource) ValidateConfig(ctx context.Context, req resource.ValidateConfigRequest, resp *resource.ValidateConfigResponse) {
	var cfg notificationRuleModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &cfg)...)
	if resp.Diagnostics.HasError() || cfg.Channel.IsUnknown() {
		return
	}
	missing := func(attr, msg string) {
		resp.Diagnostics.AddAttributeError(path.Root(attr), "Missing channel target", msg)
	}
	switch cfg.Channel.ValueString() {
	case "slack":
		if cfg.SlackChannelID.IsNull() && cfg.SlackChannel.IsNull() {
			missing("slack_channel_id", "A slack rule needs slack_channel_id or slack_channel_name.")
		}
	case "email":
		if cfg.EmailRecipients.IsNull() {
			missing("email_recipients", "An email rule needs at least one email_recipients entry.")
		}
	case "webhook":
		if cfg.WebhookURL.IsNull() {
			missing("webhook_url", "A webhook rule needs webhook_url.")
		}
	case "pagerduty":
		if cfg.PagerdutyKey.IsNull() {
			missing("pagerduty_routing_key", "A pagerduty rule needs pagerduty_routing_key.")
		}
	}
}

// ModifyPlan keeps the signing secret across updates unless the rule becomes,
// or stops being, a webhook — the only changes that make the API issue or
// drop one (notificationHubService.ts updateRule).
func (r *notificationRuleResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if req.State.Raw.IsNull() || req.Plan.Raw.IsNull() {
		return
	}
	var plan, state notificationRuleModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	switch {
	case plan.Channel.Equal(state.Channel):
		plan.SigningSecret = state.SigningSecret
	case plan.Channel.ValueString() != "webhook":
		plan.SigningSecret = types.StringNull()
	default:
		plan.SigningSecret = types.StringUnknown()
	}
	resp.Diagnostics.Append(resp.Plan.Set(ctx, &plan)...)
}

func (m *notificationRuleModel) body(ctx context.Context, diags *diag.Diagnostics) map[string]any {
	cfg := map[string]any{}
	if !m.SlackChannelID.IsNull() {
		cfg["slackChannelId"] = m.SlackChannelID.ValueString()
	}
	if !m.SlackChannel.IsNull() {
		cfg["slackChannelName"] = m.SlackChannel.ValueString()
	}
	if v := listStrings(ctx, m.EmailRecipients, diags); v != nil {
		cfg["emailRecipients"] = v
	}
	if !m.WebhookURL.IsNull() {
		cfg["webhookUrl"] = m.WebhookURL.ValueString()
	}
	if !m.PagerdutyKey.IsNull() {
		cfg["pagerdutyRoutingKey"] = m.PagerdutyKey.ValueString()
	}
	filters := map[string]any{}
	if v := listStrings(ctx, m.Severity, diags); v != nil {
		filters["severity"] = v
	}
	if v := listStrings(ctx, m.HarnessType, diags); v != nil {
		filters["harnessType"] = v
	}
	if v := listStrings(ctx, m.UserID, diags); v != nil {
		filters["userId"] = v
	}
	return map[string]any{
		"eventType":       m.EventType.ValueString(),
		"channel":         m.Channel.ValueString(),
		"channelConfig":   cfg,
		"filters":         filters,
		"cooldownMinutes": m.CooldownMinutes.ValueInt64(),
		"enabled":         m.Enabled.ValueBool(),
	}
}

// maskedRoutingKey is the API's mask (notificationHubService.ts maskSecret).
func maskedRoutingKey(key string) string {
	runes := []rune(key)
	if len(runes) > 6 {
		runes = runes[:6]
	}
	return string(runes) + "…"
}

// applyTo copies the server's view. The routing key comes back masked: the
// configured key is kept when its mask matches, so only a key changed outside
// Terraform shows as a difference.
func (a *apiRule) applyTo(m *notificationRuleModel) {
	m.ID = types.StringValue(a.RuleID)
	m.EventType = types.StringValue(a.EventType)
	m.Channel = types.StringValue(a.Channel)
	m.SlackChannelID = stringOrNull(a.ChannelConfig.SlackChannelID)
	m.SlackChannel = stringOrNull(a.ChannelConfig.SlackChannelName)
	m.EmailRecipients = stringList(a.ChannelConfig.EmailRecipients)
	m.WebhookURL = stringOrNull(a.ChannelConfig.WebhookURL)
	switch masked := a.ChannelConfig.PagerdutyKey; {
	case masked == nil:
		m.PagerdutyKey = types.StringNull()
	case m.PagerdutyKey.IsNull() || maskedRoutingKey(m.PagerdutyKey.ValueString()) != *masked:
		m.PagerdutyKey = types.StringValue(*masked)
	}
	m.Severity = stringList(a.Filters.Severity)
	m.HarnessType = stringList(a.Filters.HarnessType)
	m.UserID = stringList(a.Filters.UserID)
	m.CooldownMinutes = types.Int64Value(a.CooldownMinutes)
	m.Enabled = types.BoolValue(a.Enabled)
	if a.SigningSecret != "" {
		m.SigningSecret = types.StringValue(a.SigningSecret)
	} else if a.Channel != "webhook" || m.SigningSecret.IsUnknown() {
		m.SigningSecret = types.StringNull()
	}
}

func (r *notificationRuleResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan notificationRuleModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	var out apiRule
	if err := r.client.Post(ctx, rulesPath, plan.body(ctx, &resp.Diagnostics), &out); err != nil {
		resp.Diagnostics.AddError("Creating notification rule failed", err.Error())
		return
	}
	out.applyTo(&plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *notificationRuleResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state notificationRuleModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	var out struct {
		Rules []apiRule `json:"rules"`
	}
	if err := r.client.Get(ctx, rulesPath, &out); err != nil {
		resp.Diagnostics.AddError("Reading notification rules failed", err.Error())
		return
	}
	for i := range out.Rules {
		if out.Rules[i].RuleID == state.ID.ValueString() {
			out.Rules[i].applyTo(&state)
			resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
			return
		}
	}
	resp.State.RemoveResource(ctx)
}

func (r *notificationRuleResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state notificationRuleModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	var out apiRule
	if err := r.client.Put(ctx, rulesPath+"/"+esc(state.ID.ValueString()), plan.body(ctx, &resp.Diagnostics), &out); err != nil {
		resp.Diagnostics.AddError("Updating notification rule failed", err.Error())
		return
	}
	out.applyTo(&plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *notificationRuleResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state notificationRuleModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	err := r.client.Delete(ctx, rulesPath+"/"+esc(state.ID.ValueString()), nil)
	if err != nil && !client.IsNotFound(err) {
		resp.Diagnostics.AddError("Deleting notification rule failed", err.Error())
	}
}

func (r *notificationRuleResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
}
