package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"slices"
	"sort"
	"strings"
	"unicode/utf16"

	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/intutic/terraform-provider-intutic/internal/client"
)

// SIEM destination routes: routes/siem.ts (CreateDestinationSchema,
// UpdateDestinationSchema, validateConfig, MASKED_FIELDS_BY_ADAPTER).
const siemPath = "/api/v1/siem/destinations"

var siemAdapters = []string{"syslog_cef", "webhook_https", "gcs", "s3", "splunk_hec", "datadog_logs"}

// siemSecretFields are the config fields the API masks on every read
// (MASKED_FIELDS_BY_ADAPTER), less `signingSecret`, which the API generates
// and never accepts. They live in `secret_config`, apart from `config`.
//
// Why two attributes: the API returns these fields as `********` plus the
// last four characters. Kept inside one JSON `config`, the whole attribute
// would have to be sensitive (hiding a webhook URL or bucket name in every
// plan) and the masked read would differ from the configuration on every
// refresh. Split out, `config` stays readable and compares exactly, and each
// secret is compared through its mask: a read whose mask matches the
// configured value keeps it, so only a secret changed outside Terraform shows
// as a difference.
var siemSecretFields = map[string][]string{
	"webhook_https": {"authHeaderValue"},
	"splunk_hec":    {"token"},
	"datadog_logs":  {"apiKey"},
	"gcs":           {"credentials"},
	"s3":            {"secretAccessKey"},
}

// siemSigningSecretField is generated by the API for a webhook destination,
// masked on reads, and ignored when sent.
const siemSigningSecretField = "signingSecret"

// siemRequiredFields is validateConfig: what each adapter cannot do without.
var siemRequiredFields = map[string][]string{
	"syslog_cef":    {"host", "port"},
	"webhook_https": {"webhookUrl"},
	"splunk_hec":    {"hecUrl", "token"},
	"datadog_logs":  {"apiKey"},
	"gcs":           {"bucketName"},
	"s3":            {"bucketName"},
}

func isSiemSecretField(adapter, field string) bool {
	return field == siemSigningSecretField || slices.Contains(siemSecretFields[adapter], field)
}

// siemMask is the API's maskConfig for one value. JavaScript measures and
// slices a string in UTF-16 code units, so this does too.
func siemMask(v string) string {
	u := utf16.Encode([]rune(v))
	if len(u) > 8 {
		return "********" + string(utf16.Decode(u[len(u)-4:]))
	}
	return "********"
}

type siemDestinationResource struct{ client *client.Client }

type siemDestinationModel struct {
	ID              types.String         `tfsdk:"id"`
	Name            types.String         `tfsdk:"name"`
	AdapterType     types.String         `tfsdk:"adapter_type"`
	Config          jsontypes.Normalized `tfsdk:"config"`
	SecretConfig    types.Map            `tfsdk:"secret_config"`
	SourceTables    types.Set            `tfsdk:"source_tables"`
	BatchSize       types.Int64          `tfsdk:"batch_size"`
	FlushIntervalMs types.Int64          `tfsdk:"flush_interval_ms"`
	Enabled         types.Bool           `tfsdk:"enabled"`
	PausedReason    types.String         `tfsdk:"paused_reason"`
	SigningSecret   types.String         `tfsdk:"signing_secret"`
	RotateTriggers  types.Map            `tfsdk:"secret_rotation_triggers"`
}

type apiSiemDestination struct {
	DestinationID   string                     `json:"destinationId"`
	Name            string                     `json:"name"`
	AdapterType     string                     `json:"adapterType"`
	IsActive        bool                       `json:"isActive"`
	SourceTables    []string                   `json:"sourceTables"`
	BatchSize       int64                      `json:"batchSize"`
	FlushIntervalMs int64                      `json:"flushIntervalMs"`
	PausedReason    *string                    `json:"pausedReason"`
	Config          map[string]json.RawMessage `json:"config"`
	SigningSecret   string                     `json:"signingSecret"`
}

func newSiemDestinationResource() resource.Resource { return &siemDestinationResource{} }

var (
	_ resource.ResourceWithImportState    = (*siemDestinationResource)(nil)
	_ resource.ResourceWithValidateConfig = (*siemDestinationResource)(nil)
	_ resource.ResourceWithModifyPlan     = (*siemDestinationResource)(nil)
)

func (r *siemDestinationResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_siem_destination"
}

func (r *siemDestinationResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "A SIEM export destination (`/api/v1/siem/destinations`): where the workspace streams governance " +
			"events, and which ones. SIEM export needs the Biz Org, Enterprise or Self-host plan (or a trial); on " +
			"another plan the API refuses to create or change a destination. The adapter's credentials go in " +
			"`secret_config`, everything else in `config`. A `webhook_https` destination signs every delivery with " +
			"a secret the API generates, returns once and Terraform keeps as `signing_secret`; " +
			"`secret_rotation_triggers` replaces it. Destroying the resource deactivates the destination: the API " +
			"has no delete, so it stays listed, switched off. Needs an OWNER or ADMIN key.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				Description:   "The destination id (`siemdest_…`).",
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"name": schema.StringAttribute{
				Required:   true,
				Validators: []validator.String{stringvalidator.LengthBetween(1, 128)},
			},
			"adapter_type": schema.StringAttribute{
				Required: true,
				Description: "One of `syslog_cef`, `webhook_https`, `gcs`, `s3`, `splunk_hec`, `datadog_logs`. " +
					"Changing it replaces the destination.",
				Validators:    []validator.String{stringvalidator.OneOf(siemAdapters...)},
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"config": schema.StringAttribute{
				CustomType: jsontypes.NormalizedType{},
				Optional:   true,
				Description: "The adapter's settings as a JSON object, without its credentials. Required keys: " +
					"`syslog_cef` `host` and `port`; `webhook_https` `webhookUrl`; `splunk_hec` `hecUrl`; " +
					"`gcs` and `s3` `bucketName`. Optional ones include `useTls` (syslog), `prefix` and `projectId` " +
					"(gcs), `region` and `accessKeyId` (s3), `source` and `sourcetype` (splunk), `intakeUrl` and " +
					"`hostname` (datadog). URLs must be public https endpoints.",
				Validators: []validator.String{jsonObjectValidator{}},
			},
			"secret_config": schema.MapAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Sensitive:   true,
				Description: "The adapter's credentials, which the API only ever returns masked: `webhook_https` " +
					"`authHeaderValue` (optional); `splunk_hec` `token`; `datadog_logs` `apiKey`; `gcs` " +
					"`credentials` (a base64-encoded service-account key); `s3` `secretAccessKey`. A value changed " +
					"outside Terraform shows as a difference. Removing an optional credential clears it.",
			},
			"source_tables": schema.SetAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
				Default:     setdefault.StaticValue(types.SetValueMust(types.StringType, []attr.Value{})),
				Description: "The event sources to stream, for example `governance_incidents` or `gate_decisions`. " +
					"Empty (the default) streams every source except the opt-in ones; `gate_decisions` is sent " +
					"only to a destination that lists it.",
			},
			"batch_size": schema.Int64Attribute{
				Optional:    true,
				Computed:    true,
				Default:     int64default.StaticInt64(100),
				Description: "Events per bucket object (`gcs`, `s3`). Defaults to 100.",
				Validators:  []validator.Int64{int64validator.AtLeast(1)},
			},
			"flush_interval_ms": schema.Int64Attribute{
				Optional:    true,
				Computed:    true,
				Default:     int64default.StaticInt64(60000),
				Description: "Longest wait, in milliseconds, before a bucket object is written with fewer events. Defaults to 60000.",
				Validators:  []validator.Int64{int64validator.AtLeast(1)},
			},
			"enabled": schema.BoolAttribute{
				Optional: true,
				Computed: true,
				Default:  booldefault.StaticBool(true),
			},
			"paused_reason": schema.StringAttribute{
				Computed: true,
				Description: "Why an enabled destination streams nothing, such as a plan without SIEM export; " +
					"null while it streams.",
			},
			"signing_secret": schema.StringAttribute{
				Computed:  true,
				Sensitive: true,
				Description: "For `webhook_https`: the secret that signs each delivery. Set on create and when " +
					"`secret_rotation_triggers` changes; null after an import, since the API returns it only then.",
			},
			"secret_rotation_triggers": secretRotationTriggersAttribute("a `webhook_https` destination"),
		},
	}
}

func (r *siemDestinationResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = configuredClient(req.ProviderData, &resp.Diagnostics)
}

// configMap decodes `config`; nil when it is null, unknown or not an object
// (the attribute's validator reports that).
func (m *siemDestinationModel) configMap() map[string]json.RawMessage {
	if m.Config.IsNull() || m.Config.IsUnknown() {
		return nil
	}
	var out map[string]json.RawMessage
	if json.Unmarshal([]byte(m.Config.ValueString()), &out) != nil {
		return nil
	}
	return out
}

// present is validateConfig's truthiness: a missing, null, empty, zero or
// false value is missing.
func present(raw json.RawMessage) bool {
	var v any
	if json.Unmarshal(raw, &v) != nil {
		return false
	}
	switch v := v.(type) {
	case nil:
		return false
	case string:
		return v != ""
	case float64:
		return v != 0
	case bool:
		return v
	}
	return true
}

// ValidateConfig repeats validateConfig, and keeps each field in the
// attribute it belongs to.
func (r *siemDestinationResource) ValidateConfig(ctx context.Context, req resource.ValidateConfigRequest, resp *resource.ValidateConfigResponse) {
	var cfg siemDestinationModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &cfg)...)
	if resp.Diagnostics.HasError() {
		return
	}
	conf := cfg.configMap()
	if _, ok := conf[siemSigningSecretField]; ok {
		resp.Diagnostics.AddAttributeError(path.Root("config"), "signingSecret is generated by the API",
			"The API generates a webhook destination's signing secret and ignores one sent in config. Remove it; "+
				"read it from signing_secret and rotate it with secret_rotation_triggers.")
	}
	if cfg.AdapterType.IsUnknown() || cfg.AdapterType.IsNull() {
		return
	}
	adapter := cfg.AdapterType.ValueString()
	secretFields := siemSecretFields[adapter]

	for _, k := range sortedKeys(conf) {
		if slices.Contains(secretFields, k) {
			resp.Diagnostics.AddAttributeError(path.Root("config"), "Credential in config",
				fmt.Sprintf("%s is a credential the API masks; set it in secret_config, which is sensitive.", k))
		}
	}
	var secrets map[string]types.String
	secretsKnown := !cfg.SecretConfig.IsUnknown()
	if secretsKnown && !cfg.SecretConfig.IsNull() {
		resp.Diagnostics.Append(cfg.SecretConfig.ElementsAs(ctx, &secrets, false)...)
		for _, k := range sortedKeys(secrets) {
			if !slices.Contains(secretFields, k) {
				takes := "takes nothing"
				if len(secretFields) > 0 {
					takes = "takes only " + strings.Join(secretFields, ", ")
				}
				resp.Diagnostics.AddAttributeError(path.Root("secret_config"), "Not a credential of this adapter",
					fmt.Sprintf("The %s adapter has no credential %s; its secret_config %s.", adapter, k, takes))
			}
		}
	}
	configKnown := !cfg.Config.IsUnknown()
	for _, field := range siemRequiredFields[adapter] {
		if slices.Contains(secretFields, field) {
			v, ok := secrets[field]
			if secretsKnown && (!ok || (!v.IsUnknown() && v.ValueString() == "")) {
				resp.Diagnostics.AddAttributeError(path.Root("secret_config"), "Missing adapter credential",
					fmt.Sprintf("The %s adapter needs %s in secret_config.", adapter, field))
			}
			continue
		}
		if configKnown && !present(conf[field]) {
			resp.Diagnostics.AddAttributeError(path.Root("config"), "Missing adapter setting",
				fmt.Sprintf("The %s adapter needs %s in config.", adapter, field))
		}
	}
	if !cfg.RotateTriggers.IsNull() && adapter != "webhook_https" {
		resp.Diagnostics.AddAttributeError(path.Root("secret_rotation_triggers"), "Nothing to rotate",
			"Only a webhook_https destination has a signing secret; remove secret_rotation_triggers from this "+
				adapter+" destination.")
	}
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// ModifyPlan says what an apply does to the signing secret, and checks the
// source names against the ones the API lists.
func (r *siemDestinationResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if req.Plan.Raw.IsNull() {
		return
	}
	var plan siemDestinationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	var state *siemDestinationModel
	if !req.State.Raw.IsNull() {
		state = &siemDestinationModel{}
		resp.Diagnostics.Append(req.State.Get(ctx, state)...)
	}
	if resp.Diagnostics.HasError() {
		return
	}
	plan.SigningSecret = plan.plannedSigningSecret(state)
	if state == nil || !plan.SourceTables.Equal(state.SourceTables) {
		r.checkSources(ctx, plan.SourceTables, &resp.Diagnostics)
	}
	resp.Diagnostics.Append(resp.Plan.Set(ctx, &plan)...)
}

// plannedSigningSecret is what applying m over state (nil on create) does to
// the signing secret: a new webhook destination gets one, a rotation replaces
// it, anything else keeps it.
func (m *siemDestinationModel) plannedSigningSecret(state *siemDestinationModel) types.String {
	switch {
	case m.AdapterType.IsUnknown():
		return types.StringUnknown()
	case m.AdapterType.ValueString() != "webhook_https":
		return types.StringNull()
	case state == nil || !m.AdapterType.Equal(state.AdapterType) || m.rotates(state):
		return types.StringUnknown()
	default:
		return state.SigningSecret
	}
}

// rotates reports whether applying m over an existing destination replaces
// its signing secret.
func (m *siemDestinationModel) rotates(state *siemDestinationModel) bool {
	return m.AdapterType.ValueString() == "webhook_https" && m.AdapterType.Equal(state.AdapterType) &&
		rotationDue(m.RotateTriggers, state.RotateTriggers)
}

// checkSources refuses a source name the API does not list (`sources.all` on
// the list route), as the API would on apply. When the list cannot be read
// the check is left to the apply.
func (r *siemDestinationResource) checkSources(ctx context.Context, sources types.Set, diags *diag.Diagnostics) {
	if r.client == nil || sources.IsNull() || sources.IsUnknown() || len(sources.Elements()) == 0 {
		return
	}
	for _, e := range sources.Elements() {
		if e.IsUnknown() {
			return
		}
	}
	var list struct {
		Sources struct {
			All []string `json:"all"`
		} `json:"sources"`
	}
	if err := r.client.Get(ctx, siemPath, &list); err != nil || len(list.Sources.All) == 0 {
		return
	}
	for _, s := range listStrings(ctx, sources, diags) {
		if !slices.Contains(list.Sources.All, s) {
			diags.AddAttributeError(path.Root("source_tables"), "Unknown SIEM source",
				fmt.Sprintf("%q is not a source. Valid sources: %s.", s, strings.Join(list.Sources.All, ", ")))
		}
	}
}

// apiConfig is the config the API stores: `config` with `secret_config`
// merged in.
func (m *siemDestinationModel) apiConfig(ctx context.Context, diags *diag.Diagnostics) map[string]any {
	out := map[string]any{}
	for k, v := range m.configMap() {
		out[k] = v
	}
	if !m.SecretConfig.IsNull() && !m.SecretConfig.IsUnknown() {
		var secrets map[string]string
		diags.Append(m.SecretConfig.ElementsAs(ctx, &secrets, false)...)
		for k, v := range secrets {
			out[k] = v
		}
	}
	return out
}

func (m *siemDestinationModel) sources(ctx context.Context, diags *diag.Diagnostics) []string {
	if v := listStrings(ctx, m.SourceTables, diags); v != nil {
		return v
	}
	return []string{}
}

func (m *siemDestinationModel) createBody(ctx context.Context, diags *diag.Diagnostics) map[string]any {
	return map[string]any{
		"name":            m.Name.ValueString(),
		"adapterType":     m.AdapterType.ValueString(),
		"config":          m.apiConfig(ctx, diags),
		"sourceTables":    m.sources(ctx, diags),
		"batchSize":       m.BatchSize.ValueInt64(),
		"flushIntervalMs": m.FlushIntervalMs.ValueInt64(),
	}
}

// updateBody is the PUT body for what differs from state; nil when only
// Terraform-side attributes changed. Sending only the changes keeps
// `enabled = false` alone working on a plan without SIEM export, which the API
// allows only as a request with nothing else in it, and leaves the stored
// config (and the dead-letter queue a config change resets) alone unless the
// config changed.
func (m *siemDestinationModel) updateBody(ctx context.Context, state *siemDestinationModel, diags *diag.Diagnostics) map[string]any {
	body := map[string]any{}
	if !m.Name.Equal(state.Name) {
		body["name"] = m.Name.ValueString()
	}
	if !m.Enabled.Equal(state.Enabled) {
		body["isActive"] = m.Enabled.ValueBool()
	}
	if !m.SourceTables.Equal(state.SourceTables) {
		body["sourceTables"] = m.sources(ctx, diags)
	}
	if !m.BatchSize.Equal(state.BatchSize) {
		body["batchSize"] = m.BatchSize.ValueInt64()
	}
	if !m.FlushIntervalMs.Equal(state.FlushIntervalMs) {
		body["flushIntervalMs"] = m.FlushIntervalMs.ValueInt64()
	}
	sameConfig := m.Config.Equal(state.Config)
	if !sameConfig && !m.Config.IsNull() && !state.Config.IsNull() {
		eq, d := m.Config.StringSemanticEquals(ctx, state.Config)
		diags.Append(d...)
		sameConfig = eq
	}
	if !sameConfig || !m.SecretConfig.Equal(state.SecretConfig) {
		config := m.apiConfig(ctx, diags)
		// The API keeps a stored credential the config leaves out; an empty
		// string is what clears one, so a credential removed from
		// secret_config is sent as "".
		for k := range state.SecretConfig.Elements() {
			if _, kept := config[k]; !kept {
				config[k] = ""
			}
		}
		body["config"] = config
	}
	if len(body) == 0 {
		return nil
	}
	return body
}

// readSecretConfig is the secret_config to keep after a read. The API returns
// each credential masked; a configured value whose mask matches is kept, so
// the plan stays empty, and anything else (a credential changed outside
// Terraform, or an import) reads as the mask. A change that keeps the length
// above 8 and the last four characters cannot be seen through the mask. A
// cleared credential reads back empty and is absent here, unless the
// configuration names it as "".
func readSecretConfig(adapter string, apiConfig map[string]json.RawMessage, prior types.Map) types.Map {
	priorValues := map[string]string{}
	if !prior.IsNull() && !prior.IsUnknown() {
		for k, v := range prior.Elements() {
			if s, ok := v.(types.String); ok && !s.IsNull() && !s.IsUnknown() {
				priorValues[k] = s.ValueString()
			}
		}
	}
	elems := map[string]attr.Value{}
	for _, field := range siemSecretFields[adapter] {
		var masked string
		if json.Unmarshal(apiConfig[field], &masked) != nil {
			continue
		}
		p, configured := priorValues[field]
		if masked == "" {
			if configured && p == "" {
				elems[field] = types.StringValue("")
			}
			continue
		}
		if configured && siemMask(p) == masked {
			elems[field] = types.StringValue(p)
		} else {
			elems[field] = types.StringValue(masked)
		}
	}
	if len(elems) == 0 && (prior.IsNull() || prior.IsUnknown()) {
		return types.MapNull(types.StringType)
	}
	return types.MapValueMust(types.StringType, elems)
}

// applyTo copies the server's view onto m, which holds the configuration
// (plan) or the previous state.
func (a *apiSiemDestination) applyTo(m *siemDestinationModel) {
	m.ID = types.StringValue(a.DestinationID)
	m.Name = types.StringValue(a.Name)
	m.AdapterType = types.StringValue(a.AdapterType)

	plain := map[string]json.RawMessage{}
	for k, v := range a.Config {
		if !isSiemSecretField(a.AdapterType, k) {
			plain[k] = v
		}
	}
	if len(plain) > 0 || !m.Config.IsNull() {
		raw, _ := json.Marshal(plain) // map keys sort, so the text is stable
		m.Config = jsontypes.NewNormalizedValue(string(raw))
	}
	m.SecretConfig = readSecretConfig(a.AdapterType, a.Config, m.SecretConfig)

	sources := a.SourceTables
	if sources == nil {
		sources = []string{}
	}
	m.SourceTables = stringSet(sources)
	m.BatchSize = types.Int64Value(a.BatchSize)
	m.FlushIntervalMs = types.Int64Value(a.FlushIntervalMs)
	m.Enabled = types.BoolValue(a.IsActive)
	m.PausedReason = stringOrNull(a.PausedReason)
	if a.SigningSecret != "" {
		m.SigningSecret = types.StringValue(a.SigningSecret)
	} else if a.AdapterType != "webhook_https" || m.SigningSecret.IsUnknown() {
		m.SigningSecret = types.StringNull()
	}
}

func (r *siemDestinationResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan siemDestinationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	body := plan.createBody(ctx, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	var out apiSiemDestination
	if err := r.client.Post(ctx, siemPath, body, &out); err != nil {
		resp.Diagnostics.AddError("Creating SIEM destination failed", err.Error())
		return
	}
	wantEnabled := plan.Enabled.ValueBool()
	// Record the signing secret before anything else can fail: it is never shown again.
	out.applyTo(&plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)

	// The API creates every destination active.
	if !wantEnabled {
		var updated apiSiemDestination
		if err := r.client.Put(ctx, siemPath+"/"+esc(out.DestinationID), map[string]any{"isActive": false}, &updated); err != nil {
			resp.Diagnostics.AddError("Disabling the new SIEM destination failed", err.Error())
			return
		}
		updated.applyTo(&plan)
		resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
	}
}

func (r *siemDestinationResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state siemDestinationModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	var out apiSiemDestination
	if err := r.client.Get(ctx, siemPath+"/"+esc(state.ID.ValueString()), &out); err != nil {
		if client.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Reading SIEM destination failed", err.Error())
		return
	}
	out.applyTo(&state)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *siemDestinationResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state siemDestinationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := esc(state.ID.ValueString())
	body := plan.updateBody(ctx, &state, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	var out apiSiemDestination
	var err error
	if body != nil {
		err = r.client.Put(ctx, siemPath+"/"+id, body, &out)
	} else {
		err = r.client.Get(ctx, siemPath+"/"+id, &out)
	}
	if err != nil {
		resp.Diagnostics.AddError("Updating SIEM destination failed", err.Error())
		return
	}
	out.applyTo(&plan)
	// The PUT response says nothing of the signing secret; ModifyPlan planned
	// the state's value unless a rotation is due.
	if plan.rotates(&state) {
		secret, err := rotateSigningSecret(ctx, r.client, siemPath+"/"+id+"/signing-secret")
		if err != nil {
			// The old secret is still the live one; keeping the old triggers
			// makes the next apply try again.
			plan.SigningSecret = state.SigningSecret
			plan.RotateTriggers = state.RotateTriggers
			resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
			resp.Diagnostics.AddError("Rotating the SIEM destination's signing secret failed", err.Error())
			return
		}
		plan.SigningSecret = types.StringValue(secret)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

// Delete deactivates: the API keeps every destination it has created.
func (r *siemDestinationResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state siemDestinationModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	err := r.client.Delete(ctx, siemPath+"/"+esc(state.ID.ValueString()), nil)
	if err != nil && !client.IsNotFound(err) {
		resp.Diagnostics.AddError("Deactivating SIEM destination failed", err.Error())
	}
}

func (r *siemDestinationResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
}
