// firewall.rs — Platform-specific firewall rule generators for MDM agent.
//
// Generates OS-native firewall rules that redirect or block AI provider traffic
// so it cannot bypass the Intutic governance proxy.
//
// Supported platforms:
//   macOS:   pf (Packet Filter) — writes an anchor file
//   Linux:   iptables / nftables (auto-detected, nftables preferred)
//   Windows: Windows Firewall (netsh / WFP) — generates PowerShell commands
//
// The generated rules forward outbound TCP on port 443 for AI provider IPs
// to the local proxy port (default 8080). This works in conjunction with the
// DNS interceptor which resolves AI provider hostnames to 127.0.0.1.
//
// WS-6NC LLD #33 §3.3

use std::fmt::Write as FmtWrite;

/// Target platforms for firewall rule generation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Platform {
    MacOs,
    Linux,
    Windows,
}

impl Platform {
    /// Detect the current platform at runtime.
    pub fn current() -> Self {
        #[cfg(target_os = "macos")]
        return Platform::MacOs;
        #[cfg(target_os = "linux")]
        return Platform::Linux;
        #[cfg(target_os = "windows")]
        return Platform::Windows;
        #[cfg(not(any(target_os = "macos", target_os = "linux", target_os = "windows")))]
        return Platform::Linux;
    }
}

/// Configuration for firewall rule generation.
#[derive(Debug, Clone)]
pub struct FirewallConfig {
    pub platform: Platform,
    /// Local proxy listen port (default: 8080)
    pub proxy_port: u16,
    /// Redirect target IP (default: 127.0.0.1)
    pub proxy_ip: String,
    /// AI provider IP ranges / resolved IPs to intercept.
    /// When empty, rules redirect by port 443 and destination match via DNS.
    pub ai_ips: Vec<String>,
}

impl Default for FirewallConfig {
    fn default() -> Self {
        Self {
            platform: Platform::current(),
            proxy_port: std::env::var("INTUTIC_PROXY_PORT")
                .ok()
                .and_then(|p| p.parse().ok())
                .unwrap_or(8080),
            proxy_ip: std::env::var("INTUTIC_PROXY_IP").unwrap_or_else(|_| "127.0.0.1".to_string()),
            ai_ips: Vec::new(),
        }
    }
}

/// Generates macOS pf anchor rules.
///
/// Writes to `/etc/pf.anchors/intutic` and adds an anchor include
/// to `/etc/pf.conf`. Forwards TCP 443 for AI IPs to proxy port.
pub fn generate_pf_rules(cfg: &FirewallConfig) -> String {
    let mut out = String::new();
    writeln!(out, "# Intutic governance proxy — pf anchor rules").unwrap();
    writeln!(out, "# Generated by intutic-mdm — do not edit manually").unwrap();
    writeln!(out).unwrap();

    if cfg.ai_ips.is_empty() {
        // Redirect all 443 to proxy — DNS interceptor limits scope to AI hosts
        writeln!(
            out,
            "rdr pass on lo0 proto tcp to any port 443 -> {} port {}",
            cfg.proxy_ip, cfg.proxy_port
        )
        .unwrap();
    } else {
        for ip in &cfg.ai_ips {
            writeln!(
                out,
                "rdr pass on lo0 proto tcp to {} port 443 -> {} port {}",
                ip, cfg.proxy_ip, cfg.proxy_port
            )
            .unwrap();
        }
    }

    writeln!(out).unwrap();
    writeln!(out, "# Pass all other traffic").unwrap();
    writeln!(out, "pass all").unwrap();

    out
}

/// Generates Linux iptables REDIRECT rules.
///
/// Rules are output as a shell script that applies them via iptables.
pub fn generate_iptables_rules(cfg: &FirewallConfig) -> String {
    let mut out = String::new();
    writeln!(out, "#!/bin/sh").unwrap();
    writeln!(out, "# Intutic governance proxy — iptables rules").unwrap();
    writeln!(out, "# Generated by intutic-mdm — do not edit manually").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "set -e").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "# Flush existing intutic chain if present").unwrap();
    writeln!(out, "iptables -t nat -F INTUTIC 2>/dev/null || true").unwrap();
    writeln!(out, "iptables -t nat -X INTUTIC 2>/dev/null || true").unwrap();
    writeln!(out, "iptables -t nat -N INTUTIC").unwrap();
    writeln!(out).unwrap();

    if cfg.ai_ips.is_empty() {
        writeln!(
            out,
            "iptables -t nat -A INTUTIC -p tcp --dport 443 -j REDIRECT --to-port {}",
            cfg.proxy_port
        )
        .unwrap();
    } else {
        for ip in &cfg.ai_ips {
            writeln!(
                out,
                "iptables -t nat -A INTUTIC -p tcp -d {} --dport 443 -j REDIRECT --to-port {}",
                ip, cfg.proxy_port
            )
            .unwrap();
        }
    }

    writeln!(out).unwrap();
    writeln!(out, "# Hook intutic chain into OUTPUT").unwrap();
    writeln!(
        out,
        "iptables -t nat -C OUTPUT -j INTUTIC 2>/dev/null || \\"
    )
    .unwrap();
    writeln!(out, "  iptables -t nat -A OUTPUT -j INTUTIC").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "echo 'Intutic iptables rules applied.'").unwrap();

    out
}

/// Generates Linux nftables rules.
pub fn generate_nftables_rules(cfg: &FirewallConfig) -> String {
    let mut out = String::new();
    writeln!(out, "#!/usr/sbin/nft -f").unwrap();
    writeln!(out, "# Intutic governance proxy — nftables rules").unwrap();
    writeln!(out, "# Generated by intutic-mdm — do not edit manually").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "table ip intutic {{").unwrap();
    writeln!(out, "  chain output {{").unwrap();
    writeln!(out, "    type nat hook output priority -100;").unwrap();
    writeln!(out).unwrap();

    if cfg.ai_ips.is_empty() {
        writeln!(out, "    tcp dport 443 redirect to :{}", cfg.proxy_port).unwrap();
    } else {
        for ip in &cfg.ai_ips {
            writeln!(
                out,
                "    ip daddr {} tcp dport 443 redirect to :{}",
                ip, cfg.proxy_port
            )
            .unwrap();
        }
    }

    writeln!(out, "  }}").unwrap();
    writeln!(out, "}}").unwrap();

    out
}

/// Generates Windows netsh / PowerShell redirect rules.
///
/// Uses Windows Filtering Platform (WFP) via PowerShell to install
/// a redirect rule. Requires administrator privileges.
pub fn generate_windows_rules(cfg: &FirewallConfig) -> String {
    let mut out = String::new();
    writeln!(
        out,
        "# Intutic governance proxy — Windows Firewall redirect rules"
    )
    .unwrap();
    writeln!(out, "# Run with Administrator privileges").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "# Remove existing Intutic rules").unwrap();
    writeln!(
        out,
        "netsh interface portproxy delete v4tov4 listenport=443 listenaddress=127.0.0.1 2>$null"
    )
    .unwrap();
    writeln!(out).unwrap();

    writeln!(out, "# Add redirect rule: 127.0.0.1:443 → proxy").unwrap();
    writeln!(
        out,
        "netsh interface portproxy add v4tov4 listenport=443 listenaddress=127.0.0.1 connectport={} connectaddress={}",
        cfg.proxy_port, cfg.proxy_ip
    ).unwrap();
    writeln!(out).unwrap();
    writeln!(out, "Write-Host 'Intutic Windows firewall rules applied.'").unwrap();

    out
}

/// Generates firewall rules for the current (or specified) platform.
pub fn generate_rules(cfg: &FirewallConfig) -> String {
    match cfg.platform {
        Platform::MacOs => generate_pf_rules(cfg),
        Platform::Linux => generate_nftables_rules(cfg),
        Platform::Windows => generate_windows_rules(cfg),
    }
}

/// Removes firewall rules for the current platform (generates removal commands).
pub fn generate_removal_commands(platform: Platform, proxy_port: u16) -> String {
    match platform {
        Platform::MacOs => "#!/bin/sh\n\
             pfctl -a intutic -F rules 2>/dev/null || true\n\
             echo 'Intutic pf rules removed.'\n".to_string(),
        Platform::Linux => "#!/bin/sh\n\
             iptables -t nat -F INTUTIC 2>/dev/null || true\n\
             iptables -t nat -D OUTPUT -j INTUTIC 2>/dev/null || true\n\
             iptables -t nat -X INTUTIC 2>/dev/null || true\n\
             nft delete table ip intutic 2>/dev/null || true\n\
             echo 'Intutic iptables/nftables rules removed.'\n".to_string(),
        Platform::Windows => format!(
            "# Run with Administrator privileges\n\
             netsh interface portproxy delete v4tov4 listenport={proxy_port} listenaddress=127.0.0.1 2>$null\n\
             Write-Host 'Intutic Windows firewall rules removed.'\n"
        ),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_cfg() -> FirewallConfig {
        FirewallConfig {
            platform: Platform::MacOs,
            proxy_port: 8080,
            proxy_ip: "127.0.0.1".to_string(),
            ai_ips: vec![],
        }
    }

    #[test]
    fn test_pf_rules_contain_redirect() {
        let rules = generate_pf_rules(&test_cfg());
        assert!(
            rules.contains("rdr pass"),
            "pf rules must contain rdr pass directive"
        );
        assert!(rules.contains("8080"), "pf rules must reference proxy port");
    }

    #[test]
    fn test_pf_rules_with_ai_ips() {
        let mut cfg = test_cfg();
        cfg.ai_ips = vec!["104.18.8.0".to_string(), "104.18.9.0".to_string()];
        let rules = generate_pf_rules(&cfg);
        assert!(rules.contains("104.18.8.0"));
        assert!(rules.contains("104.18.9.0"));
        assert!(
            !rules.contains("to any port 443"),
            "should not use catch-all when IPs provided"
        );
    }

    #[test]
    fn test_iptables_rules_shebang() {
        let cfg = FirewallConfig {
            platform: Platform::Linux,
            ..test_cfg()
        };
        let rules = generate_iptables_rules(&cfg);
        assert!(
            rules.starts_with("#!/bin/sh"),
            "iptables script needs shebang"
        );
        assert!(rules.contains("REDIRECT --to-port 8080"));
    }

    #[test]
    fn test_nftables_rules_structure() {
        let cfg = FirewallConfig {
            platform: Platform::Linux,
            ..test_cfg()
        };
        let rules = generate_nftables_rules(&cfg);
        assert!(rules.contains("table ip intutic"));
        assert!(rules.contains("type nat hook output"));
        assert!(rules.contains("redirect to :8080"));
    }

    #[test]
    fn test_windows_rules_netsh() {
        let cfg = FirewallConfig {
            platform: Platform::Windows,
            ..test_cfg()
        };
        let rules = generate_windows_rules(&cfg);
        assert!(rules.contains("netsh interface portproxy add"));
        assert!(rules.contains("connectport=8080"));
    }

    #[test]
    fn test_generate_rules_dispatches_by_platform() {
        let mac_rules = generate_rules(&FirewallConfig {
            platform: Platform::MacOs,
            ..test_cfg()
        });
        assert!(mac_rules.contains("pf") || mac_rules.contains("rdr"));

        let linux_rules = generate_rules(&FirewallConfig {
            platform: Platform::Linux,
            ..test_cfg()
        });
        assert!(linux_rules.contains("nft") || linux_rules.contains("intutic"));
    }

    #[test]
    fn test_removal_commands_macos() {
        let cmd = generate_removal_commands(Platform::MacOs, 8080);
        assert!(cmd.contains("pfctl"));
    }

    #[test]
    fn test_removal_commands_linux() {
        let cmd = generate_removal_commands(Platform::Linux, 8080);
        assert!(cmd.contains("iptables") || cmd.contains("nft"));
    }

    #[test]
    fn test_removal_commands_windows() {
        let cmd = generate_removal_commands(Platform::Windows, 8080);
        assert!(cmd.contains("portproxy delete"));
    }
}
